### ISSUE TITLE
out of memory error tagging

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#10020]
Expected text language: Dutch
Exception in thread "main" java.lang.OutOfMemoryError
        at java.base/java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:214)
        at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:206)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:173)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:178)
        at org.languagetool.tools.StringTools.readerToString(StringTools.java:309)
        at org.languagetool.commandline.Main.getFilteredText(Main.java:340)
        at org.languagetool.commandline.Main.runOnFile(Main.java:166)
        at org.languagetool.commandline.Main.main(Main.java:454)

The exact command is:
		java -Dfile.encoding=utf-8 -jar languagetool-commandline.jar -t -b -l nl -c "UTF-8" $CORPUS > $LTROOT/tagged.txt
The corpus is a text file of 1.1 GB

There is no problem with a corpus of .5 GB

Is the file read into memory in full? System memory is not the issue, of 64 GB, there is still 50 GB available.

**Comment by baarsrj** [comment]
I can work around it, using -r

**Comment by danielnaber** [comment]
> Is the file read into memory in full?

Yes, it's read into the memory available to Java (not the systems' memory, the amount available to Java can be changed with a parameter like `-Xmx8000M`).
