### ISSUE TITLE
[en] UNIT_SPACE throws an error sometimes during testing

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool#10397]
Under Windows, using both IntelliJ IDEA and maven directly, I tend to get a bogus report: 

```Running XML validation for en/grammar.xml...
Running XML validation for en/style.xml...
Running XML validation for /org/languagetool/rules/en/remote-rule-filters.xml...
Running pattern rule tests for English (org.languagetool.language.English)... 
Check rule id uniqueness for English...
Loaded 6118 rules...
Check that sentence start tag is not included in <marker>....
Check that <unify-ignore> is not at the start of <unify>....
Check parenthesis and back references in synthesis matches...
Checking regexp syntax of 6088 rules for English...
Checking messages for 'TBD' etc of 6088 rules for English...
Checking example sentences of 6088 rules for English...
Testing rule 100...
Testing rule 200...
Testing rule 300...
Testing rule 400...
Testing rule 500...
Testing rule 600...
Testing rule 700...
Testing rule 800...
Testing rule 900...
Testing rule 1000...
Testing rule 1100...
Testing rule 1200...
Testing rule 1300...
Testing rule 1400...
Testing rule 1500...
Testing rule 1600...
Testing rule 1700...
Testing rule 1800...
Testing rule 1900...
Testing rule 2000...
Testing rule 2100...
Testing rule 2200...
Testing rule 2300...
Testing rule 2400...
Testing rule 2500...
Testing rule 2600...
Testing rule 2700...
Testing rule 2800...
Testing rule 2900...
Testing rule 3000...
Testing rule 3100...
Testing rule 3200...
Testing rule 3300...
Testing rule 3400...
Testing rule 3500...
Testing rule 3600...
Testing rule 3700...
Testing rule 3800...
Testing rule 3900...
Testing rule 4000...
Testing rule 4100...
Testing rule 4200...
Testing rule 4300...
Testing rule 4400...
Testing rule 4500...
Testing rule 4600...
Testing rule 4700...
Testing rule 4800...
Testing rule 4900...
Testing rule 5000...
Testing rule 5100...
Testing rule 5200...
Testing rule 5300...
Testing rule 5400...
Testing rule 5500...
Testing rule 5600...
Testing rule 5700...
Testing rule 5800...
Testing rule 5900...
Testing rule 6000...
Skipped 0 rules for variant language to avoid checking rules more than once
6088 rules tested.
Running XML validation for en/en-US/grammar.xml...
Running XML validation for en/en-US/style.xml...
Running XML validation for /org/languagetool/rules/en/remote-rule-filters.xml...
Running pattern rule tests for English (US) (org.languagetool.language.AmericanEnglish)... 
Check rule id uniqueness for English (US)...
Loaded 6175 rules...
Check that sentence start tag is not included in <marker>....
Check that <unify-ignore> is not at the start of <unify>....
Check parenthesis and back references in synthesis matches...
Checking regexp syntax of 6142 rules for English (US)...
Checking messages for 'TBD' etc of 6142 rules for English (US)...
Checking example sentences of 6142 rules for English (US)...
Testing rule 100...
Testing rule 200...
Testing rule 300...
Testing rule 400...
Testing rule 500...
Skipped 5561 rules for variant language to avoid checking rules more than once
6142 rules tested.
Running XML validation for en/en-GB/grammar.xml...
Running XML validation for en/en-GB/style.xml...
Running XML validation for /org/languagetool/rules/en/remote-rule-filters.xml...
Running pattern rule tests for English (GB) (org.languagetool.language.BritishEnglish)... 
Check rule id uniqueness for English (GB)...
Loaded 6157 rules...
Check that sentence start tag is not included in <marker>....
Check that <unify-ignore> is not at the start of <unify>....
Check parenthesis and back references in synthesis matches...
Checking regexp syntax of 6124 rules for English (GB)...
Checking messages for 'TBD' etc of 6124 rules for English (GB)...
Checking example sentences of 6124 rules for English (GB)...
Testing rule 100...
Testing rule 200...
Testing rule 300...
Testing rule 400...
Testing rule 500...
Skipped 5561 rules for variant language to avoid checking rules more than once
6124 rules tested.
Running XML validation for en/en-AU/grammar.xml...
Running XML validation for en/en-AU/style.xml...
No rule file found at /org/languagetool/rules/en/en-AU/style.xml in classpath. THIS SHOULD BE FIXED!
Running XML validation for /org/languagetool/rules/en/remote-rule-filters.xml...
Running pattern rule tests for English (Australian) (org.languagetool.language.AustralianEnglish)... 
Check rule id uniqueness for English (Australian)...
Loaded 6124 rules...
Check that sentence start tag is not included in <marker>....
Check that <unify-ignore> is not at the start of <unify>....
Check parenthesis and back references in synthesis matches...
Checking regexp syntax of 6092 rules for English (Australian)...
Checking messages for 'TBD' etc of 6092 rules for English (Australian)...
Checking example sentences of 6092 rules for English (Australian)...
Testing rule 100...
Testing rule 200...
Testing rule 300...
Testing rule 400...
Testing rule 500...
Skipped 5561 rules for variant language to avoid checking rules more than once
6092 rules tested.
Running XML validation for en/en-CA/grammar.xml...
Running XML validation for en/en-CA/style.xml...
No rule file found at /org/languagetool/rules/en/en-CA/style.xml in classpath. THIS SHOULD BE FIXED!
Running XML validation for /org/languagetool/rules/en/remote-rule-filters.xml...
Running pattern rule tests for English (Canadian) (org.languagetool.language.CanadianEnglish)... 
Check rule id uniqueness for English (Canadian)...
Loaded 6125 rules...
Check that sentence start tag is not included in <marker>....
Check that <unify-ignore> is not at the start of <unify>....
Check parenthesis and back references in synthesis matches...
Checking regexp syntax of 6093 rules for English (Canadian)...
Checking messages for 'TBD' etc of 6093 rules for English (Canadian)...
Checking example sentences of 6093 rules for English (Canadian)...
Testing rule 100...
Testing rule 200...
Testing rule 300...
Testing rule 400...
Testing rule 500...
Skipped 5561 rules for variant language to avoid checking rules more than once
6093 rules tested.
Running XML validation for en/en-NZ/grammar.xml...
Running XML validation for en/en-NZ/style.xml...
No rule file found at /org/languagetool/rules/en/en-NZ/style.xml in classpath. THIS SHOULD BE FIXED!
Running XML validation for /org/languagetool/rules/en/remote-rule-filters.xml...
Running pattern rule tests for English (New Zealand) (org.languagetool.language.NewZealandEnglish)... 
Check rule id uniqueness for English (New Zealand)...
Loaded 6125 rules...
Check that sentence start tag is not included in <marker>....
Check that <unify-ignore> is not at the start of <unify>....
Check parenthesis and back references in synthesis matches...
Checking regexp syntax of 6092 rules for English (New Zealand)...
Checking messages for 'TBD' etc of 6092 rules for English (New Zealand)...
Checking example sentences of 6092 rules for English (New Zealand)...
Testing rule 100...
Testing rule 200...
Testing rule 300...
Testing rule 400...
Testing rule 500...
Skipped 5561 rules for variant language to avoid checking rules more than once
6092 rules tested.
Skipping English (South African) because there are no specific rules for that variant

org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule UNIT_SPACE[1] in file /org/languagetool/rules/en/grammar.xml (line -1): Did not expect error in:
  ...their sample variance, and σ2N their population variance.
  Analyzed token readings: [/SENT_START*] .[./.*,./PCT*] .[./.*,./PCT*] .[./.*,./PCT*] their[their/PRP$*,they/PRP$_A3P*,they/PRP$_A3S*]  [ /null*] sample[sample/JJ,I-NP-singular]  [ /null*] variance[variance/NN:UN,E-NP-singular] ,[,/,*,,/PCT*,,/,*,O]  [ /null*] and[and/CC,O]  [ /null*] σ2N[σ2N/null,B-PP]  [ /null*] their[their/PRP$,they/PRP$_A3P,they/PRP$_A3S,B-NP-singular]  [ /null*] population[population/NN:UN,I-NP-singular]  [ /null*] variance[variance/NN:UN,E-NP-singular] .[./.*,./SENT_END*,./PCT*,O]


	at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:502)
	at org.languagetool.rules.patterns.PatternRuleTest.testCorrectSentences(PatternRuleTest.java:822)
	at org.languagetool.rules.patterns.PatternRuleTest.lambda$testGrammarRulesFromXML$2(PatternRuleTest.java:536)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1573)

```

**Comment by milekpl** [comment]
@jaumeortola any idea why this happens?

**Comment by jaumeortola** [comment]
No idea. I will be able to try it on Windows at some point.

**Comment by milekpl** [comment]
@jaumeortola it was only Java 19 doing this. Closing.
