### ISSUE TITLE
Plugin crashing in LO Writer

### ISSUE THREAD

**Issue by LanceHaverkamp** [languagetool-org/languagetool#10440]
In the middle of checking a large document (200-page book), the plugin is repeatedly crashing with this type of error:

An error has occurred in LanguageTool 6.3.1 (2023-12-30 21:58:50 +0000):
java.lang.NullPointerException
Stacktrace:
java.lang.NullPointerException
at org.languagetool.openoffice.SpellAndGrammarCheckDialog.getErrorsFromCache(SpellAnd GrammarCheckDialog.java:515)
at org.languagetool.openoffice.SpellAnd
GrammarCheckDialog.getNextGrammatikOrSpellErrorInParagraph(SpellAndGrammarCheckDialog.java:558)
at org.languagetool.openoffice.SpellAndGrammarCheckDialog.getNextErrorInParagraph(SpellAndGrammarCheckDialog.java:493)
at org.languagetool.openoffice.SpellAndGrammarCheckDialog.access$7500(SpellAndGrammarCheckDialog.java:107)
at org.languagetool.openoffice.SpellAndGrammarCheckDialog$LtCheckDialog.getNextError(SpellAndGrammarCheckDialog.java:2206)
at org.languagetool.openoffice.SpellAnd GrammarCheckDialog$LtCheckDialog.goto
NextError(SpellAndGrammarCheckDialog.java:1894)
at org.languagetool.openoffice.SpellAndGrammarCheckDialog$LtCheckDialog.goto NextError(SpellAndGrammarCheckDialog.java:1881)
at org.languagetool.openoffice.SpellAndGrammarCheckDialog$LtCheckDialog.changeText(SpellAndGrammarCheckDialog.java:2557)
at
org.languagetool.openoffice.SpellAnd GrammarCheckDialog$LtCheckDialog.access$8100(SpellAndGrammarCheckDialog.java:803)
at org.languagetool.openoffice.SpellAndGrammarCheckDialog$LtCheckDialog$11.run(SpellAndGrammarCheckDialog.java:2328)
at java.base/java.lang.Thread.run(Thread.java:829)
OS: Linux on amd64, Java version 11.0.22 from Oracle Corporation
--
Running LO Version: 7.6.4.1 (X86_64) / LibreOffice Community
Build ID: 60(Build:1)
CPU threads: 4; OS: Linux 6.8; UI render: default; VCL: kf5 (cairo+xcb)
Locale: en-US (en_US.UTF-8); UI: en-US
Calc: threaded
on OpenSUSE Tumbleweed (SlowRoll)

**Comment by FredKruse** [comment]
Please test, if this bug also occurs with LT 6.4 and provide feedback.

**Comment by LanceHaverkamp** [comment]
> Please test, if this bug also occurs with LT 6.4 and provide feedback.

It did clear up with a later version.
