### ISSUE TITLE
Use latest version of Indriya

### ISSUE THREAD

**Issue by tneves86** [languagetool-org/languagetool#10485]
in my project, Indriya is a direct dependency, but we can't update it to version 2.2 because then languagetool breaks at runtime with the following stacktrace:

...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.languagetool.rules.en.UnitConversionRuleImperial
	at org.languagetool.language.BritishEnglish.getRelevantRules(BritishEnglish.java:53)
	at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:477)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:309)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:278)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:338)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:244)
	... 43 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: KILOGRAM [in thread "CachePreloaderService-Workerpool-26-thread-12"]
	at org.languagetool.rules.AbstractUnitConversionRule.<clinit>(AbstractUnitConversionRule.java:57)
	at org.languagetool.language.BritishEnglish.getRelevantRules(BritishEnglish.java:53)
	at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:477)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:309)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:278)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:338)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:244)
	... 13 more

**Comment by WemanAndo** [comment]
@tneves86 I have the same issue. Did you find a fix?

**Comment by tneves86** [comment]
Not really, we stick with indriya 1.0 meanwhile. That's quite a limiting factor :/
