### ISSUE TITLE
Libreoffice addon doesn't work, clicking buttons does nothing

### ISSUE THREAD

**Issue by kuba-orlik** [languagetool-org/languagetool#10507]
I've installed LT plugin for Libreoffice 24.2.2.2. Plugin version is 6.3.1. The plugin installs, and I see the buttons in the toolbar: 

![image](https://github.com/languagetool-org/languagetool/assets/2697916/28e8560f-c97a-4b2d-99aa-5a174d14eb13)

However, clicking any of the buttons doesn't do anything. In the terminal output I can see the following errors: 

```
java.lang.NoClassDefFoundError: Could not initialize class javax.swing.JOptionPane
	at org.languagetool.openoffice.MessageHandler$DialogThread.run(MessageHandler.java:184)
	at org.languagetool.openoffice.MessageHandler.showMessage(MessageHandler.java:151)
	at org.languagetool.openoffice.MessageHandler.showMessage(MessageHandler.java:143)
	at org.languagetool.openoffice.MultiDocumentsHandler.testDocLanguage(MultiDocumentsHandler.java:1791)
	at org.languagetool.openoffice.MultiDocumentsHandler.trigger(MultiDocumentsHandler.java:1567)
	at org.languagetool.openoffice.Main.trigger(Main.java:207)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk/lib/libawt_xawt.so [in thread "Thread-97"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1993)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
	at java.desktop/java.awt.Component.<clinit>(Component.java:624)
	... 6 more
java.lang.NoClassDefFoundError: Could not initialize class com.sun.java.swing.plaf.gtk.GTKLookAndFeel
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.desktop/javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:2036)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:638)
	at org.languagetool.openoffice.MultiDocumentsHandler.setJavaLookAndFeel(MultiDocumentsHandler.java:1825)
	at org.languagetool.openoffice.MultiDocumentsHandler.getCheckResults(MultiDocumentsHandler.java:214)
	at org.languagetool.openoffice.MultiDocumentsHandler.doProofreading(MultiDocumentsHandler.java:200)
	at org.languagetool.openoffice.Main.doProofreading(Main.java:80)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit [in thread "Thread-125"]
	at java.desktop/java.awt.Insets.<clinit>(Insets.java:92)
	at java.desktop/javax.swing.plaf.synth.SynthLookAndFeel.<clinit>(SynthLookAndFeel.java:102)
	... 8 more

```

**Comment by hopp19** [comment]
> I've installed LT plugin for Libreoffice 24.2.2.2. Plugin version is 6.3.1.

Not a LibO user myself, but the latest LT release is v6.4, <https://languagetool.org/download/>.  Looking at the commit log, there have been a few commits related to LibO extension.

**Comment by kuba-orlik** [comment]
With 6.4, the error in the terminal seems to be gone, but clicking the button still gives me nothing:

[Screencast from 2024-04-20 14-15-31.webm](https://github.com/languagetool-org/languagetool/assets/2697916/7c516fc2-2792-4703-8f4d-e5821e4db8b0)

**Comment by FredKruse** [comment]
@kuba-orlik 
Please give me the following information: Which operating system and java version are you using? What language do you work in? Please send me the LT log file (After unsuccessfully clicking on the information button)?
