### ISSUE TITLE
Stacktrace w NullPointer Exception

### ISSUE THREAD

**Issue by drwetter** [languagetool-org/languagetool#10540]
Hi,

thanks for the tool!

Probably since version 6 I encountered a stacktrace caused by a pointer pointing not to where it should 

![image](https://github.com/languagetool-org/languagetool/assets/8036727/f50902c5-d6b1-4b6b-96b4-ee034a3ced9b)

Le me know if I can provide more information

**Comment by FredKruse** [comment]
I think this is not a dramatic problem. LibreOffice exited before the LT cache could be saved. In the worst-case scenario, no cache was saved, and the grammar check would have to be carried out all over again the next time it was called up. Data should not have been lost. However, the problem has now been resolved. Please test it with the snapshot tomorrow.

**Comment by drwetter** [comment]
Will do and report back

However I would have ignored this exception if LT would work afterwards. It doesn't though.

**Comment by drwetter** [comment]
Sorry about the question, maybe I missed something: how long does that take? Or is there a build which I can grab?

![image](https://github.com/languagetool-org/languagetool/assets/8036727/7661eac3-d168-412b-bdcd-cf5161fe3060)

**Comment by drwetter** [comment]
Giving up after 315 min CPU time.

**Comment by FredKruse** [comment]
You can find The latest snapshot here:
https://internal1.languagetool.org/snapshots/ (newest OXT)

**Comment by drwetter** [comment]
Ok, thanks! Tried it and there's no stacktrace. So it looks good.

I believe though I have another problem, so you might want to ignore  my statement above _However I would have ignored this exception if LT would work afterwards. It doesn't though._ It looks like with my default font neither LT nor spellchecking works. If I just choose another font both work.

For LT and just FYI: Looks I couldn't roll back from the snapshot to 6.4. There was no menu item "background check enabled" (translated in to English myself as I have a German UI). And there was another stacktrace when starting wit v6.4 again:

```
java.lang.NumberFormatException: For input string: "i8"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Integer.parseInt(Integer.java:652)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at org.languagetool.gui.Configuration.parseConfigurableRuleValues(Configuration.java:1475)
at org.languagetool.gui.Configuration.loadCurrentProfile(Configuration.java:1405)
at org.languagetool.gui.Configuration.loadConfiguration(Configuration.java:1232)
at org.languagetool.gui.Configuration.loadConfiguration(Configuration.java:1181)
at org.languagetool.gui.Configuration.<init>(Configuration.java:249)
at org.languagetool.openoffice.LtSpellChecker.runLTSpellChecker(LtSpellChecker.java:410)
at org.languagetool.openoffice.LtSpellChecker.<init>(LtSpellChecker.java:88)
at org.languagetool.openoffice.SingletonFactory.createInstanceWithContext(SingletonFactory.java:52)
```

However as said you were right regarding the other stacktrace and my assessment that it doesn't work was likely not related to LT. Thus closing
