### ISSUE TITLE
Libreoffice + LanguageTool 6.4 java.lang.NullPointerException: Cannot invoke org.languagetool.openoffice.CacheIO.setDocumentPath

### ISSUE THREAD

**Issue by bunk3m** [languagetool-org/languagetool#10605]
For some reason today, while doing a LibreOffice "Save as", I've started receiving  the following error:
```
LT office integration log from Tue May 21 09:42:19 EDT 2024

LanguageTool 6.4 (2024-03-28 14:05:28 +0100, 0e9362b)
OS: Windows 11 10.0 on amd64
LibreOffice 24.2.3.2 (The Document Foundation), en-US
Java-Version: 17.0.11, max. Heap-Space: 8028 MB, LT Heap Space Limit: 7225 MB

Spell Cache read from: C:\Users\username\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtSpellCache.lcz
MultiDocumentsHandler: getLinguisticServices: linguServices set: is NOT null
Document 0 created; docID = C1
MultiDocumentsHandler: LtHelper: local: en-CA
Document 1 created; docID = C2
java.lang.NullPointerException: Cannot invoke "org.languagetool.openoffice.CacheIO.setDocumentPath(com.sun.star.lang.XComponent)" because the return value of "org.languagetool.openoffice.SingleDocument.access$500(org.languagetool.openoffice.SingleDocument)" is null
    at org.languagetool.openoffice.SingleDocument$LTDokumentEventListener.documentEventOccured(SingleDocument.java:1635)

Disposing document has no content: Wait for 1000 milliseconds
Document 2 created; docID = C3
java.lang.NullPointerException: Cannot invoke "org.languagetool.openoffice.CacheIO.setDocumentPath(com.sun.star.lang.XComponent)" because the return value of "org.languagetool.openoffice.SingleDocument.access$500(org.languagetool.openoffice.SingleDocument)" is null
    at org.languagetool.openoffice.SingleDocument$LTDokumentEventListener.documentEventOccured(SingleDocument.java:1635)
```
Environment:
```
LanguageTool 6.4 (2024-03-28 14:05:28 +0100, 0e9362b)
OS: Windows 11 10.0 (amd64)
LibreOffice 24.2.3.2 (The Document Foundation), en-US
Java version: 17.0.11 (Eclipse Adoptium)
Java max/total/free memory: 8028MB, 200MB, 144MB
```
![2024-05-21_10-01_LanguageTools6 4_Error](https://github.com/languagetool-org/languagetool/assets/3494567/ed749ac4-7a59-4956-b894-f863f1b84b2d)

**Comment by FredKruse** [comment]
It is the same issue as #10585.
The issue should be solved. Please test it with the 6.5-snapshot tomorrow and close the issue.
