### ISSUE TITLE
can't use custom server in word add-in

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [languagetool-org/languagetool#10724]
I'm using the word addin with a local languagetool server running on port 8081.

I have `http://localhost:8081/v2` set as the server URL in the word add-in. When I use the "check document" feature, on the demo text, I get this error message: "http://localhost:8081/v2: A network error occurred. Please check your internet connection." and it says "no issues found". Aren't there supposed to be errors in the demo text?

Meanwhile, the server logs show this:

```
2024-07-12 10:16:00.945 GMT+02:00 INFO  org.languagetool.server.LanguageToolHttpHandler Handling OPTIONS /v2/check
2024-07-12 10:16:00.947 GMT+02:00 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'Missing 'text' or 'data' parameter', sending HTTP code 400. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0, User agent param: null, Referrer: null, language: null, h: 1, r: 15, time: 2m: ALL, l: DEFAULT, Stacktrace follows:org.languagetool.server.BadRequestException: Missing 'text' or 'data' parameter
        at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:168)
        at org.languagetool.server.ApiV2.lambda$handleRequest$4(ApiV2.java:86)
        at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
        at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:86)
        at org.languagetool.server.LanguageToolHttpHandler.lambda$handle$0(LanguageToolHttpHandler.java:206)
        at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:206)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:848)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:817)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2024-07-12 10:16:00.947 GMT+02:00 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 2ms; sending code 400
2024-07-12 10:16:00.948 GMT+02:00 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2024-07-12 10:16:01.014 GMT+02:00 INFO  org.languagetool.server.TextChecker Check done: 260 chars, en-US[auto], requestId: null, #5, null, 0/9 matches, 65ms, agent:mswordpremiumJS-demo, version: 1.2.17, sent, q:0, h:1, dH:1, r:16, m:all, premium: false
2024-07-12 10:16:01.014 GMT+02:00 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 66ms; sending code 200
```

Any ideas what might be the problem?

**Comment by ryanwinter** [comment]
I appended `/v2` to the end of my URL and now it works. Still getting errors in the logs though but I can just ignore that.
