### ISSUE TITLE
[pt-PT] Importing entities — 2024-07-11

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10722]
Heya, @p-goulart ,

I tried to import them, first in the pt-PT grammar.xml:

```
<!DOCTYPE rules [
        <!ENTITY % messages   SYSTEM "../../resource/pt/entities/messages.ent" >
        <!ENTITY % datetime   SYSTEM "../../resource/pt/entities/datetime.ent" >
        <!ENTITY % misc       SYSTEM "../../resource/pt/entities/misc.ent"     >
        <!ENTITY % abbrev     SYSTEM "../../resource/pt/entities/abbrev.ent"   >
        <!ENTITY % paronyms   SYSTEM "../../resource/pt/entities/paronyms.ent" >
        <!ENTITY % verbs      SYSTEM "../../resource/pt/entities/verbs.ent"    >
        <!ENTITY % languages  SYSTEM "../../resource/pt/entities/languages.ent">
        <!ENTITY % postal     SYSTEM "../../resource/pt/entities/postal.ent"   >
        <!ENTITY % hyphenised SYSTEM "../../resource/pt/entities/hyphenised.ent"   >
        <!ENTITY % chars      SYSTEM "../../resource/pt/entities/chars.ent"    >
        %messages;
        %datetime;
        %misc;
        %abbrev;
        %paronyms;
        %verbs;
        %languages;
        %postal;
        %hyphenised;
        %chars;


<!ENTITY expressoes_invariaveis_pt_pt "algema|afazere|alvíssara|anai|antolho|apetrecho|arra|arredore|boda|brócol[io]|cã|calça|calenda|ceroula|cócega|condolência|confin|endoença|esponsai|esposório|exéquia|fasto|féria|feze|finança|hemorróida|mane|núpcia|óculo|olheira|pantalona|parabén|pêsame|petrecho|pi[ck]le|primícia|reticência|suspensório|treva|víscera|vívere">

<!ENTITY pontos_cardeais_capitalizados "Norte|Sul|Este|Oeste|Ocidente|Oriente|Nascente|Poente|Nordeste|Sudeste|Noroeste|Sudoeste">

        ]>
```

I had to manually add the extra two entities because `TESTRULES PT-PT` was saying they weren't found.

Now a `TESTRULES PT-PT` gives a ton of errors:

```
Testing rule 1300...
Skipped 2055 rules for variant language to avoid checking rules more than once
3393 rules tested.
Exception in thread "main" org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule VERBO_HIFENIZADOR_VERBOS_2[3] in file /org/languagetool/rules/pt/pt-PT/grammar.xml (line 2434): Did not expect error in:
  Ao invés de estar por aí caçando qualquer mala na rua pra te esquecer ou para me esquecer.
  Analyzed token readings: [/SENT_START*] Ao[a:o/SPS00:DA0MS0*]  [ /null*] invés[invés/NCMS000]  [ /null*] de[de/SPS00]  [ /null*] estar[estar/VMN0000,estar/VMN01S0,estar/VMN03S0]  [ /null*] por[por/SPS00]  [ /null*] aí[aí/I,aí/NCMS000,aí/RG]  [ /null*] caçando[caçar/VMG0000]  [ /null*] qualquer[qualquer/DI0CS0]  [ /null*] mala[mala/NCFS000]  [ /null*] na[em:o/SPS00:DA0FS0]  [ /null*] rua[rua/NCFS000]  [ /null*] pra[pra:o/SPS00:DA0FS0,pra/SPS00]  [ /null*] te[tu/PP2CSO00]  [ /null*] esquecer[esquecer/VMN0000,esquecer/VMN01S0,esquecer/VMN03S0,esquecer/VMSF1S0,esquecer/VMSF3S0]  [ /null*] ou[ou/CC]  [ /null*] para[para/CC,para/SPS00]  [ /null*] me[eu/PP1CSO00]  [ /null*] esquecer[esquecer/VMN0000,esquecer/VMN01S0,esquecer/VMN03S0,esquecer/VMSF1S0,esquecer/VMSF3S0] .[./SENT_END*,./_PUNCT_PERIOD*,./_PUNCT*]

        at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:502)
        at org.languagetool.rules.patterns.PatternRuleTest.testCorrectSentences(PatternRuleTest.java:822)
        at org.languagetool.rules.patterns.PatternRuleTest.lambda$testGrammarRulesFromXML$2(PatternRuleTest.java:536)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule VERBO_HIFENIZADOR_VERBOS_2[3] in file /org/languagetool/rules/pt/pt-PT/grammar.xml (line 2434): Did not expect error in:
  N?o tenho certeza se tenho tempo o bastante para te ajudar.
  Analyzed token readings: [/SENT_START*] N?o[n?o/RN*]  [ /null*] tenho[ter/VMIP1S0]  [ /null*] certeza[certeza/NCFS000]  [ /null*] se[se/CS,se/PP3CNO00]  [ /null*] tenho[ter/VMIP1S0]  [ /null*] tempo[tempo/NCMS000]  [ /null*] o[o/DA0MS0,o/PD0MS000,ele/PP3MSA00]  [ /null*] bastante[bastante/RG]  [ /null*] para[para/CC,para/SPS00]  [ /null*] te[tu/PP2CSO00]  [ /null*] ajudar[ajudar/VMN0000,ajudar/VMN01S0,ajudar/VMN03S0,ajudar/VMSF1S0,ajudar/VMSF3S0] .[./SENT_END*,./_PUNCT_PERIOD*,./_PUNCT*]

        at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:502)
        at org.languagetool.rules.patterns.PatternRuleTest.testCorrectSentences(PatternRuleTest.java:822)
        at org.languagetool.rules.patterns.PatternRuleTest.lambda$testGrammarRulesFromXML$2(PatternRuleTest.java:536)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule VERBO_HIFENIZADOR_VERBOS_2[3] in file /org/languagetool/rules/pt/pt-PT/grammar.xml (line 2434): "Foi muito bom te ver de novo."
Errors expected: 1
Errors found   : 0
Message: Forma hifenizada. Será que quis dizer:
Analyzed token readings: [/SENT_START*] Foi[ir/VMIS3S0*,ser/VMIS3S0*]  [ /null*] muito[muito/DI0MS0,muito/NCMS000,muito/PI0MS000,muito/RG]  [ /null*] bom[bom/AQ0MS0,bom/NCMS000]  [ /null*] te[tu/PP2CSO00]  [ /null*] ver[ver/VMN0000,ver/VMN01S0,ver/VMN03S0]  [ /null*] de[de novo/RG]  [ /null*] novo[de novo/RG] .[./SENT_END*,./_PUNCT_PERIOD*,./_PUNCT*]
Matches: []
        at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:502)
        at org.languagetool.rules.patterns.PatternRuleTest.testBadSentences(PatternRuleTest.java:641)
        at org.languagetool.rules.patterns.PatternRuleTest.lambda$testGrammarRulesFromXML$2(PatternRuleTest.java:537)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule AO45_MONTHS_CASING[1] in file /org/languagetool/rules/pt/pt-PT/grammar.xml (line 3942): Incorrect input:
  O ano novo chinês é a 28 de janeiro.
Corrected sentence:
  O ano novo chinês é a 28 de Janeiro.
The correction triggered an error itself:
  AO45_MONTHS_CASING[1]:28-35:Segundo o Acordo Ortográfico de 45, os meses e as estaç?es do ano devem ser capitalizados.

        at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:502)
        at org.languagetool.rules.patterns.PatternRuleTest.testBadSentences(PatternRuleTest.java:671)
        at org.languagetool.rules.patterns.PatternRuleTest.lambda$testGrammarRulesFromXML$2(PatternRuleTest.java:537)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule AO45_MONTHS_CASING[1] in file /org/languagetool/rules/pt/pt-PT/grammar.xml (line 3942): Incorrect input:
  22 set - início do Outono.
Corrected sentence:
  22 Set - início do Outono.
The correction triggered an error itself:
  AO45_MONTHS_CASING[1]:3-6:Segundo o Acordo Ortográfico de 45, os meses e as estaç?es do ano devem ser capitalizados.

        at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:502)
        at org.languagetool.rules.patterns.PatternRuleTest.testBadSentences(PatternRuleTest.java:671)
        at org.languagetool.rules.patterns.PatternRuleTest.lambda$testGrammarRulesFromXML$2(PatternRuleTest.java:537)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Running disambiguator rule tests...
Skipping variant: Portuguese (Portugal)
Disambiguator tests successful.
Running XML bitext pattern tests...
Bitext pattern tests successful.
Validating false-friends.xml...
Validation successfully finished.
```

Could you please advise me how to solve this?

Thanks!

**Comment by marcoagpinto** [comment]
Heya, @p-goulart and @susanaboatto ,

It worked okay with style.xml, but it fails for grammar.xml.

There must be some content on the entities files that makes the rules fail.

I will look into it on Sunday.

Anyway, this is with what it should work but fails:

```
<!DOCTYPE rules [
        <!ENTITY % messages   SYSTEM "../../resource/pt/entities/messages.ent" >
        <!ENTITY % datetime   SYSTEM "../../resource/pt/entities/datetime.ent" >
        <!ENTITY % misc       SYSTEM "../../resource/pt/entities/misc.ent"     >
        <!ENTITY % abbrev     SYSTEM "../../resource/pt/entities/abbrev.ent"   >
        <!ENTITY % paronyms   SYSTEM "../../resource/pt/entities/paronyms.ent" >
        <!ENTITY % verbs      SYSTEM "../../resource/pt/entities/verbs.ent"    >
        <!ENTITY % languages  SYSTEM "../../resource/pt/entities/languages.ent">
        <!ENTITY % postal     SYSTEM "../../resource/pt/entities/postal.ent"   >
        <!ENTITY % hyphenised SYSTEM "../../resource/pt/entities/hyphenised.ent"   >
        <!ENTITY % chars      SYSTEM "../../resource/pt/entities/chars.ent"    >
        %messages;
        %datetime;
        %misc;
        %abbrev;
        %paronyms;
        %verbs;
        %languages;
        %postal;
        %hyphenised;
        %chars;

<!ENTITY expressoes_invariaveis_pt_pt "algema|afazere|alvíssara|anai|antolho|apetrecho|arra|arredore|boda|brócol[io]|cã|calça|calenda|ceroula|cócega|condolência|confin|endoença|esponsai|esposório|exéquia|fasto|féria|feze|finança|hemorróida|mane|núpcia|óculo|olheira|pantalona|parabén|pêsame|petrecho|pi[ck]le|primícia|reticência|suspensório|treva|víscera|vívere">

<!ENTITY pontos_cardeais_capitalizados "Norte|Sul|Este|Oeste|Ocidente|Oriente|Nascente|Poente|Nordeste|Sudeste|Noroeste|Sudoeste">


        ]>
```

**Comment by p-goulart** [comment]
Well, the entities may have diverged, or were simply never the same. It is entirely possible that `pt-PT` used different values for some of them. You can probably keep the diverging entities redeclared in the `pt-PT` file to make things easier.

**Comment by marcoagpinto** [comment]
> Well, the entities may have diverged, or were simply never the same. It is entirely possible that `pt-PT` used different values for some of them. You can probably keep the diverging entities redeclared in the `pt-PT` file to make things easier.

Ahhhhhh… exactly what I was thinking.

Tomorrow I will look into that.

Thank you!

**Comment by marcoagpinto** [comment]
Done!

Now I can again focus on the slow rewrite of the rules.

https://github.com/languagetool-org/languagetool/pull/10732
