### ISSUE TITLE
JDK 24 - Cannot load or parse input stream of '/org/languagetool/rules/en/grammar.xml'

### ISSUE THREAD

**Issue by cushon** [languagetool-org/languagetool#11125]
I am seeing errors like the following the JDK 24 early access builds. JDK 24 changes JAXP limits (see https://bugs.openjdk.org/browse/JDK-8343022), which is causing an error to be reported parsing `/org/languagetool/rules/en/grammar.xml`

```
Caused by: java.io.IOException: Cannot load or parse input stream of '/org/languagetool/rules/en/grammar.xml'
	at org.languagetool.rules.patterns.PatternRuleLoader.getRules(PatternRuleLoader.java:76)
	at org.languagetool.Language.getPatternRules(Language.java:598)
	at org.languagetool.JLanguageTool.activateDefaultPatternRules(JLanguageTool.java:634)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:321)
	... 40 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 28; JAXP00010004: The accumulated size of entities is "100,006" that exceeded the "100,000" limit set by "jaxp.properties".
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.checkLimit(XMLEntityScanner.java:1009)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.checkEntityLimit(XMLEntityScanner.java:968)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanContent(XMLEntityScanner.java:1072)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2760)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:891)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:827)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
	at org.languagetool.rules.patterns.PatternRuleLoader.getRules(PatternRuleLoader.java:73)
	... 43 more
```

**Comment by MrDrMcCoy** [comment]
This also affected me with Java 24 on Arch. Downgrading to 22 (GraalVM) worked around it. I hope a permanent solution can be found.
