### ISSUE TITLE
Allow reading of dictonaries on readonly filesystem

### ISSUE THREAD

**Issue by kinkykate92** [languagetool-org/languagetool#112]
I'm trying to incorporate languagetool in a Google App Engine application. Their sandbox doesn't allow write access to the file system.

I get the following stacktrace:

```
java.lang.RuntimeException: java.lang.NullPointerException
    at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:635)
    at org.languagetool.JLanguageTool.check(JLanguageTool.java:576)
    at org.languagetool.JLanguageTool.check(JLanguageTool.java:534)
    at org.languagetool.JLanguageTool.check(JLanguageTool.java:530)
    at gaelanguagetool.LanguageToolJSONServlet.checkToJson(LanguageToolJSONServlet.java:164)
    at gaelanguagetool.LanguageToolJSONServlet.doGet(LanguageToolJSONServlet.java:85)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:266)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:446)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:188)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NullPointerException
    at java.io.File.<init>(File.java:290)
    at org.languagetool.rules.spelling.hunspell.HunspellRule.getDictionaryPath(HunspellRule.java:190)
    at org.languagetool.rules.spelling.hunspell.HunspellRule.init(HunspellRule.java:163)
    at org.languagetool.rules.spelling.hunspell.HunspellRule.match(HunspellRule.java:81)
    at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:686)
    at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:995)
    at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:962)
    at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:631)
    ... 39 more
```

The line in question is here:

https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java#L190

where the dictionary is unpacked from the jar and put in a temporary directory.

I don't know much about the loading process, but would it be possible to allow this (optionally) in memory ? If there is an easy workaround for this that I could use with GAE, please let me know.

**Comment by seahrh** [comment]
I have the same issue as the OP. When I try to load English or British English, it throws the following exception:

[INFO] Caused by: java.security.AccessControlException: access denied ("java.net.NetPermission" "setDefaultAuthenticator")
[INFO]  at java.security.AccessControlContext.checkPermission(AccessControlConte
xt.java:372)
[INFO]  at java.security.AccessController.checkPermission(AccessController.java:559)
[INFO]  at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
[INFO]  at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
[INFO]  at java.net.Authenticator.setDefault(Authenticator.java:127)
[INFO]  at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleLoader.getRules(DisambiguationRuleLoader.java:59)
[INFO]  at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.loadPatternRules(XmlRuleDisambiguator.java:78)
[INFO]  at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.disambiguate(XmlRuleDisambiguator.java:59)

**Comment by danielnaber** [comment]
Please open a new issue for that, this seems to be a different problem.
