### ISSUE TITLE
HTTPServerLoadTest unstable

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1120]
The test is unstable, but the failure is difficult to reproduce:

```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: English (US)): 'This is a test of the language d
etection.'
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.languagetool.server.TextChecker.checkText(TextChecker.java:161)
        at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:105)
        at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:61)
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:145)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: English (US)): 'This is a test of the language detection.'
        at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:679)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:619)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:578)
        at org.languagetool.server.TextChecker.getRuleMatches(TextChecker.java:276)
        at org.languagetool.server.TextChecker.access$000(TextChecker.java:48)
        at org.languagetool.server.TextChecker$1.call(TextChecker.java:155)
        at org.languagetool.server.TextChecker$1.call(TextChecker.java:148)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: java.lang.RuntimeException: Could not check sentence (language: English (US)): 'This is a test of the language detection.'
        at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1157)
        at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1060)
        at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1027)
        at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:675)
        ... 10 more
Caused by: java.lang.NullPointerException
        at morfologik.fsa.builders.FSABuilder$1.compare(FSABuilder.java:61)
        at morfologik.fsa.builders.FSABuilder$1.compare(FSABuilder.java:59)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
        at java.util.TimSort.sort(TimSort.java:234)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1454)
        at java.util.Collections.sort(Collections.java:175)
        at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.getDictionary(MorfologikMultiSpeller.java:167)
        at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.getPlainTextDictSpellerOrNull(MorfologikMultiSpeller.java:142)
        at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.<init>(MorfologikMultiSpeller.java:103)
        at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.<init>(MorfologikMultiSpeller.java:73)
        at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.initSpeller(MorfologikSpellerRule.java:144)
        at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.match(MorfologikSpellerRule.java:98)
        at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:705)
        at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1115)
        ... 13 more
```

So `lines` somehow contains a `null` it seems. Maybe this is caused by @f-knorr's [commit on 2018-06-30](https://github.com/languagetool-org/languagetool/commit/f96604b658d426a8f1be86a2c557a38d51d78f93)?

**Comment by danielnaber** [comment]
Another issue is that `dictCache.invalidateAll()` seems to be called every time someone checks e.g. en-US, so the cache is invalidated all the time it seems?

**Comment by danielnaber** [comment]
Also sometimes happens on the server (i.e. not just during unit testing).
