### ISSUE TITLE
Load peak / LT process partially stuck

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1253]
LT consumed a lot of CPU but keeps working. Happened twice so far:

* 2018-11-05 (HE2)
* 2018-11-09, ca. 12:25 (HE2), load exceeded 15 for some time

This was in the stacktrace for several minutes, obviously stuck:

```
"lt-textchecker-thread-336" #4377 prio=5 os_prio=0 tid=0x00007f09b001d000 nid=0x1fc3 runnable [0x00007f0a0179e000]
   java.lang.Thread.State: RUNNABLE
        at com.sun.jna.Native.invokeInt(Native Method)
        at com.sun.jna.Function.invoke(Function.java:419)
        at com.sun.jna.Function.invoke(Function.java:354)
        at com.sun.jna.Library$Handler.invoke(Library.java:244)
        at com.sun.proxy.$Proxy4.Hunspell_spell(Unknown Source)
        at org.languagetool.rules.spelling.hunspell.Hunspell$Dictionary.misspelled(Hunspell.java:336)
        [...]
```

Restarting the LT process fixed the high load.

**Comment by danielnaber** [comment]
closing, hasn't happened for a long time.
