### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/languagetool/JLanguageTool

### ISSUE THREAD

**Issue by loretoparisi** [languagetool-org/languagetool#1287]
Built from master with `install.sh` and then `mvn package` in the root folder.
```
$ java -jar languagetool-commandline-4.4-SNAPSHOT.jar -l en --json -
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/languagetool/JLanguageTool
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.languagetool.JLanguageTool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

In my `target/` folder I have the jar built

```
-rw-r--r--  1 loretoparisi  staff  29942  7 Dic 17:37 languagetool-commandline-4.4-SNAPSHOT.jar
```

**Comment by danielnaber** [comment]
> 29942  7 Dic 17:37 languagetool-commandline-4.4-SNAPSHOT.jar

That's not the real JAR to use, please try the contents of `languagetool-standalone/target/LanguageTool-4.4-SNAPSHOT.zip` instead.

**Comment by loretoparisi** [comment]
@danielnaber thank you! I have found it here unzipped already `languagetool/languagetool-standalone/target/LanguageTool-4.4-SNAPSHOT/LanguageTool-4.4-SNAPSHOT`

here it is the folder contents

```
-rw-r--r--   1 loretoparisi  staff   55491  7 Dic 17:01 CHANGES.md
-rw-r--r--   1 loretoparisi  staff  111359  7 Dic 17:01 CHANGES.txt
-rw-r--r--   1 loretoparisi  staff   26706  7 Dic 17:01 COPYING.txt
drwxr-xr-x   5 loretoparisi  staff     160  7 Dic 17:20 META-INF
-rw-r--r--   1 loretoparisi  staff    6865  7 Dic 17:01 README.md
-rw-r--r--   1 loretoparisi  staff   29942  7 Dic 17:37 languagetool-commandline.jar
-rw-r--r--   1 loretoparisi  staff  127296  7 Dic 17:19 languagetool-server.jar
-rw-r--r--   1 loretoparisi  staff  502836  7 Dic 17:39 languagetool.jar
drwxr-xr-x  70 loretoparisi  staff    2240  7 Dic 17:20 libs
drwxr-xr-x   3 loretoparisi  staff      96  7 Dic 17:20 org
-rwxr-xr-x   1 loretoparisi  staff    1220  7 Dic 17:01 testrules.bat
-rwxr-xr-x   1 loretoparisi  staff    1212  7 Dic 17:01 testrules.sh
drwxr-xr-x  13 loretoparisi  staff     416  7 Dic 17:20 third-party-licenses
```

so you can do then with the `languagetool-commandline.jar`

```bash
echo "Hello  how are yu?" | java -jar languagetool-commandline.jar -l en-US --json - | jq
```

that will print out

```json
{
  "software": {
    "name": "LanguageTool",
    "version": "4.4-SNAPSHOT",
    "buildDate": "2018-12-07 16:11",
    "apiVersion": 1,
    "premium": false,
    "premiumHint": "You might be missing errors only the Premium version can find. Contact us at support<at>languagetoolplus.com.",
    "status": ""
  },
  "warnings": {
    "incompleteResults": false
  },
  "language": {
    "name": "English (US)",
    "code": "en-US",
    "detectedLanguage": {
      "name": "English (US)",
      "code": "en-US",
      "confidence": 1
    }
  },
  "matches": [
    {
      "message": "Possible spelling mistake found",
      "shortMessage": "Spelling mistake",
      "replacements": [
        {
          "value": "you"
        },
        {
          "value": "EU"
        },
        {
          "value": "BYU"
        },
        {
          "value": "nu"
        },
        {
          "value": "yo"
        },
        {
          "value": "Eu"
        },
        {
          "value": "GU"
        },
        {
          "value": "Ru"
        },
        {
          "value": "yum"
        },
        {
          "value": "yup"
        },
        {
          "value": "AU"
        },
        {
          "value": "AYU"
        },
        {
          "value": "Au"
        },
        {
          "value": "BU"
        },
        {
          "value": "Cu"
        },
        {
          "value": "Du"
        },
        {
          "value": "HU"
        },
        {
          "value": "JU"
        },
        {
          "value": "KU"
        },
        {
          "value": "LU"
        },
        {
          "value": "Lu"
        },
        {
          "value": "MU"
        },
        {
          "value": "NU"
        },
        {
          "value": "NYU"
        },
        {
          "value": "PU"
        },
        {
          "value": "Pu"
        },
        {
          "value": "RU"
        },
        {
          "value": "SU"
        },
        {
          "value": "TU"
        },
        {
          "value": "Tu"
        },
        {
          "value": "U"
        },
        {
          "value": "VU"
        },
        {
          "value": "WU"
        },
        {
          "value": "Wu"
        },
        {
          "value": "Y"
        },
        {
          "value": "YL"
        },
        {
          "value": "YM"
        },
        {
          "value": "YP"
        },
        {
          "value": "YT"
        },
        {
          "value": "YUG"
        },
        {
          "value": "YUL"
        },
        {
          "value": "YUM"
        },
        {
          "value": "YW"
        },
        {
          "value": "Yb"
        },
        {
          "value": "bu"
        },
        {
          "value": "cu"
        },
        {
          "value": "mu"
        },
        {
          "value": "u"
        },
        {
          "value": "y"
        },
        {
          "value": "ya"
        },
        {
          "value": "yd"
        },
        {
          "value": "ye"
        },
        {
          "value": "yr"
        },
        {
          "value": "yuk"
        },
        {
          "value": "y u"
        }
      ],
      "offset": 14,
      "length": 2,
      "context": {
        "text": "Hello how are yu? ",
        "offset": 14,
        "length": 2
      },
      "sentence": "Hello how are yu?",
      "type": {
        "typeName": "Other"
      },
      "rule": {
        "id": "MORFOLOGIK_RULE_EN_US",
        "description": "Possible spelling mistake",
        "issueType": "misspelling",
        "category": {
          "id": "TYPOS",
          "name": "Possible Typo"
        }
      },
      "ignoreForIncompleteSentence": false
    }
  ]
}
```

**Comment by donovanrichardson** [comment]
The [wiki](http://wiki.languagetool.org/development-overview#toc2) currently says "the stand-alone version [can be found] in `languagetool-standalone/target` (in a sub directory named e.g. LanguageTool-2.7-SNAPSHOT/, you cannot run the *.jar directly in the target directoy)." From what I see here, that's not correct; I was not able to run the latest standalone (`LanguageTool-4.8-SNAPSHOT.jar`) according to the instructions on that page, and it seems from the issue here that the correct procedure is to run the command line jar. Can this passage be edited in the wiki?

**Comment by danielnaber** [comment]
I'm not sure what's wrong with the wiki: you indeed cannot run `target/LanguageTool-4.8-SNAPSHOT.jar`. For the stand-alone, you need to go to `LanguageTool-4.8-SNAPSHOT/LanguageTool-4.8-SNAPSHOT/` and run one of the JARs there. For the LibreOffice extension, you can use the file in `languagetool-office-extension/target/`, but you should rename it to have an `.oxt` suffix (and you cannot run it, but install it in LibreOffice).
