### ISSUE TITLE
Exception java.lang.NoClassDefFoundError for "zh"  language code

### ISSUE THREAD

**Issue by riyazbasha131** [languagetool-org/languagetool#1384]
Hi, 
I have imported LanguageTool java stand alone from http://languagetool.org/download/LanguageTool-4.2.zip and consuming it as java library. For all other locales (like en, de) language tool working as expected but **for locale "zh"  it is throwing following exception when I call  langTool.check api**

Sample code:
`  Locale locale = new Locale("zh","" );
    Language language = Languages.getLanguageForLocale(locale);
    JLanguageTool langTool = new JLanguageTool(language);
     List<RuleMatch> matches = langTool.check("Some text");
`

Exception trace:
`java.lang.NoClassDefFoundError: cn/com/cjf/CJFBeanFactory
	at org.languagetool.tokenizers.zh.ChineseWordTokenizer.init(ChineseWordTokenizer.java:42)
	at org.languagetool.tokenizers.zh.ChineseWordTokenizer.tokenize(ChineseWordTokenizer.java:66)
	at org.languagetool.JLanguageTool.getRawAnalyzedSentence(JLanguageTool.java:843)
	at org.languagetool.JLanguageTool.getAnalyzedSentence(JLanguageTool.java:824)
	at org.languagetool.JLanguageTool.analyzeSentences(JLanguageTool.java:643)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:617)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:595)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:554)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:538)
	at com.amazon.spelltest.MainClassTest.init2(MainClassTest.java:122)
	at com.amazon.spelltest.MainClassTest.main(MainClassTest.java:24)
Caused by: java.lang.ClassNotFoundException: cn.com.cjf.CJFBeanFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
`

Could you please help me solving this problem, "zh" language is one of the primary language for which I need to check spell and grammar.

**Comment by danielnaber** [comment]
Please try with Maven (or Gradle) as documented on http://wiki.languagetool.org/java-api

**Comment by riyazbasha131** [comment]
@danielnaber Thanks for quick reply, As you suggested to use maven but my service is not maven or Gradle friendly, due to security reasons my service could only import the raw library. 
**So is this a known issue with zip package ?**

**Comment by danielnaber** [comment]
`cn/com/cjf/CJFBeanFactory` is in `cjftransform.jar` so you need to make sure that is in your classpath.

**Comment by riyazbasha131** [comment]
Thanks a lot, thats the issue. This jar was absent in my class path. thats why I am getting this exception.
