### ISSUE TITLE
LT commandline error: xgboost4j.dll was not found inside JAR

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#1461]
```

D:\lt45-snap>java -jar languagetool-commandline.jar -l en-US -eo --enablecategories TYPOS --recursive ..\temp > myerrors
.txt
Mar 12, 2019 5:38:58 PM ml.dmlc.xgboost4j.java.NativeLibLoader smartLoad
SEVERE: failed to load library from both native path and jar
Mar 12, 2019 5:38:58 PM ml.dmlc.xgboost4j.java.XGBoostJNI <clinit>
SEVERE: Failed to load native library
java.io.FileNotFoundException: File /lib/xgboost4j.dll was not found inside JAR.
        at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:121)
        at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:64)
        at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:152)
        at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:40)
        at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
        at ml.dmlc.xgboost4j.java.Booster.init(Booster.java:526)
        at ml.dmlc.xgboost4j.java.Booster.<init>(Booster.java:48)
        at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:86)
        at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:57)
        at org.languagetool.rules.spelling.suggestions.XGBoostSuggestionsOrderer$1.create(XGBoostSuggestionsOrderer.java
:58)
        at org.languagetool.rules.spelling.suggestions.XGBoostSuggestionsOrderer$1.create(XGBoostSuggestionsOrderer.java
:53)
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:60)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1041)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:342)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:265)
        at org.languagetool.rules.spelling.suggestions.XGBoostSuggestionsOrderer.<init>(XGBoostSuggestionsOrderer.java:1
04)
        at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.<init>(MorfologikSpellerRule.java:95)
        at org.languagetool.rules.en.AbstractEnglishSpellerRule.<init>(AbstractEnglishSpellerRule.java:86)
        at org.languagetool.rules.en.MorfologikAmericanSpellerRule.<init>(MorfologikAmericanSpellerRule.java:63)
        at org.languagetool.language.AmericanEnglish.getRelevantLanguageModelCapableRules(AmericanEnglish.java:62)
        at org.languagetool.JLanguageTool.updateOptionalLanguageModelRules(JLanguageTool.java:430)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:256)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:277)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:86)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:67)
        at org.languagetool.commandline.Main.<init>(Main.java:72)
        at org.languagetool.commandline.Main.main(Main.java:425)

Expected text language: English (US)
Working on D:\lt45-snap\..\temp\sentences-short.txt...

D:\lt45-snap>
```

Despite the error message, the command runs, and I get an analysis of the source data.

**Comment by danielnaber** [comment]
@fabrichter can hopefully fix this

**Comment by MikeUnwalla** [comment]
Thanks. Fixed.
