### ISSUE TITLE
"Em Maláui África" makes LT crash

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1503]
```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): 'Em Maláui África'
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:179)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:726)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:702)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:693)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:652)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:636)
	at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:106)
	at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:82)
	at org.languagetool.commandline.Main.runOnFile(Main.java:194)
	at org.languagetool.commandline.Main.main(Main.java:466)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): 'Em Maláui África'
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:176)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): 'Em Maláui África'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	... 10 more
Caused by: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): 'Em Maláui África'
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1298)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1189)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1152)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: Error analyzing sentence: '<S> Em[em/SPS00] Maláui[Maláui/null] África[África/NPFSG00,áfrica/NCFS000,</S><P/>]'
	at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:239)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:814)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1255)
	... 7 more
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 6
DA0(..
      ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.accept(Pattern.java:1813)
	at java.util.regex.Pattern.group0(Pattern.java:2908)
	at java.util.regex.Pattern.sequence(Pattern.java:2051)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at org.languagetool.synthesis.BaseSynthesizer.synthesize(BaseSynthesizer.java:124)
	at org.languagetool.rules.patterns.MatchState.toFinalString(MatchState.java:251)
	at org.languagetool.rules.patterns.PatternRuleMatcher.concatMatches(PatternRuleMatcher.java:465)
	at org.languagetool.rules.patterns.PatternRuleMatcher.formatMatches(PatternRuleMatcher.java:348)
	at org.languagetool.rules.patterns.PatternRuleMatcher.createRuleMatch(PatternRuleMatcher.java:192)
	at org.languagetool.rules.patterns.PatternRuleMatcher.match(PatternRuleMatcher.java:159)
	at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:235)
	... 9 more
```

It seems the issue is in `MatchState`:

`targetPosTag = pPosRegexMatch.matcher(targetPosTag).replaceAll(posTagReplace);`

`targetPosTag` here is the same as `pPosRegexMatch` because it still has its initial value, which makes the replacement useles. Quick fix: add `!posTags.isEmpty()` to the `if`. Maybe @TiagoSantos81 has an opinion about this? The rule causing this is `ARTICLES_PRECEDING_LOCATIONS`.

**Comment by TiagoSantos81** [comment]
>  Maybe @TiagoSantos81 has an opinion about this? The rule causing this is ARTICLES_PRECEDING_LOCATIONS.
This error has never occured to me, but I guess the problem comes from this:
`<suggestion><match no='2' postag="N.(..).+" postag_regexp="yes" postag_replace="DA0$1." case_conversion="alllower">o</match> \2</suggestion>`
The DA0$1**.** should actually be DA0$1**0**. However, I could never actually make it like that, sith it will assume it is a reference to the 10th capture ($10). 

Any suggestion on how to insert the replacement of capture 1 ($1) and add the 0 next to it, @danielnaber ?

**Comment by TiagoSantos81** [comment]
And if an opinion is requested, if this can't be done with the present code base, I would suggest improving <match/> code on the public version, so it becomes possible.
