### ISSUE TITLE
Update xgboost4j to 0.90

### ISSUE THREAD

**Issue by ismail** [languagetool-org/languagetool#1604]
This version has a bug fix for newer Java (9+) versions which fixes the loading of libxgboost.so: https://github.com/dmlc/xgboost/pull/4351

Without this fix LanguageTool reports the following at startup:

```
SEVERE: usr_paths                                                                                                                                                                  [1453/2851]
May 31, 2019 8:50:14 AM ml.dmlc.xgboost4j.java.XGBoostJNI <clinit>                             
SEVERE: Failed to load native library                                                          
java.io.IOException: Failed to get field handle to set library path                            
        at ml.dmlc.xgboost4j.java.NativeLibLoader.addNativeDir(NativeLibLoader.java:185)                                                                                                      
        at ml.dmlc.xgboost4j.java.NativeLibLoader.smartLoad(NativeLibLoader.java:146)                                                                                                         
        at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:40)                                                                                                        
        at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)                                                                                                                     
        at ml.dmlc.xgboost4j.java.Booster.init(Booster.java:526)                                                                                                                              
        at ml.dmlc.xgboost4j.java.Booster.<init>(Booster.java:48)                                                                                                                             
        at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:86)                                                                                                                          
        at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:57)                                                                                                                          
        at org.languagetool.rules.spelling.suggestions.XGBoostSuggestionsOrderer$1.create(XGBoostSuggestionsOrderer.java:61)                                                                  
        at org.languagetool.rules.spelling.suggestions.XGBoostSuggestionsOrderer$1.create(XGBoostSuggestionsOrderer.java:54)                                                                  
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:60)                                                                             
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1041)                                                                                      
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:342)                                                                                 
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:265)                                                                                 
        at org.languagetool.rules.spelling.suggestions.XGBoostSuggestionsOrderer.<init>(XGBoostSuggestionsOrderer.java:117)                                                                   
        at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.<init>(MorfologikSpellerRule.java:91)                                                                             
        at org.languagetool.rules.en.AbstractEnglishSpellerRule.<init>(AbstractEnglishSpellerRule.java:85)                                                                                    
        at org.languagetool.rules.en.MorfologikAmericanSpellerRule.<init>(MorfologikAmericanSpellerRule.java:63)                                                                              
        at org.languagetool.language.AmericanEnglish.getRelevantLanguageModelCapableRules(AmericanEnglish.java:62)                                                                            
        at org.languagetool.JLanguageTool.updateOptionalLanguageModelRules(JLanguageTool.java:458)                                                                                            
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:283)                       
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:304)                       
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:86)                                                                                             
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:74)
        at org.languagetool.gui.LanguageToolSupport.reloadLanguageTool(LanguageToolSupport.java:255)
        at org.languagetool.gui.LanguageToolSupport.init(LanguageToolSupport.java:318)
        at org.languagetool.gui.LanguageToolSupport.<init>(LanguageToolSupport.java:109)
        at org.languagetool.gui.Main.createGUI(Main.java:465)
        at org.languagetool.gui.Main.access$1700(Main.java:144)
        at org.languagetool.gui.Main$7.run(Main.java:1198)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

WARN  o.l.r.s.s.XGBoostSuggestionsOrderer At the moment, your platform (Windows?) or architecture (32 bit?) is not supported by the official XGBoost maven package; ML-based suggestion reorde
ring is disabled.

```

**Comment by danielnaber** [comment]
Thanks, it has been updated

**Comment by fedup41** [comment]
I added #1760 and it seems related to this fix.
