### ISSUE TITLE
LanguageTool reports UnsatisfiedLinkError at startup

### ISSUE THREAD

**Issue by fedup41** [languagetool-org/languagetool#1760]
The attached stacktrace results in languagetools reporting: "At the moment, your platform (Windows?) or architecture (32 bit?) is not supported by the official XGBoost maven package; ML-based suggestion reordering is disabled."

```
stack_trace: "java.lang.UnsatisfiedLinkError: /dev/shm/libxgboost4j6275767362009909875.so: /dev/shm/libxgboost4j6275767362009909875.so: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load0(ClassLoader.java)
	at java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.lang.Runtime.load0(Runtime.java:767)
	at java.lang.System.load(System.java:1831)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:71)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:41)
	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
	at ml.dmlc.xgboost4j.java.Booster.init(Booster.java:685)
	at ml.dmlc.xgboost4j.java.Booster.<init>(Booster.java:51)
	at ml.dmlc.xgboost4j.java.Booster.loadModel(Booster.java:89)
	at ml.dmlc.xgboost4j.java.XGBoost.loadModel(XGBoost.java:57)
	at org.languagetool.rules.spelling.suggestions.XGBoostSuggestionsOrderer$1.create(XGBoostSuggestionsOrderer.java:61)
	at org.languagetool.rules.spelling.suggestions.XGBoostSuggestionsOrderer$1.create(XGBoostSuggestionsOrderer.java:54)
	at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1041)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:342)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:265)
	at org.languagetool.rules.spelling.suggestions.XGBoostSuggestionsOrderer.<init>(XGBoostSuggestionsOrderer.java:117)
	at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.<init>(MorfologikSpellerRule.java:98)
	at org.languagetool.rules.en.AbstractEnglishSpellerRule.<init>(AbstractEnglishSpellerRule.java:86)
```

```
            <dependency>
                <groupId>org.languagetool</groupId>
                <artifactId>language-en</artifactId>
                <version>4.6</version>
            </dependency>
```

which brings in 0.90 of xgboost4j.

**Comment by danielnaber** [comment]
So which platform are you on?

**Comment by fedup41** [comment]
I have run this as a docker container based on openjdk:v11 on a local machine and on GCP.  All of these are 64-bit machines.  GCP is an amd64.  I get the same results in all places.

**Comment by iamtekeste** [comment]
I seeing the same issue on my AWS LighSail instance with Ubuntu 18.04.1 LTS. 
I am using OpenJDK if that helps.

**Comment by iamtekeste** [comment]
For anyone else facing this issue, after some googling around I was able to get rid it by installing gcc. 

I followed these instructions found on
https://unix.stackexchange.com/questions/400529/how-can-i-resolve-this-libgomp1-dependency-issue

```sh
sudo apt-get install gcc-5 g++-5
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
```

**Comment by marci4** [comment]
Hello everyone, 
got the same error usin version 4.8:
`2019-12-29 21:12:15 +0100 ERROR org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'java.lang.UnsatisfiedLinkError: dumonts.hunspell.bindings.HunspellLibrary.Hunspell_create(JJ)J, detected: de-DE', sending HTTP code 500. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0, User agent param: webextension-firefox-ng, v: 3.0.2, Referrer: null, language: auto, h: 1, r: 4, time: 3303m: ALL_BUT_TEXTLEVEL_ONLY, iID: 45171:1577650310500, Stacktrace follows:java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dumonts.hunspell.bindings.HunspellLibrary.Hunspell_create(JJ)J, detected: de-DE
`

Java version:
`openjdk version "1.8.0_232"`

OS:
Centos 7.7.1908

**Comment by Mannshoch** [comment]
Have the same error
Is there a need for gcc and g++ ?
Shouldn't LanguageTool only have Java as requirement?

**Comment by danielnaber** [comment]
For the record, `UnsatisfiedLinkError` happens when you're using a 32-bit Java. Using a 64 bit OS isn't enough.

**Comment by Mannshoch** [comment]
Please made a better error message.

**Comment by danielnaber** [comment]
Closing, as `XGBoostSuggestionsOrderer` has been removed.
