### ISSUE TITLE
CLI: warning and exception on Windows (v4.6)

### ISSUE THREAD

**Issue by GegznaV** [languagetool-org/languagetool#1813]
I downloaded LanguageTool from `https://www.languagetool.org/download/LanguageTool-4.6.zip` and use its command-line interface on Windows. Consider this example:
```bash
java -jar LanguageTool-4.6/languagetool-commandline.jar --encoding utf-8 --language en-GB --json test_text.txt
```
The code above results in output that contains a warning (similar to #1497) and an exception.  
<details>
<summary><i>(details: the output)</i></summary>
```
Warning: At the moment, your platform (Windows) is not supported by the official XGBoost maven package; ML-based suggestion reordering is disabled.
Expected text language: English (GB)
Working on test_text.txt...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at org.languagetool.MultiThreadedJLanguageTool.analyzeSentences(MultiThreadedJLanguageTool.java:153)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:738)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:716)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:699)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:658)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:642)
        at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:106)
        at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:82)
        at org.languagetool.commandline.Main.runOnFile(Main.java:194)
        at org.languagetool.commandline.Main.main(Main.java:466)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at java.util.concurrent.ForkJoinTask.get(Unknown Source)
        at org.languagetool.MultiThreadedJLanguageTool.analyzeSentences(MultiThreadedJLanguageTool.java:146)
        ... 9 more
Caused by: java.lang.OutOfMemoryError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
        ... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at opennlp.tools.ml.model.AbstractModelReader.getParameters(AbstractModelReader.java:140)
        at opennlp.tools.ml.maxent.io.GISModelReader.constructModel(GISModelReader.java:78)
        at opennlp.tools.ml.model.GenericModelReader.constructModel(GenericModelReader.java:62)
        at opennlp.tools.ml.model.AbstractModelReader.getModel(AbstractModelReader.java:85)
        at opennlp.tools.util.model.GenericModelSerializer.create(GenericModelSerializer.java:32)
        at opennlp.tools.util.model.GenericModelSerializer.create(GenericModelSerializer.java:29)
        at opennlp.tools.util.model.BaseModel.finishLoadingArtifacts(BaseModel.java:309)
        at opennlp.tools.util.model.BaseModel.loadModel(BaseModel.java:239)
        at opennlp.tools.util.model.BaseModel.<init>(BaseModel.java:173)
        at opennlp.tools.postag.POSModel.<init>(POSModel.java:82)
        at org.languagetool.chunking.EnglishChunker.<init>(EnglishChunker.java:64)
        at org.languagetool.language.English.getChunker(English.java:136)
        at org.languagetool.JLanguageTool.getRawAnalyzedSentence(JLanguageTool.java:991)
        at org.languagetool.JLanguageTool.getAnalyzedSentence(JLanguageTool.java:966)
        at org.languagetool.MultiThreadedJLanguageTool$AnalyzeSentenceCallable.call(MultiThreadedJLanguageTool.java:208)
        at org.languagetool.MultiThreadedJLanguageTool$AnalyzeSentenceCallable.call(MultiThreadedJLanguageTool.java:199)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
</details>

<details>
<summary>The contents of test_text.txt</summary>

```
LanguageTool offers spell and grammar checking.
Just paste your text here and click the 'Check Text' button.
Click the colored phrases for details on potential errors.
or use this text too see an few of of the problems that LanguageTool can detecd.
What do you thinks of grammar checkers? Please not that they are not perfect.
Style issues get a blue marker: It's 5 P.M. in the afternoon.
The weather was nice on Thursday, 27 June 2017.

```
</details>

How can this error be prevented to get a correct JSON output on Windows?

**Comment by danielnaber** [comment]
`Caused by: java.lang.OutOfMemoryError` -> please try starting with more memory, e.g. `java -Xmx2500m ...`

**Comment by GegznaV** [comment]
Installing 64bit JAVA helped to prevent error (see [here](https://forum.languagetool.org/t/resolved-xgboost-warning-and-outofmemoryerror-when-checking-english-with-ngram/4539/2)).
But the warning still persists.
