### ISSUE TITLE
StringIndexOutOfBoundsException in Ukrainian

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1897]
Since a few days, we get quite some of these exceptions. I have removed the text for privacy reasons, but I couldn't reproduce the issue anyway with that text:

```
2019-09-01 12:08:37 +0000 An error has occurred: 'java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Ukrainian): '...', detected: uk-UA
        at org.languagetool.server.TextChecker.checkText(TextChecker.java:343)
        at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:114)
        at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:65)
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:154)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Ukrainian): '...'
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.languagetool.server.TextChecker.checkText(TextChecker.java:328)
        ... 12 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Ukrainian): '...'
        at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:817)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:753)
        at org.languagetool.server.TextChecker.getRuleMatches(TextChecker.java:508)
        at org.languagetool.server.TextChecker.access$000(TextChecker.java:55)
        at org.languagetool.server.TextChecker$1.call(TextChecker.java:319)
        at org.languagetool.server.TextChecker$1.call(TextChecker.java:312)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 3 more
Caused by: java.lang.RuntimeException: Could not check sentence (language: Ukrainian): '....'
        at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1354)
        at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1243)
        at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1206)
        at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:813)
        ... 9 more
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 1435, length 1304
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at org.languagetool.JLanguageTool.adjustRuleMatchPos(JLanguageTool.java:893)
        at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1318)
        ... 12 more
```

@arysin Any idea what might have caused this?

**Comment by arysin** [comment]
I am not familiar with adjustRuleMatchPos() method, but recently I've pushed some sentence tokenization improvements for sentences with '...'
I haven't seen any issues on my 100M word corpus though. It would be nice to see text that causes this.

**Comment by danielnaber** [comment]
@arysin Here's now an input to reproduce: `https://www.foo.com/foo https://youtube.com Зе` - could this be related to your recent changes?

**Comment by danielnaber** [comment]
Indeed 982807b1f49768062654a011ab338ef6189a2dab is the cause: 
```
        String replaceChar = String.valueOf((char)urlReplaceChar);
        urls.put(replaceChar, urlGroup);
```
This causes the URLs to be replaced all by the same url further down in the code. I will see if I can fix it or roll it back.

**Comment by arysin** [comment]
Thanks for finding the root cause Daniel! And apologies for delayed response.
I've added a test for tokenizing multiple urls in the sentence and pushed the fix.
