### ISSUE TITLE
LT crashes occasionaly with a concurrency error

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#1918]
Runnign several stand alone LT's for testing separate rules, It occasionally crashes with this error:

```
Working on /media/ruud/data1/LT-premium/testcorpus1M.txt...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError
        at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:175)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:753)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:729)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:712)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:671)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:655)
        at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:106)
        at org.languagetool.commandline.Main.handleLine(Main.java:284)
        at org.languagetool.commandline.Main.runOnFileLineByLine(Main.java:271)
        at org.languagetool.commandline.Main.main(Main.java:464)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:172)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        ... 10 more
Caused by: java.lang.NoClassDefFoundError: org/languagetool/rules/RuleMatch$LinePosition
        at org.languagetool.rules.RuleMatch.<init>(RuleMatch.java:48)
        at org.languagetool.rules.patterns.PatternRuleMatcher.createRuleMatch(PatternRuleMatcher.java:237)
        at org.languagetool.rules.patterns.PatternRuleMatcher.match(PatternRuleMatcher.java:159)
        at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:235)
        at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:845)
        at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1311)
        at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1243)
        at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1206)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by baarsrj** [comment]
It actually happens in the command line version; even when there is only one running (a long time).

**Comment by danielnaber** [comment]
Which command line version do you use, one you just compiled or the one downloaded from languagetool.org? If you just compiled it, you need to make sure nothing (other tests, mvn, IntelliJ, ...) work in that directory.

**Comment by baarsrj** [comment]
So I can not run 2 LT's in the same directory the same moment. Okay, I will stick to one. Slows down the process though.

**Comment by danielnaber** [comment]
You can run them, but you cannot run any compilation, as that will change files.

**Comment by danielnaber** [comment]
Closing, probably related to the developer setup and compilation while running code.
