### ISSUE TITLE
PlainEnglish category creation issue

### ISSUE THREAD

**Issue by TiagoSantos81** [languagetool-org/languagetool#1978]
@danielnaber At the moment it is impossible to create new Java categories. 
While trying to fit the new PlainEnglish java rule in the existing PLAIN_ENGLISH XML category, I had to create a new category in Categories.java. Although the Category was created and is in use, the rule is still grouped in the English Style category.
The working code looks like this:
`  public static final Categories PLAIN_ENGLISH = make("PLAIN_ENGLISH", "category_style");`
but it should look like this:
`  public static final Categories PLAIN_ENGLISH = make("PLAIN_ENGLISH", "category_plain_english");`
This is not possible since [what I believe to be] a closed-source module blocks new category creation, and while compiling this error warning is shown:
```
`[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.languagetool.rules.en.MorfologikCanadianSpellerRuleTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.739 s <<< FAILURE! - in org.languagetool.rules.en.MorfologikCanadianSpellerRuleTest
[ERROR] testMorfologikSpeller(org.languagetool.rules.en.MorfologikCanadianSpellerRuleTest)  Time elapsed: 0.688 s  <<< ERROR!
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key category_plain_english
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:558)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at org.languagetool.ResourceBundleWithFallback.handleGetObject(ResourceBundleWithFallback.java:40)
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:555)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at org.languagetool.rules.Categories.getCategory(Categories.java:79)
	at org.languagetool.rules.en.EnglishPlainEnglishRule.<init>(EnglishPlainEnglishRule.java:55)
	at org.languagetool.language.English.getRelevantRules(English.java:202)
	at org.languagetool.language.CanadianEnglish.getRelevantRules(CanadianEnglish.java:48)
	at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:395)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:281)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:310)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:221)
	at org.languagetool.rules.en.MorfologikCanadianSpellerRuleTest.testMorfologikSpeller(MorfologikCanadianSpellerRuleTest.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

[ERROR] testSuggestions(org.languagetoo`

```

**Comment by danielnaber** [comment]
I haven't test it, but `category_plain_english` is not in `MessageBundle.properties` and `MessageBundle_en.properties`, and that would be a problem.

**Comment by TiagoSantos81** [comment]
Ok... PropertyResourceBundle I assumed as 'Proprietary'. I will close this when I get to it.
