### ISSUE TITLE
[de][server] RuntimeException: Could not activate rules

### ISSUE THREAD

**Issue by black-snow** [languagetool-org/languagetool#2121]
I need help once again.

I checked out v4.7 and at the same time built a new dictionary for my custom German derivate. So I don't know if I messed things up with the dictionary or if any change in 4.7 is causing trouble.

The server fires up just fine but when I query it:

> An error has occurred: 'java.lang.RuntimeException: Could not activate rules, detected: da-DK', sending HTTP code 400. Access from 192.168.1.1, HTTP user agent: insomnia/7.0.0, User agent param: null, Referrer: null, language: de-DE, h: 1, r: 2, time: 854, text length: 8, m: ALL, Stacktrace follows:java.lang.RuntimeException: java.lang.RuntimeException: Could not activate rules, detected: da-DK

Full trace:
```
2019-11-05 11:16:36 +0000 An error has occurred: 'java.lang.RuntimeException: Could not activate rules, detected: da-DK', sending HTTP code 400. Access from 192.168.1.1, HTTP user agent: insomnia/7.0.0, User agent param: null, Referrer: null, language: de-DE, h: 1, r: 2, time: 854, text length: 8, m: ALL, Stacktrace follows:java.lang.RuntimeException: java.lang.RuntimeException: Could not activate rules, detected: da-DK
        at org.languagetool.server.TextChecker.checkText(TextChecker.java:343)
        at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:125)
        at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:68)
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:154)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not activate rules
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.languagetool.server.TextChecker.checkText(TextChecker.java:326)
        ... 12 more
Caused by: java.lang.RuntimeException: Could not activate rules
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:291)
        at org.languagetool.server.Pipeline.<init>(Pipeline.java:82)
        at org.languagetool.server.PipelinePool.createPipeline(PipelinePool.java:191)
        at org.languagetool.server.PipelinePool.getPipeline(PipelinePool.java:171)
        at org.languagetool.server.TextChecker.getRuleMatches(TextChecker.java:507)
        at org.languagetool.server.TextChecker.access$000(TextChecker.java:55)
        at org.languagetool.server.TextChecker$1.call(TextChecker.java:319)
        at org.languagetool.server.TextChecker$1.call(TextChecker.java:312)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: java.lang.RuntimeException: Could not load language model capable rules.
        at org.languagetool.JLanguageTool.updateOptionalLanguageModelRules(JLanguageTool.java:470)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:289)
        ... 11 more
Caused by: java.lang.IllegalArgumentException: Dictionary must have at least the root node.
        at morfologik.speller.Speller.<init>(Speller.java:127)
        at org.languagetool.rules.spelling.morfologik.MorfologikSpeller.<init>(MorfologikSpeller.java:88)
        at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.getPlainTextDictSpellerOrNull(MorfologikMultiSpeller.java:184)
        at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.<init>(MorfologikMultiSpeller.java:142)
        at org.languagetool.rules.de.GermanSpellerRule.getSpeller(GermanSpellerRule.java:867)
        at org.languagetool.rules.de.GermanSpellerRule.<init>(GermanSpellerRule.java:742)
        at org.languagetool.language.GermanyGerman.getRelevantLanguageModelCapableRules(GermanyGerman.java:48)
        at org.languagetool.JLanguageTool.updateOptionalLanguageModelRules(JLanguageTool.java:464)
        ... 12 more
```

This happens for any language I request.

Steps I did:

```bash
mvn clean
./build.sh languagetool-server package -DskipTests
./languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/create_dict.sh de AD
```

Repeated building the server and the dict a couple times. The only issue I encounter while building is that `create_dict.sh` is missing `org.languagetool.tools.SpellDictionaryBuilder` (and others) after a `mvn clean` and even after `./build.sh languagetool-server package`. I circumvented this by running `mvn package` top-level, skipping the German module for it fails the tests with the same error `Runtime Could not activate rules`.

```
[INFO] Running org.languagetool.rules.de.GermanFillerWordsRuleTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.076 s <<< FAILURE! - in org.languagetool.rules.de.GermanFillerWordsRuleTest
[ERROR] testRule(org.languagetool.rules.de.GermanFillerWordsRuleTest)  Time elapsed: 0.076 s  <<< ERROR!
java.lang.RuntimeException: Could not activate rules
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:291)
        ...
Caused by: java.lang.RuntimeException: Could not load language model capable rules.
        at org.languagetool.JLanguageTool.updateOptionalLanguageModelRules(JLanguageTool.java:470)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:289)
        ... 28 more
Caused by: java.lang.IllegalArgumentException: Dictionary must have at least the root node.
        at morfologik.speller.Speller.<init>(Speller.java:127)
        ...
```

So something seems to be wrong with my dictionary but I've built it without errors.
Comparing `de_AT.dict` and `de_CH.dict` I can see they both start with:
```
5c66 7361 c600 0720 0078 6ab6 792d bca4
7677 7a70 646b 6663 626d c367 686f 756c
2b74 6169 6e72 7365 405e
```
and my `de_AD.dict` differs:
```
5c66 7361 c600 071b ...
```

Any guess what I might be missing?

**Comment by black-snow** [comment]
This seems to happen when I truncate `spelling.txt`. At least the tests seem to depend on some specific words in `spelling.txt`. Will try to remove the corresponding lines from the tests and try again.

**Comment by black-snow** [comment]
Checked out a clean 4.7 and applied my changes step by step and got a working version again. Will close this for now.
