### ISSUE TITLE
update hunspell to 1.7

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2151]
Test from a local branch with hunspell 1.7:

org.languagetool.rules.patterns.PerformanceTest with 20 runs.
All values in milliseconds, average of three runs:

new hunspell (local branch):
de-DE de.txt: 31
en-US en-big.txt: 42
pt-PT pt-error.txt: 355

old hunspell (current LT master, hunspell 1.3(?)):
de-DE de.txt: 31
en-US en-big.txt: 42
pt-PT pt-error.txt: 1050

**Comment by danielnaber** [comment]
Done by https://github.com/languagetool-org/languagetool/commit/442c9e891b6604fbd3fe82f2035d56a788b4dc7a

**Comment by danielnaber** [comment]
Doesn't build on Travis:

```
[ERROR] testImmunizedFrenchWord(org.languagetool.rules.spelling.hunspell.HunspellRuleTest)  Time elapsed: 0.368 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: dumonts.hunspell.bindings.HunspellLibrary.Hunspell_create(JJ)J
	at dumonts.hunspell.bindings.HunspellLibrary.Hunspell_create(Native Method)
	at dumonts.hunspell.bindings.HunspellLibrary.Hunspell_create(HunspellLibrary.java:25)
	at org.languagetool.rules.spelling.hunspell.Hunspell.<init>(Hunspell.java:46)
	at org.languagetool.rules.spelling.hunspell.Hunspell.getInstance(Hunspell.java:59)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.init(HunspellRule.java:377)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.match(HunspellRule.java:142)
```

**Comment by danielnaber** [comment]
System Properties on travis:
[props.txt](https://github.com/languagetool-org/languagetool/files/3851576/props.txt)
