### ISSUE TITLE
Failed to use 4.8 version

### ISSUE THREAD

**Issue by maxiplay** [languagetool-org/languagetool#2264]
Hello,

I just changed the Language tool version from 4.7 to 4.8.

Here what I have when try to launch spellcheck : 

        at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1245) ~[languagetool-core-4.8.jar!/:na]
        at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1208) ~[languagetool-core-4.8.jar!/:na]
        at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:815) ~[languagetool-core-4.8.jar!/:na]
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:755) ~[languagetool-core-4.8.jar!/:na]
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:731) ~[languagetool-core-4.8.jar!/:na]
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:714) ~[languagetool-core-4.8.jar!/:na]
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:690) ~[languagetool-core-4.8.jar!/:na]
        at com.writecontrol.spellcheck.service.LanguageToolService.check(LanguageToolService.java:57) ~[classes!/:0.0.1-SNAPSHOT]
        at com.writecontrol.spellcheck.controller.SpellcheckController.launchSpellcheck(SpellcheckController.java:42) ~[classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) ~[spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

I run Language tool in a docker container :

FROM java:8u91
VOLUME /tmp
ADD spellcheck-0.0.1-SNAPSHOT.war app.jar
RUN bash -c 'touch /app.jar'

The hosting OS is :

Linux instance-1 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

Here What is logged also before Exception :

```
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so : /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/BridJExtractedLibraries3152546208511200855/libhunspell.so)
2019-12-30 10:37:30.113 ERROR 6 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: dumonts.hunspell.bindings.HunspellLibrary.Hunspell_create(JJ)J] with root cause
```

**Comment by maxiplay** [comment]
I suppose it is relative to the hunspell update ?

**Comment by danielnaber** [comment]
> I suppose it is relative to the hunspell update ?

Probably. Can you install GLIBCXX_3.4.21?

**Comment by maxiplay** [comment]
I updated the FROM image to openjdk:8u232-stretch and it works perfectly
