### ISSUE TITLE
why is languagetool-commandline.jar trying to read from stdin

### ISSUE THREAD

**Issue by Konfekt** [languagetool-org/languagetool#2323]
This is a question originally asked by @skywind3000 in https://github.com/skywind3000/asyncrun.vim/issues/170#issuecomment-573388936_ :

When calling `java -jar java -jar %USERPROFILE%/LanguageTool/languagetool-commandline.jar --autoDetect %USERPROFILE%/text.txt` on the command line in Windows 10 64 bit, then it emits the message
```
Working on STDIN...
```
whereas closing `stdin` gives the error
```
Exception in thread "main" java.io.IOException: Stream Closed
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at org.languagetool.tools.StringTools.readerToString(StringTools.java:255)
	at org.languagetool.commandline.Main.getFilteredText(Main.java:348)
	at org.languagetool.commandline.Main.runOnFile(Main.java:174)
	at org.languagetool.commandline.Main.main(Main.java:466)
```
Why does LanguageTool work on stdin if it is reading a file, say `%USERPROFILE%/file.text`

**Comment by danielnaber** [comment]
I cannot reproduce this on Linux with LT 4.8. `Working on STDIN...` is only printed when the filename equals `-`, so I guess the command you've given is not exactly the one that's actually running?

**Comment by Konfekt** [comment]
Thank you; perhaps it is only a matter of the Vim-plugin referred to above that the command is passed to. Let me close for the meanwhile and check back.
