### ISSUE TITLE
languagetool throws error, when adding Hunspell dictionary with hpyhenated language shortcut

### ISSUE THREAD

**Issue by marcmittag** [languagetool-org/languagetool#2402]
Hi there,
based on input from Daniel I added additional hunspell dictionaries to languagetool as documented here:
https://confluence.translate5.net/display/TIU/Activate+additional+languages+for+spell+checking
This enables users to use Hunspell dictionaries for spellchecking with languagetool, that languagetool itself does not support by default.
In short: you have to add something like

lang-sr=Serbian(Latin)
lang-sr-dictPath=../hunspell-dictionaries-for-languagetool/sr/sr-Latn.dic

to the server.properties file of languageTool.

This works well as long as the language-Shortcut does not contain hyphens.
If you use country-specific shortcuts like "tr-TR" or shortcuts that define an alphabeth like "sr-Cyrl" languagetool throws an error.

So this does not work in the server.properties and leads to an error, when languagetool-server is queried for checking a sentence for that language:

lang-sr-Cyrl=Serbian(Cyril)
lang-sr-Cyrl-dictPath=../hunspell-dictionaries-for-languagetool/sr/sr.dic

The error thrown looks like this - you can see, that languageTool lists "sr-Cyrl" in the supported languages but says at the same time, that it is not supported:

2020-01-31 19:16:28 +0100 ERROR org.languagetool.server.LanguageToolHttpHandler An error has occurred: ''sr-Cyrl' is not a language code known to LanguageTool. Supported language codes are: af, ar, ast-ES, be, be-BY, bn, bo, br-FR, bs, ca, ca-ES, ca-ES-valencia, cs, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, et, fa, fr, gl-ES, gu, he, hi, hr, hu, id, is, it, ja-JP, km-KH, ku, lt, lv, nb, nl, nn, no, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sq, sr, sr-Cyrl, sv, sw, ta-IN, te, th, tl-PH, tr, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See http://wiki.languagetool.org/java-api for details.', sending HTTP code 400. Access from 127.0.0.1, HTTP user agent: Zend_Http_Client, User agent param: null, Referrer: null, language: sr-Cyrl, h: 1, r: 24, time: 1text length: 5, m: ALL, Stacktrace follows:java.lang.IllegalArgumentException: 'sr-Cyrl' is not a language code known to LanguageTool. Supported language codes are: af, ar, ast-ES, be, be-BY, bn, bo, br-FR, bs, ca, ca-ES, ca-ES-valencia, cs, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, et, fa, fr, gl-ES, gu, he, hi, hr, hu, id, is, it, ja-JP, km-KH, ku, lt, lv, nb, nl, nn, no, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sq, sr, sr-Cyrl, sv, sw, ta-IN, te, th, tl-PH, tr, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See http://wiki.languagetool.org/java-api for details.
	at org.languagetool.Languages.getLanguageForShortCode(Languages.java:193)
	at org.languagetool.Languages.getLanguageForShortCode(Languages.java:170)
	at org.languagetool.server.V2TextChecker.getLanguage(V2TextChecker.java:111)
	at org.languagetool.server.TextChecker.checkText(TextChecker.java:231)
	at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:141)
	at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:71)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:170)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Could that be fixed somehow?

best
Marc

**Comment by danielnaber** [comment]
I've committed a potential fix, could you try again?

**Comment by marcmittag** [comment]
No error anymore with the snapshot-build from yesterday, but also not working (no spell-check at all).
Maybe this is an issue on our side. We will check this the next 2 days.
I'll keep you posted.
best
Marc
