### ISSUE TITLE
Runtime exceptions building Office extension

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#241]
These exceptions appear building the Languagetool-office extension. But the build completes successfully. 

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/carrotsearch/hppc/ArraySizingStrategy
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:152)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:487)
	at org.languagetool.openoffice.Main.doGrammarCheckingInternal(Main.java:316)
	at org.languagetool.openoffice.Main.doProofreading(Main.java:253)
	at org.languagetool.openoffice.MainTest.testVariants(MainTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/carrotsearch/hppc/ArraySizingStrategy
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:149)
	... 24 more
Caused by: java.lang.NoClassDefFoundError: com/carrotsearch/hppc/ArraySizingStrategy
	at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.getDictionary(MorfologikMultiSpeller.java:98)
	at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.getPlainTextDictOrNull(MorfologikMultiSpeller.java:76)
	at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.<init>(MorfologikMultiSpeller.java:53)
	at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.match(MorfologikSpellerRule.java:96)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:572)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:917)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:870)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: com.carrotsearch.hppc.ArraySizingStrategy
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 11 more
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/carrotsearch/hppc/ArraySizingStrategy
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:152)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:487)

**Comment by danielnaber** [comment]
How exactly do you build, by changing to the `languagetool-office-extension` directory and calling `mvn package`? Maven isn't good at that, please either run `mvn install` once from the top LT directory, or just always build from the top-directory (e.g. with the `build.sh` helper script).

**Comment by jaumeortola** [comment]
That is exaclyt what I do: "mvn install", "mvn clean install"... from the top LT directory.
