### ISSUE TITLE
LibreOffice/OO: crash with Catalan

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#242]
The problem seems to be that `MorfologikCatalanSpellerRule` returns `true` in `useInOffice()`, but at the same time we exclude all spelling-related files in `assembly/oxt.xml`, so `spelling.txt` cannot be loaded. @jaumeortola I forgot about the reason to turn on the rule even though it's a spelling rule?

	java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not check sentence: 'Trenta-dos home. '
		at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:152)
		at org.languagetool.JLanguageTool.check(JLanguageTool.java:487)
		at org.languagetool.openoffice.Main.doGrammarCheckingInternal(Main.java:318)
		at org.languagetool.openoffice.Main.doProofreading(Main.java:255)
	Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not check sentence: 'Trenta-dos home. '
		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
		at java.util.concurrent.FutureTask.get(FutureTask.java:192)
		at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:149)
		... 3 more
	Caused by: java.lang.RuntimeException: Could not check sentence: 'Trenta-dos home. '
		at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:940)
		at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:870)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.lang.RuntimeException: Could not find ignore spell file in path: ca/hunspell/spelling.txt
		at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.match(MorfologikSpellerRule.java:100)
		at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:572)
		at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:917)
		... 5 more

**Comment by jaumeortola** [comment]
MorfologikCatalanSpellerRule is used in the Office extension because it's better than the Hunspell speller (the dictionary is better mantained, etc.). The user needs to manually disable the Hunspell speller in LibreOffice/OO. By the way, the dictionary used for spelling is the tagger dictionary.

**Comment by jaumeortola** [comment]
I have moved /ca/hunspell/spelling.txt to /ca/spelling.txt, which makes sense because Hunspell checkspelling is not used in Catalan in any way. Likewise the speller and tagger dictionary is in /ca/catalan.dict.
