### ISSUE TITLE
Concurrent modification exception in synthesizer

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#2959]
It happens only sometimes. My impression is that it is related to POS tags that include the character `+`, which has a special use in regular expressions. For example, in this sentence: `compartilos[compartir/VMM02V0+PP3MPA00]`. Obviously, it would be better not to use this symbol in POS tags. I can use some other character when the dictionary is updated. 

```
Caused by: java.lang.RuntimeException: Error analyzing sentence: '<S> miedo[miedo/NCMS000] de[de/SPS00] compartilos[compartir/VMM02V0+PP3MPA00,</S>]<P/> ' with rule VOSEO[1]
	at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:227)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:964)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1465)
	... 7 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.languagetool.synthesis.BaseSynthesizer.synthesize(BaseSynthesizer.java:193)
	at org.languagetool.rules.patterns.MatchState.toFinalString(MatchState.java:257)
	at org.languagetool.rules.patterns.PatternRuleMatcher.concatMatches(PatternRuleMatcher.java:484)
	at org.languagetool.rules.patterns.PatternRuleMatcher.formatMatches(PatternRuleMatcher.java:354)
	at org.languagetool.rules.patterns.PatternRuleMatcher.createRuleMatch(PatternRuleMatcher.java:195)
	at org.languagetool.rules.patterns.PatternRuleMatcher.match(PatternRuleMatcher.java:162)
	at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:223)
	... 9 more
```

**Comment by danielnaber** [comment]
The affected line is `for (String tag : possibleTags) {`- could it be this happens only on LT startup, or at least when that language is used for the first time after LT has started?

**Comment by jaumeortola** [comment]
> could it be this happens only on LT startup, or at least when that language is used for the first time after LT has started?

Yes, it is possible. It happens making tests on the command line: `java -jar languagetool-commandline.jar ...`
