### ISSUE TITLE
Error using  languagetool-wikipedia.jar

### ISSUE THREAD

**Issue by reisenmachtfreude** [languagetool-org/languagetool#300]
I obtain some errors during the wiki command line check

```bash 
java -jar languagetool-wikipedia.jar wiki-check https://de.wikipedia.org/wiki/Einh%C3%BCllenboot
```
Error message:
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Exception in thread "main" org.languagetool.dev.wikipedia.PageNotFoundException: No content found at 'https://de.wikipedia.org/wiki/Einh%C3%BCllenboot'
	at org.languagetool.dev.wikipedia.WikipediaQuickCheck.checkPage(WikipediaQuickCheck.java:108)
	at org.languagetool.dev.wikipedia.WikipediaQuickCheck.main(WikipediaQuickCheck.java:246)
	at org.languagetool.dev.wikipedia.Main.main(Main.java:51)

Same error if I want to check a random German page:
```bash
java -jar languagetool-wikipedia.jar wiki-check https://de.wikipedia.org/wiki/Spezial:Zuf%C3%A4llige_Seite
```
Error message:
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Exception in thread "main" org.languagetool.dev.wikipedia.PageNotFoundException: No content found at 'https://de.wikipedia.org/wiki/Spezial:Zuf%C3%A4llige_Seite'
	at org.languagetool.dev.wikipedia.WikipediaQuickCheck.checkPage(WikipediaQuickCheck.java:108)
	at org.languagetool.dev.wikipedia.WikipediaQuickCheck.main(WikipediaQuickCheck.java:246)
	at org.languagetool.dev.wikipedia.Main.main(Main.java:51)

**Comment by danielnaber** [comment]
Simply use `Einhüllenboot` instead of `Einh%C3%BCllenboot`. The random page is a special case, it's not really a page but some kind of redirect, so it won't work.

**Comment by reisenmachtfreude** [comment]
If the URL'https://de.wikipedia.org/wiki/Einh%C3%BCllenboot' is not allowed line 244 in the file WikipeidaQuickCheck.java  should be removed, because this shows an example URL which contains  URL encoded "Umlaute" also:
    final String urlString = "https://secure.wikimedia.org/wikipedia/de/wiki/G%C3%BCtersloh";

**Comment by danielnaber** [comment]
You're right, I've fixed the example.
