### ISSUE TITLE
Investigate Dalvik compatibility (Android)

### ISSUE THREAD

**Issue by JakubAdamWieczorek** [languagetool-org/languagetool#330]
As you may or may not be aware, LanguageTool does not currently run on Dalvik – specifically, but likely not exclusively, due to the VM's [poor support for XML schemas](https://code.google.com/p/android/issues/detail?id=7395).

Here's a stack trace I get on instantiating a JLanguageTool object on Dalvik:

```
Caused by: java.lang.IllegalArgumentException: http://www.w3.org/2001/XMLSchema
     at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:192)
     at net.sourceforge.segment.util.Util.getSchema(Util.java:265)
     at net.sourceforge.segment.util.Util.getSchema(Util.java:247)
     at net.sourceforge.segment.srx.io.Srx2SaxParser.<init>(Srx2SaxParser.java:181)
     at org.languagetool.tokenizers.SrxTools.createSrxDocument(SrxTools.java:51)
     at org.languagetool.tokenizers.LocalSRXSentenceTokenizer.<init>(LocalSRXSentenceTokenizer.java:46)
     at org.languagetool.tokenizers.SimpleSentenceTokenizer.<init>(SimpleSentenceTokenizer.java:37)
     at org.languagetool.Language.<clinit>(Language.java:63)
```

Let me know if you need any more information.

**Comment by danielnaber** [comment]
What happens if you remove the schema reference from the `grammar.xml` files? I don't think it's needed at runtime.

**Comment by JakubAdamWieczorek** [comment]
@danielnaber Sorry, I'm a student with what almost amounts to a negative time budget, so I'm afraid I can't actually test your solution. It does sound promising, though. I'm happy to try out a .jar, should you be able to provide one with the fix included… :)

**Comment by JakubAdamWieczorek** [comment]
@danielnaber I have looked into this and the problem is independent of whether or not the files themselves contain schema declarations. It's the `net.sourceforge.segment` library that uses schema-related methods which aren entirely unsupported on Dalvik – see the upper frames of the trace.

**Comment by danielnaber** [comment]
Then this should probably be reported to the library https://github.com/loomchild/segment

**Comment by JakubAdamWieczorek** [comment]
@danielnaber Right. I filed https://github.com/icenlp/segment/issues/1.

**Comment by JakubAdamWieczorek** [comment]
@danielnaber Why close this? LanguageTool still does not run on Dalvik, regardless od whether the reason is contained in a 3rd-party library, or not.

**Comment by danielnaber** [comment]
If the reason is in a third-party component, what can we do? If the component gets an update that fixes that, we'll update anyway, we don't need an issue for that.

**Comment by JakubAdamWieczorek** [comment]
We don't need to act on it whilst keeping it open to track the underlying issue.

**Comment by danielnaber** [comment]
I think you filed your issue under an outdated version (no activity for 4 years), the up-to-date repo seems to be this: https://github.com/loomchild/segment

**Comment by JakubAdamWieczorek** [comment]
Ah, clearly. Thanks. [Here](https://github.com/loomchild/segment/issues/7)'s the right one.

**Comment by JakubAdamWieczorek** [comment]
OK, there are some changes I've had to make to get this to work –

**Comment by JakubAdamWieczorek** [comment]
Things are looking promising. There are various changes I've had to make to get the library to work on Dalvik – I'll clean them up. I'm not quite there yet – am currently stuck at a rather mysterious stack trace.

```java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence: 'Napewno to zrobię'
     (...)
  Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence: 'Napewno to zrobię'
     at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:549)
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:498)
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:449)
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:445)
     (...)
  Caused by: java.lang.RuntimeException: Could not check sentence: 'Napewno to zrobię'
     at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:941)
     at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:871)
     at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:545)
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:498) 
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:449) 
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:445) 
     (...)
  Caused by: java.nio.BufferUnderflowException
     at java.nio.CharArrayBuffer.get(CharArrayBuffer.java:100)
     at morfologik.speller.Speller.findRepl(Speller.java:476)
     at morfologik.speller.Speller.findRepl(Speller.java:526)
     at morfologik.speller.Speller.findReplacements(Speller.java:434)
     at org.languagetool.rules.spelling.morfologik.MorfologikSpeller.getSuggestions(MorfologikSpeller.java:75)
     at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.getSuggestions(MorfologikMultiSpeller.java:129)
     at org.languagetool.rules.pl.MorfologikPolishSpellerRule.getRuleMatches(MorfologikPolishSpellerRule.java:126)
     at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.match(MorfologikSpellerRule.java:117)
     at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:583)
     at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:918)
     at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:871) 
     at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:545) 
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:498) 
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:449) 
     at org.languagetool.JLanguageTool.check(JLanguageTool.java:445) 
     (...)
```

In any case – please reopen the issue.

**Comment by danielnaber** [comment]
Have you made progress with this issue? If so, now there's still a chance to get your changes into the next LT release (planned for end of this month).

**Comment by danielnaber** [comment]
Also see https://github.com/Softcatala/LanguageToolAndroidService/ for how this could be useful to have an Android checker without the need to connect the remote service (also ping to @jordimas so he knows about this issue).

**Comment by danielnaber** [comment]
Closing, as there was no further feedback.
