### ISSUE TITLE
Tools.correctText causes a StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by eliac** [languagetool-org/languagetool#337]
With JLanguageTool - English 3.1 (Maven dependency: `org.languagetool:language-en:3.1`), the following code throws the following exception:

    Tools.correctText("I've have", new JLanguageTool(new BritishEnglish()));

    Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:868)
    	at java.lang.StringBuilder.substring(StringBuilder.java:72)
    	at org.languagetool.tools.Tools.correctTextFromMatches(Tools.java:241)
    	at org.languagetool.tools.Tools.correctText(Tools.java:219)

**Comment by danielnaber** [comment]
Thanks for the report, this has been fixed.
