### ISSUE TITLE
Add options to create a "must/should be" rule

### ISSUE THREAD

**Issue by thelittlefireman** [languagetool-org/languagetool#3384]
Hi,
in some language (and specially in French) it's hard to define a rule by his mistakes. I wonder if there is a way or if there could be a way to add the ability to create a "must/should be" rule. And then we could add exceptions to this rule. 
For example instead of declared a rule like "a singular should not be followed by a plural noun" we could define a rule like "a singular SHOULD ALWAYS BE followed by a singular noun". I try with the "negate" option but most of the time it doesn't work and the regexp parser is lost in nowhere...
Thanks :)

**Comment by jaumeortola** [comment]
I am not sure I understand your first point. You can use `<exception>` or `<antipattern>`. 
```
<pattern>
   <token postag="singular"/>
   <token><exception postag="singular"/>
</pattern>
```

```
<antipattern>
    <token postag="singular"/>
    <token postag="singular"/>
</antipattern>
<pattern>
   <token postag="singular"/>
   <token/>
</pattern>
```

As for the second point, something can be achieved using `<phrase>`. For example:
```
 <phrases>
    <phrase id="NONIMAL_GROUP_SING1">
          <token postag="determiner singular"/>
          <token postag="noun singular"/>
    </phrase>
    <phrase id="NONIMAL_GROUP_SING2">
          <token postag="determiner singular"/>
          <token postag="noun singular"/>
          <token postag="preposition"/>
          <token postag="determiner" min="0"/>
          <token postag="noun"/>
    </phrase>
    ...
    <phrase id="ALL_NONIMAL_GROUPS_SING">
      <includephrases>
          <phraseref idref="NONIMAL_GROUP_SING1"/>
          <phraseref idref="NONIMAL_GROUP_SING2"/>
          ...
      </includephrases>
    </phrase>
  </phrases>
```
And then the rule: 
```
<pattern>
    <phraseref idref="ALL_NONIMAL_GROUPS_SING"/>
    <token postag="verb plural">
</pattern>
```
There is little development with `<phrase>` (See the Spanish grammar.xml for a simple example). So, I don't know if it will work. 

Remember that rules for subject/verb agreement are difficult, and they will probably need many exceptions.

**Comment by thelittlefireman** [comment]
Thanks :) I will test all of that. That's seem to be what I'm looking for.

**Comment by MikeUnwalla** [comment]
@jaumeortola , is `<phrase>` for `grammar.xml` only or should I be able to use it in` disambiguation.xml`?

**Comment by jaumeortola** [comment]
> @jaumeortola , is `<phrase>` for `grammar.xml` only or should I be able to use it in` disambiguation.xml`?

I never used `<phrase>` in disambiguation.xml. But I have tried now and it works as expected.

**Comment by MikeUnwalla** [comment]
@jaumeortola , thanks.

I asked because I get a testrules error message.

I copied the English phrases from grammar.xml and put them into en/disambiguation.xml after the unification rules.

Testrules gives this error:
```

Skipped 0 rules for variant language to avoid checking rules more than once
3930 rules tested.
Exception in thread "main" org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule A_CD_NNS[1] in file /org/languagetool/rules/en/grammar.xml: After a forty-five minutes or so of jokes and music, the procession then moves out to the lawn in front of Hartley, Wallach and John Jay residence halls to entertain the residents there."
Errors expected: 1
Errors found   : 0
Message: The article "\1" is not needed here.
Analyzed token readings: [/SENT_START*] After[after/CC*,after/IN*,after/RB*,B-PP]  [ /null*] a[a/DT,B-NP-plural]  [ /null*] forty-five[forty-five/CD,I-NP-plural]  [ /null*] minutes[minute/NNS,minute/VBZ,I-NP-plural]  [ /null*] or[or/CC,or/JJ,I-NP-plural]  [ /null*] so[so/RB,so/CC,so/JJ,so/NN:U,E-NP-plural]  [ /null*] of[of/IN,B-PP]  [ /null*] jokes[joke/NNS,B-NP-plural]  [ /null*] and[and/CC,I-NP-plural]  [ /null*] music[music/NN:U,E-NP-plural] ,[,/,*,,/PCT*,O]  [ /null*] the[the/DT,B-NP-singular]  [ /null*] procession[procession/NN:UN,E-NP-singular]  [ /null*] then[then/JJ,then/NN,then/RB,B-ADVP]  [ /null*] moves[move/NNS,move/VBZ,B-VP]  [ /null*] out[out/IN,out/NN,out/RB,out/RP,out/UH,B-NP-singular|E-NP-singular]  [ /null*] to[to/IN,to/TO,B-PP]  [ /null*] the[the/DT,B-NP-singular]  [ /null*] lawn[lawn/NN:UN,E-NP-singular]  [ /null*] in[in/IN,B-PP]  [ /null*] front[front/NN:UN,B-NP-singular|E-NP-singular]  [ /null*] of[of/IN,B-PP]  [ /null*] Hartley[Hartley/NNP,B-NP-singular|E-NP-singular] ,[,/,*,,/PCT*,O]  [ /null*] Wallach[Wallach/NNP,B-NP-singular|E-NP-singular]  [ /null*] and[and/CC,O]  [ /null*] John[John/NNP,B-NP-plural]  [ /null*] Jay[Jay/NNP,I-NP-plural]  [ /null*] residence[residence/NN:UN,I-NP-plural]  [ /null*] halls[hall/NNS,E-NP-plural]  [ /null*] to[to/TO,B-VP]  [ /null*] entertain[entertain/VB,I-VP]  [ /null*] the[the/DT,B-NP-plural]  [ /null*] residents[resident/NNS,E-NP-plural]  [ /null*] there[there/RB,B-ADVP] .[./.*,./SENT_END*,./PCT*,O]
Matches: []
        at org.languagetool.rules.patterns.PatternRuleTest.testBadSentences(PatternRuleTest.java:396)
        at org.languagetool.rules.patterns.PatternRuleTest.testGrammarRulesFromXML(PatternRuleTest.java:318)
        at org.languagetool.rules.patterns.PatternRuleTest.runTestForLanguage(PatternRuleTest.java:169)
        at org.languagetool.rules.patterns.PatternRuleTest.runGrammarRulesFromXmlTestIgnoringLanguages(PatternRuleTest.java:152)
        at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:683)
Running disambiguator rule tests...
Running disambiguation tests for English...
*** WARNING: The English rule: REMOVE_JJ_FOR_OR[1], token [2], contains an empty string "" that is marked as regular expression.
*** WARNING: The English rule: REMOVE_JJ_FOR_OR[1], token [4], contains an empty string "" that is marked as regular expression.
*** WARNING: The English rule: REMOVE_JJ_FOR_OR[1], token [6], contains an empty string "" that is marked as regular expression.
*** WARNING: The English rule: REMOVE_JJ_FOR_OR[1], token [7], contains an empty string "" that is marked as regular expression.
Exception in thread "main" java.lang.AssertionError: Disambiguated sentence is equal to the non-disambiguated sentence for rule: REMOVE_JJ_FOR_OR. The sentence was: <S> Let[Let/NNP,let/NN,let/VB,let/VBD,let/VBN,let/VBP,B-VP]'['/null]s[s/POS] choose[choose/VB,choose/VBP,B-VP] A[a/DT,B-NP-singular] or[or/CC,or/JJ,or/NN:U,I-NP-singular] B[B/null].[./.,</S>]
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.testDisambiguationRulesFromXML(DisambiguationRuleTest.java:154)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.testDisambiguationRulesFromXML(DisambiguationRuleTest.java:79)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.main(DisambiguationRuleTest.java:234)
Running XML bitext pattern tests...
Bitext pattern tests successful.
Validating false-friends.xml...
Validation successfully finished.
```

Do any of the developers know why the error occurs?
