### ISSUE TITLE
Wont install on LibreOffice

### ISSUE THREAD

**Issue by philipzae** [languagetool-org/languagetool#367]
Tried adding it to LibreOffice 5.1, but got an error.

[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0
java stack trace:
java.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:793)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:52)
	at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:380)

**Comment by danielnaber** [comment]
You'll need to install Java 8 and configure it in LibreOffice at `Tools -> Options -> Advanced`. Your system is still using an older version of Java.

**Comment by philipzae** [comment]
Thanks for the reply and sorry for the invalid bug report.
