### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#4011]
I get this error in execution when using the current LanguageTool snapshot (5.2-SNAPSHOT) inside another Java application. Any hint about how to fix it? @danielnaber @donnerpeter 

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IncompatibleClassChangeError
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:191)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:933)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:887)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:874)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:864)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:846)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:803)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:787)
	at checkdocuments.checkdocuments$1.call(checkdocuments.java:302)
	at checkdocuments.checkdocuments$1.call(checkdocuments.java:214)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.IncompatibleClassChangeError
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:188)
	... 13 more
Caused by: java.lang.IncompatibleClassChangeError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	... 15 more
Caused by: java.lang.IncompatibleClassChangeError: Class com.google.common.base.Suppliers$SupplierOfInstance does not implement the requested interface java.util.function.Supplier
	at org.languagetool.rules.RuleMatch.getSuggestedReplacementObjects(RuleMatch.java:396)
	at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.getRuleMatches(MorfologikSpellerRule.java:439)
	at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.match(MorfologikSpellerRule.java:136)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:1249)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1797)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1718)
	at org.languagetool.MultiThreadedJLanguageTool.lambda$null$0(MultiThreadedJLanguageTool.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by danielnaber** [comment]
Could you run `mvn dependency:tree` and see which version of com.google.guava:guava you get?

**Comment by jaumeortola** [comment]
In LanguageTool: `com.google.guava:guava:jar:28.1-jre:compile`
In the other project: `com.google.guava:guava:jar:11.0.2:compile`

Adding this dependency the issue is fixed. Thank you.
