### ISSUE TITLE
Languagetool say ngram directory do not exist

### ISSUE THREAD

**Issue by Mannshoch** [languagetool-org/languagetool#4035]
It seems my languagetool setup has a problem finding the ngrams directory

languagetool.service
```
[Unit]
Description=Rechtschreib Prüfung - Languagetool
After=network.target

[Service]
ExecStart=/usr/bin/java -cp '/home/user/LanguageTool/languagetool-server.jar' org.languagetool.server.HTTPServer --config '/home/user/languagetool.cfg'
Restart=always
RestartSec=5
Type=simple
User=user
WorkingDirectory=/home/user/LanguageTool

[Install]
WantedBy=network.target
```
languagetool.cfg
```
port=8081
allow-origin='*'
languageModel='/home/user/ngrams'
word2vecDir='/home/user/word2vec'
```
bash
```
/home/user/ngrams$ ls -lah
insgesamt 16K
drwxrwxrwx 4 user user 4.0K Mär 31  2020 .
drwxrwxrwx 6 user user 4.0K Dez 17 10:15 ..
drwxr-xr-x 5 user user 4.0K Aug 19  2015 de
drwxr-xr-x 5 user user 4.0K Aug 22  2018 en
```
journalctl -ru languagetool
```
Dez 17 10:16:17 user-pc systemd[1]: Failed to start Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:17 user-pc systemd[1]: languagetool.service: Failed with result 'exit-code'.
Dez 17 10:16:17 user-pc systemd[1]: languagetool.service: Start request repeated too quickly.
Dez 17 10:16:17 user-pc systemd[1]: Stopped Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:17 user-pc systemd[1]: languagetool.service: Scheduled restart job, restart counter is at 5.
Dez 17 10:16:17 user-pc systemd[1]: languagetool.service: Failed with result 'exit-code'.
Dez 17 10:16:17 user-pc systemd[1]: languagetool.service: Main process exited, code=exited, status=1/FAILURE
Dez 17 10:16:17 user-pc java[16076]:         at org.languagetool.server.HTTPServer.main(HTTPServer.java:139)
Dez 17 10:16:17 user-pc java[16076]:         at org.languagetool.server.HTTPServerConfig.<init>(HTTPServerConfig.java:161)
Dez 17 10:16:17 user-pc java[16076]:         at org.languagetool.server.HTTPServerConfig.parseConfigFile(HTTPServerConfig.java:237)
Dez 17 10:16:17 user-pc java[16076]:         at org.languagetool.server.HTTPServerConfig.setLanguageModelDirectory(HTTPServerConfig.java:377)
Dez 17 10:16:17 user-pc java[16076]: Exception in thread "main" java.lang.RuntimeException: LanguageModel directory not found or is not a directory: '/home/user/ngrams'
Dez 17 10:16:17 user-pc systemd[1]: Started Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:17 user-pc systemd[1]: Stopped Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:17 user-pc systemd[1]: languagetool.service: Scheduled restart job, restart counter is at 4.
Dez 17 10:16:16 user-pc systemd[1]: languagetool.service: Failed with result 'exit-code'.
Dez 17 10:16:16 user-pc systemd[1]: languagetool.service: Main process exited, code=exited, status=1/FAILURE
Dez 17 10:16:16 user-pc java[16054]:         at org.languagetool.server.HTTPServer.main(HTTPServer.java:139)
Dez 17 10:16:16 user-pc java[16054]:         at org.languagetool.server.HTTPServerConfig.<init>(HTTPServerConfig.java:161)
Dez 17 10:16:16 user-pc java[16054]:         at org.languagetool.server.HTTPServerConfig.parseConfigFile(HTTPServerConfig.java:237)
Dez 17 10:16:16 user-pc java[16054]:         at org.languagetool.server.HTTPServerConfig.setLanguageModelDirectory(HTTPServerConfig.java:377)
Dez 17 10:16:16 user-pc java[16054]: Exception in thread "main" java.lang.RuntimeException: LanguageModel directory not found or is not a directory: '/home/user/ngrams'
Dez 17 10:16:16 user-pc systemd[1]: Started Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:16 user-pc systemd[1]: Stopped Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:16 user-pc systemd[1]: languagetool.service: Scheduled restart job, restart counter is at 3.
Dez 17 10:16:16 user-pc systemd[1]: languagetool.service: Failed with result 'exit-code'.
Dez 17 10:16:16 user-pc systemd[1]: languagetool.service: Main process exited, code=exited, status=1/FAILURE
Dez 17 10:16:16 user-pc java[16033]:         at org.languagetool.server.HTTPServer.main(HTTPServer.java:139)
Dez 17 10:16:16 user-pc java[16033]:         at org.languagetool.server.HTTPServerConfig.<init>(HTTPServerConfig.java:161)
Dez 17 10:16:16 user-pc java[16033]:         at org.languagetool.server.HTTPServerConfig.parseConfigFile(HTTPServerConfig.java:237)
Dez 17 10:16:16 user-pc java[16033]:         at org.languagetool.server.HTTPServerConfig.setLanguageModelDirectory(HTTPServerConfig.java:377)
Dez 17 10:16:16 user-pc java[16033]: Exception in thread "main" java.lang.RuntimeException: LanguageModel directory not found or is not a directory: '/home/user/ngrams'
Dez 17 10:16:16 user-pc systemd[1]: Started Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:16 user-pc systemd[1]: Stopped Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:16 user-pc systemd[1]: languagetool.service: Scheduled restart job, restart counter is at 2.
Dez 17 10:16:16 user-pc systemd[1]: languagetool.service: Failed with result 'exit-code'.
Dez 17 10:16:16 user-pc systemd[1]: languagetool.service: Main process exited, code=exited, status=1/FAILURE
Dez 17 10:16:16 user-pc java[16015]:         at org.languagetool.server.HTTPServer.main(HTTPServer.java:139)
Dez 17 10:16:16 user-pc java[16015]:         at org.languagetool.server.HTTPServerConfig.<init>(HTTPServerConfig.java:161)
Dez 17 10:16:16 user-pc java[16015]:         at org.languagetool.server.HTTPServerConfig.parseConfigFile(HTTPServerConfig.java:237)
Dez 17 10:16:16 user-pc java[16015]:         at org.languagetool.server.HTTPServerConfig.setLanguageModelDirectory(HTTPServerConfig.java:377)
Dez 17 10:16:16 user-pc java[16015]: Exception in thread "main" java.lang.RuntimeException: LanguageModel directory not found or is not a directory: '/home/user/ngrams'
Dez 17 10:16:16 user-pc systemd[1]: Started Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:16 user-pc systemd[1]: Stopped Rechtschreib Prüfung - Languagetool.
Dez 17 10:16:16 user-pc systemd[1]: languagetool.service: Scheduled restart job, restart counter is at 1.
Dez 17 10:16:15 user-pc systemd[1]: languagetool.service: Failed with result 'exit-code'.
Dez 17 10:16:15 user-pc systemd[1]: languagetool.service: Main process exited, code=exited, status=1/FAILURE
Dez 17 10:16:15 user-pc java[15984]:         at org.languagetool.server.HTTPServer.main(HTTPServer.java:139)
Dez 17 10:16:15 user-pc java[15984]:         at org.languagetool.server.HTTPServerConfig.<init>(HTTPServerConfig.java:161)
Dez 17 10:16:15 user-pc java[15984]:         at org.languagetool.server.HTTPServerConfig.parseConfigFile(HTTPServerConfig.java:237)
Dez 17 10:16:15 user-pc java[15984]:         at org.languagetool.server.HTTPServerConfig.setLanguageModelDirectory(HTTPServerConfig.java:377)
```

**Comment by danielnaber** [comment]
There must not be quotes around the values here: `languageModel='/home/user/ngrams'`

**Comment by Mannshoch** [comment]
Thanks that was helpfull.
But now I also have other Errors ( I also removed the quotes ther but that did not help)
It seems that the Key **port**, **allow-origin** and **word2vecDir** are not known.

```
port=8081
allow-origin=*
languageModel=/home/user/ngrams
word2vecDir=/home/user/word2vec
```

journalctl -ru languagetool
```
Dez 17 15:43:21 user-pc java[47525]: 2020-12-17 15:43:21 +0100 INFO  org.languagetool.server.DatabaseAccess Not setting up database access, dbDriver is not configured
Dez 17 15:43:21 user-pc java[47525]: Known keys: [abTest, abTestClients, abTestRollout, beolingusFile, blockedReferrers, cacheSize, cacheTTLSeconds, dbDriver, dbPassword, dbUrl, dbUsername, disabledRu>
Dez 17 15:43:21 user-pc java[47525]: Key 'word2vecDir' from configuration file '/home/user/languagetool.cfg' is unknown. Please check the key's spelling (case is signi>
Dez 17 15:43:21 user-pc java[47525]: ***** WARNING: ****
Dez 17 15:43:21 user-pc java[47525]: Known keys: [abTest, abTestClients, abTestRollout, beolingusFile, blockedReferrers, cacheSize, cacheTTLSeconds, dbDriver, dbPassword, dbUrl, dbUsername, disabledRu>
Dez 17 15:43:21 user-pc java[47525]: Key 'port' from configuration file '/home/user/languagetool.cfg' is unknown. Please check the key's spelling (case is significant).
Dez 17 15:43:21 user-pc java[47525]: ***** WARNING: ****
Dez 17 15:43:21 user-pc java[47525]: Known keys: [abTest, abTestClients, abTestRollout, beolingusFile, blockedReferrers, cacheSize, cacheTTLSeconds, dbDriver, dbPassword, dbUrl, dbUsername, disabledRu>
Dez 17 15:43:21 user-pc java[47525]: Key 'allow-origin' from configuration file '/home/user/languagetool.cfg' is unknown. Please check the key's spelling (case is sign>
Dez 17 15:43:21 user-pc java[47525]: ***** WARNING: ****
Dez 17 15:43:21 user-pc systemd[1]: Started Rechtschreib Prüfung - Languagetool.
```

**Comment by danielnaber** [comment]
Please check the output of `java -jar languagetool-server.jar`, it described what's a command-line parameter and what belongs into the properties file.

**Comment by Mannshoch** [comment]
OK thanks. 👍
I would vote for adding these two also to the properties.
