### ISSUE TITLE
support Java 15

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#4061]
Tests fail with Java 15 and runtime behavior will be different with Java 15.

See #4054

**Comment by danielnaber** [comment]
Update: Next problem after working around the regex issue:

```
[ERROR] testIndexerSearcherWithEnglish(org.languagetool.dev.index.IndexerSearcherTest)  Time elapsed: 0.526 s  <<< ERROR!
org.languagetool.dev.index.SearchTimeoutException: Search timeout of 5000ms reached for query +fieldLowercase:back +fieldLowercase:and +fieldLowercase:fourth
	at __randomizedtesting.SeedInfo.seed([84DEA6EE34B343D6:31D0B1D48A5EF3EA]:0)
	at org.languagetool.dev.index.Searcher.findRuleMatchesOnIndex(Searcher.java:171)
	at org.languagetool.dev.index.Searcher.findRuleMatchesOnIndex(Searcher.java:137)
	at org.languagetool.dev.index.IndexerSearcherTest.testIndexerSearcherWithEnglish(IndexerSearcherTest.java:198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1764)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:871)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:921)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:809)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:460)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:880)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:781)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:816)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:827)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Issue starts with JDK13, JDK12 is still okay.

**Comment by jaumeortola** [comment]
A user reports problems in LanguageTool+LibreOffice, with Java 15, checking text in Catalan. It seems that lower case words are tagged as if they were capitalized in a disambiguation rule that relies on `\p{Lu}` (ca/disambiguation.xml id="possible_nom_propi"). 
How can the issue be fixed? Adding `case_sensitive="yes"` to the rule (to all the rules...)?

**Comment by danielnaber** [comment]
A fix already exists for this locally, please wait a bit and I will apply it.

**Comment by danielnaber** [comment]
My plan is now to commit the change on Saturday, as there will be fewer changes in the nightly diff from Saturday to Sunday. The change shouldn't make a difference, but if it does, having changes from the patch and the regular changes from rule updates, it might get a bit messy.

**Comment by danielnaber** [comment]
This has now been committed, LT should work with Java 8 and Java 15 now.
