### ISSUE TITLE
maxOccurrences error

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4087]
Changes made between 2020-11-07 and 2020-12-19 cause errors when I try to use external rules (https://dev.languagetool.org/tips-and-tricks#adding-rules-to-an-external-file). I get error messages about maxOccurrences.

(Update: the problem occurs also I replace the default LT rules with the rules that are in my external file.)

I cannot give a specific date when the problem started because I cannot get old snapshots from https://internal1.languagetool.org/snapshots/.

I am not sure if the LT changes mean that I must change something in my rules or whether the LT changes did not take into account external rules. To what does maxOccurrences refer?

If I use a grammar file that has a small number of rules and the full set of disambiguation rules, I get this error message:

```
<snip>\lt52-snap-old> java -jar languagetool.jar
java.lang.RuntimeException: Problems with loading disambiguation file: en/disambiguation.xml
        at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.<init>(XmlRuleDisambiguator.java:53)
        at org.languagetool.tagging.en.EnglishHybridDisambiguator.<init>(EnglishHybridDisambiguator.java:43)
        at org.languagetool.language.English.createDefaultDisambiguator(English.java:133)
        at org.languagetool.Language.getDisambiguator(Language.java:328)
        at org.languagetool.JLanguageTool.getAnalyzedSentence(JLanguageTool.java:1406)
        at org.languagetool.JLanguageTool.analyzeSentences(JLanguageTool.java:1128)
        at org.languagetool.MultiThreadedJLanguageTool.analyzeSentences(MultiThreadedJLanguageTool.java:129)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:912)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:884)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:871)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:861)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:843)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:800)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:784)
        at org.languagetool.gui.LanguageToolSupport.checkText(LanguageToolSupport.java:753)
        at org.languagetool.gui.LanguageToolSupport.access$1700(LanguageToolSupport.java:57)
        at org.languagetool.gui.LanguageToolSupport$RunnableImpl.run(LanguageToolSupport.java:921)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: maxOccurrences should be between -1 and 127
        at org.languagetool.rules.patterns.PatternToken.setMaxOccurrence(PatternToken.java:407)
        at org.languagetool.rules.patterns.XMLRuleHandler.finalizeTokens(XMLRuleHandler.java:571)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleHandler.endElement(DisambiguationRuleHandler.java:352)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleLoader.getRules(DisambiguationRuleLoader.java:46)
        at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.loadPatternRules(XmlRuleDisambiguator.java:72)
        at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.<init>(XmlRuleDisambiguator.java:51)
        ... 23 more

<snip>\lt52-snap-old>
```

If I delete some disambiguation rules, LT opens without errors. (The rules won't work correctly, but that is not important for this test.)

If I use a grammar file that has the full set of grammar rules and the full set of disambiguation rules, I get this message:

```
<snip>\lt52-ste>java -jar languagetool.jar
java.lang.RuntimeException: java.lang.RuntimeException: Could not activate rules
        at org.languagetool.gui.LanguageToolSupport.reloadLanguageTool(LanguageToolSupport.java:262)
        at org.languagetool.gui.LanguageToolSupport.init(LanguageToolSupport.java:318)
        at org.languagetool.gui.LanguageToolSupport.<init>(LanguageToolSupport.java:109)
        at org.languagetool.gui.Main.createGUI(Main.java:468)
        at org.languagetool.gui.Main.access$1700(Main.java:144)
        at org.languagetool.gui.Main$7.run(Main.java:1201)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Could not activate rules
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:328)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:287)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:347)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:86)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:74)
        at org.languagetool.gui.LanguageToolSupport.reloadLanguageTool(LanguageToolSupport.java:255)
        ... 19 more
Caused by: java.io.IOException: Cannot load or parse input stream of '/org/languagetool/rules/en/grammar.xml'
        at org.languagetool.rules.patterns.PatternRuleLoader.getRules(PatternRuleLoader.java:76)
        at org.languagetool.Language.getPatternRules(Language.java:598)
        at org.languagetool.JLanguageTool.activateDefaultPatternRules(JLanguageTool.java:634)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:321)
        ... 24 more
Caused by: java.lang.RuntimeException: Could not create filter class using constructor public org.languagetool.rules.en.EnglishPartialPosTagFilter()
        at org.languagetool.rules.patterns.RuleFilterCreator.getFilter(RuleFilterCreator.java:54)
        at org.languagetool.rules.patterns.XMLRuleHandler.setRuleFilter(XMLRuleHandler.java:638)
        at org.languagetool.rules.patterns.PatternRuleHandler.createRules(PatternRuleHandler.java:615)
        at org.languagetool.rules.patterns.PatternRuleHandler.createRules(PatternRuleHandler.java:642)
        at org.languagetool.rules.patterns.PatternRuleHandler.createRules(PatternRuleHandler.java:642)
        at org.languagetool.rules.patterns.PatternRuleHandler.endElement(PatternRuleHandler.java:374)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.endNamespaceScope(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleEndElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.endElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at org.languagetool.rules.patterns.PatternRuleLoader.getRules(PatternRuleLoader.java:73)
        ... 27 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.languagetool.rules.patterns.RuleFilterCreator.getFilter(RuleFilterCreator.java:47)
        ... 48 more
Caused by: java.lang.RuntimeException: Problems with loading disambiguation file: en/disambiguation.xml
        at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.<init>(XmlRuleDisambiguator.java:53)
        at org.languagetool.tagging.en.EnglishHybridDisambiguator.<init>(EnglishHybridDisambiguator.java:43)
        at org.languagetool.language.English.createDefaultDisambiguator(English.java:133)
        at org.languagetool.Language.getDisambiguator(Language.java:328)
        at org.languagetool.rules.en.EnglishPartialPosTagFilter.<init>(EnglishPartialPosTagFilter.java:46)
        ... 53 more
Caused by: java.lang.IllegalArgumentException: maxOccurrences should be between -1 and 127
        at org.languagetool.rules.patterns.PatternToken.setMaxOccurrence(PatternToken.java:407)
        at org.languagetool.rules.patterns.XMLRuleHandler.finalizeTokens(XMLRuleHandler.java:571)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleHandler.endElement(DisambiguationRuleHandler.java:352)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleLoader.getRules(DisambiguationRuleLoader.java:46)
        at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.loadPatternRules(XmlRuleDisambiguator.java:72)
        at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.<init>(XmlRuleDisambiguator.java:51)
        ... 57 more

<snip>\lt52-ste>
```

**Comment by danielnaber** [comment]
> To what does maxOccurrences refer?

It's `max` in XML, do you use a value for it smaller than -1 or larger than 127?

**Comment by MikeUnwalla** [comment]
Thanks @danielnaber ,

One rule had `max="200"`. I changed it to `max="127"` and all is well.
