### ISSUE TITLE
Crash with "Tipus farola."

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#413]
`Tipus farola.` (Catalan) makes LT crash:

```
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 7
NCM(000
       ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.accept(Pattern.java:1813)
	at java.util.regex.Pattern.group0(Pattern.java:2908)
	at java.util.regex.Pattern.sequence(Pattern.java:2051)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at org.languagetool.synthesis.ca.CatalanSynthesizer.synthesize(CatalanSynthesizer.java:125)
	at org.languagetool.rules.patterns.MatchState.toFinalString(MatchState.java:251)
	at org.languagetool.rules.patterns.PatternRuleMatcher.concatMatches(PatternRuleMatcher.java:403)
	at org.languagetool.rules.patterns.PatternRuleMatcher.formatMatches(PatternRuleMatcher.java:304)
	at org.languagetool.rules.patterns.PatternRuleMatcher.createRuleMatch(PatternRuleMatcher.java:155)
	at org.languagetool.rules.patterns.PatternRuleMatcher.match(PatternRuleMatcher.java:137)
	at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:162)
	... 7 more

```

Jaume, could you maybe check if rule `FAROLA` is okay or if this is a bug in LT core?

**Comment by jaumeortola** [comment]
This happens when you try to synthesize a word and the original token, for some reason, has not the expected POS tag.  In this particular case, the POS tag NCFS000 is removed by the disambiguator from the word "farola" and the suggestion synthesis causes the crash:

`<suggestion><match no="1" postag="NC.(.).*" postag_regexp="yes" postag_replace="NCM$1000">fanal</match></suggestion>`

The desired behavior should be:
- The programm doesn't crash (it just shows no suggestion).
- A warning (in the logs) indicates that there is a problem in some rule.

I willl try to implement this solution.

**Comment by jaumeortola** [comment]
Now the error is catched: https://github.com/languagetool-org/languagetool/commit/4e28394872caae0904b6242614f6aabd19fe0a82
