### ISSUE TITLE
docker container not working

### ISSUE THREAD

**Issue by jdtorrenegraneiu** [languagetool-org/languagetool#4165]
The following configuration is passed to LanguageTool:
+ java -Xms256m -Xmx512m -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8010 --public --allow-origin '*' --config config.properties
languageModel=/ngrams
2021-01-15 21:48:36 -0800 INFO org.languagetool.server.DatabaseAccess Not setting up database access, dbDriver is not configured
2021-01-16 05:48:36 +0000 WARNING: running in HTTP mode, consider running LanguageTool behind a reverse proxy that takes care of encryption (HTTPS)

2021-01-16 05:48:36 +0000 WARNING: running in public mode, LanguageTool API can be accessed without restrictions!

2021-01-16 05:48:37 +0000 Setting up thread pool with 10 threads
2021-01-16 05:48:37 +0000 Starting LanguageTool 5.2 (build date: 2020-12-30 14:55, eb572bf) server on http://localhost:8010...
2021-01-16 05:48:37 +0000 Server started
2021-01-15 21:48:44 -0800 ERROR org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default', sending HTTP code 400. Access from 192.168.1.10, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75, User agent param: null, Referrer: null, language: en-us, h: 1, r: 1, time: 2m: ALL, l: DEFAULT, Stacktrace follows:java.lang.IllegalArgumentException: This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default

at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:190)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by danielnaber** [comment]
We don't provide Docker containers, so you should open an issue in the Docker container repo. But the problem you're looking for seems to be `You have not specified any parameters`, i.e. the request you send is incomplete.
