### ISSUE TITLE
Clean build of org.languagetool.commandline fails with AssertionError in testPolishApiStdInDefaultOff

### ISSUE THREAD

**Issue by fragmer** [languagetool-org/languagetool#418]
Today I downloaded a copy of languagetool v3.3 source (as a zip snapshot from the ["releases"](https://github.com/languagetool-org/languagetool/releases/tag/v3.3) page) and tried to build it with maven 3.0.5 via NetBeans 8.1. The build was going smoothly until a unit test failed in "LanguageTool command-line version" (**org.languagetool.commandline.MainTest.testPolishApiStdInDefaultOff**):

```
Running org.languagetool.commandline.MainTest
Tests run: 41, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.167 sec <<< FAILURE! - in org.languagetool.commandline.MainTest
testPolishApiStdInDefaultOff(org.languagetool.commandline.MainTest)  Time elapsed: 0.03 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <1>
     but: was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.languagetool.commandline.MainTest.testPolishApiStdInDefaultOff(MainTest.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)


Results :

Failed tests: 
  MainTest.testPolishApiStdInDefaultOff:331 
Expected: is <1>
     but: was <3>
```

### Steps to reproduce:
1) Get a copy of languagetool v3.3 source 
2) run `mvn clean install` on languagetool-parent

### System info:
OS: Windows 10 running on amd64; Cp1252; en_US (nb)
JRE: Java SE 1.8.0_92-b14; HotSpot 64-Bit Server VM 25.92-b14
IDE: NetBeans IDE 8.1
Maven: 3.0.5

### Additional info:
Complete Maven log: https://gist.github.com/fragmer/979b949a06cfbb23de8b118eee8e8a9e

Throughout the log file, maven-surefire-plugin produced the following warnings, which may potentially be relevant: `file.encoding cannot be set as system property, use <argLine>-Dfile.encoding=...</argLine> instead`

**Comment by fragmer** [comment]
I tried building the same source snapshot with a different version of Maven (standalone 3.3.9), on the same machine/OS/JDK/JRE, and got the exact same AssertionError.  Here is the complete log file: https://gist.github.com/fragmer/f299baa8da86c329093a6ecc6a901a2c

**Comment by fragmer** [comment]
Here is the line where the AssertionException is thrown: https://github.com/languagetool-org/languagetool/blob/faaf778a1a1409c2f9628293ef732ee487de636a/languagetool-commandline/src/test/java/org/languagetool/commandline/MainTest.java#L343

Debugging the unit test, the actual value of "output" is as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<matches software="LanguageTool" version="3.3" buildDate="null">
<language shortname="pl-PL" name="Polish"/>
<error fromy="0" fromx="30" toy="0" tox="35" ruleId="PL_WORD_REPEAT" msg="PowtÃ³rzony wyraz w zdaniu" shortmsg="PowtÃ³rzenie wyrazu" replacements="" context="To jest test, ktÃ³ry zrobi?em, ktÃ³ry mi si? podoba." contextoffset="30" offset="30" errorlength="5" category="BÅ‚Ä™dy rÃ³Å¼ne" categoryid="MISC" locqualityissuetype="style"/>
<error fromy="0" fromx="43" toy="0" tox="49" ruleId="UPPERCASE_SENTENCE_START" msg="To zdanie nie zaczyna siÄ™ wielkÄ… literÄ…" replacements="Podoba" context="To jest test, ktÃ³ry zrobi?em, ktÃ³ry mi si? podoba." contextoffset="43" offset="43" errorlength="6" category="Pisownia maÅ‚Ä… i wielkÄ… literÄ…" categoryid="CASING" locqualityissuetype="typographical"/>
<error fromy="0" fromx="43" toy="0" tox="49" ruleId="ZWROTNE_BEZ_SIE" subId="1"  msg="W tym zdaniu wystÄ™puje czasownik zwrotny, a brakuje wyrazu â€žsiÄ™â€�; powinno byÄ‡: &apos;podoba siÄ™&apos; lub &apos;siÄ™ podoba&apos;." shortmsg="Prawdopodobna literÃ³wka" replacements="podoba siÄ™#siÄ™ podoba" context="To jest test, ktÃ³ry zrobi?em, ktÃ³ry mi si? podoba." contextoffset="43" offset="43" errorlength="6" category="Prawdopodobne literÃ³wki" categoryid="TYPOS" locqualityissuetype="misspelling"/>
</matches>
<!--
Time: 31ms for 2 sentences (64.5 sentences/sec)
-->
```

Tangential note: The string ends up being interpreted by JVM as CP-1252 instead of UTF-8. If I explicitly set the charset on the line above (`final String output = new String(this.out.toByteArray(), Charset.forName("UTF-8"))`) then I end up with correct encoding:

```
<?xml version="1.0" encoding="UTF-8"?>
<matches software="LanguageTool" version="3.3" buildDate="null">
<language shortname="pl-PL" name="Polish"/>
<error fromy="0" fromx="30" toy="0" tox="35" ruleId="PL_WORD_REPEAT" msg="Powtórzony wyraz w zdaniu" shortmsg="Powtórzenie wyrazu" replacements="" context="To jest test, który zrobi?em, który mi si? podoba." contextoffset="30" offset="30" errorlength="5" category="Błędy różne" categoryid="MISC" locqualityissuetype="style"/>
<error fromy="0" fromx="43" toy="0" tox="49" ruleId="UPPERCASE_SENTENCE_START" msg="To zdanie nie zaczyna się wielką literą" replacements="Podoba" context="To jest test, który zrobi?em, który mi si? podoba." contextoffset="43" offset="43" errorlength="6" category="Pisownia małą i wielką literą" categoryid="CASING" locqualityissuetype="typographical"/>
<error fromy="0" fromx="43" toy="0" tox="49" ruleId="ZWROTNE_BEZ_SIE" subId="1"  msg="W tym zdaniu występuje czasownik zwrotny, a brakuje wyrazu „się”; powinno być: &apos;podoba się&apos; lub &apos;się podoba&apos;." shortmsg="Prawdopodobna literówka" replacements="podoba się#się podoba" context="To jest test, który zrobi?em, który mi si? podoba." contextoffset="43" offset="43" errorlength="6" category="Prawdopodobne literówki" categoryid="TYPOS" locqualityissuetype="misspelling"/>
</matches>
<!--
Time: 26ms for 2 sentences (76.9 sentences/sec)
-->
````

...but either way, there are 3 "<error>" tags in the output rather than the expected 1, and the test fails.

**Comment by danielnaber** [comment]
Could you try with the latest code from git to see if the problem occurs there, too?

**Comment by fragmer** [comment]
The original reported problem (related to testPolishApiStdInDefaultOff) appears to be fixed in master -- I was able to build "LanguageTool command-line version" and its dependencies without problems from the latest code. I did run into a different, unrelated build problem, but I will report it separately. Thanks!
