### ISSUE TITLE
Postag_replace gives an incorrect postag if the pattern is thelast token

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#435]
This rule shows the problem:
```
        <rule id="POSTAG_REPLACE" name="postag_replace">
            <pattern>
                <token inflected="yes">test</token>
            </pattern>
            <message>Use <suggestion><match no="1" postag="(.*)" postag_replace="$1">trial</match></suggestion>.</message>
            <short>postag_replace</short>
            <example>We did some <marker>trials</marker>.</example>
            <example correction="trials">And we also did some <marker>tests</marker>.</example>
            <example type="triggers_error">The last token gets a postag in parentheses: <marker>Tests</marker></example>
        </rule>
```
![postag-in-parentheses](https://cloud.githubusercontent.com/assets/5816160/16731117/623f499a-476e-11e6-8fe1-859374f29dac.png)

**Comment by jaumeortola** [comment]
The last word of a sentence has tags for sentence end and paragraph end. In this case:
NNS 
VBZ 
SENT_END 
PARA_END 

You need to specify the postag you want to use in the suggestion syntesis. For example:

`<suggestion><match no="1" postag="(N.*)" postag_replace="$1">trial</match></suggestion>`

**Comment by MikeUnwalla** [comment]
Jaume, thanks.

Your suggestion solves the problem of the postag in parentheses in the GUI. But, if I remove  `type="triggers_error"`, testrules gives this error:
```
Running pattern rule tests for English... Exception in thread "main" java.lang.AssertionError: English: Did not expect e
rror in:
  The last token gets a postag in parentheses: Tests
Matching Rule: POSTAG_REPLACE[1]
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.languagetool.rules.patterns.PatternRuleTest.testCorrectSentences(PatternRuleTest.java:472)
        at org.languagetool.rules.patterns.PatternRuleTest.testGrammarRulesFromXML(PatternRuleTest.java:272)
        at org.languagetool.rules.patterns.PatternRuleTest.runTestForLanguage(PatternRuleTest.java:198)
        at org.languagetool.rules.patterns.PatternRuleTest.runGrammarRulesFromXmlTestIgnoringLanguages(PatternRuleTest.j
ava:149)
        at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:558)
```

**Comment by jaumeortola** [comment]
We fixed the error. So the example should be like:
`<example correction="Trials">The last token DOESN'T get a postag in parentheses: <marker>Tests</marker></example>`

**Comment by MikeUnwalla** [comment]
Yes. Sorry.
