### ISSUE TITLE
LibreOffice 7.1.2.2 with LanguageTool 5.3: java.lang.NullPointerException (LinguisticServices.java:188)

### ISSUE THREAD

**Issue by sbourlon** [languagetool-org/languagetool#4834]
Hello LanguageTool team,

I just installed LanguageTool 5.3 from https://extensions.libreoffice.org/en/extensions/show/languagetool and got the following error when turning on LanguageTool by clicking "Switch Off/On":

## Error:
```
% libreoffice --writer
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.NullPointerException
	at org.languagetool.openoffice.LinguisticServices.getLocale(LinguisticServices.java:188)
	at org.languagetool.openoffice.SpellAndGrammarCheckDialog.updateDocumentCache(SpellAndGrammarCheckDialog.java:163)
	at org.languagetool.openoffice.SpellAndGrammarCheckDialog.nextError(SpellAndGrammarCheckDialog.java:201)
	at org.languagetool.openoffice.MultiDocumentsHandler.trigger(MultiDocumentsHandler.java:1176)
	at org.languagetool.openoffice.Main.trigger(Main.java:204)
```

## LibreOffice version
```
% libreoffice --version
LibreOffice 7.1.2.2 10(Build:2)
```

## OS
Archlinux running Sway
```
% uname -a 
Linux smoasb 5.11.14-arch1-1 #1 SMP PREEMPT Wed, 14 Apr 2021 12:06:34 +0000 x86_64 GNU/Linux
```

**Comment by danielnaber** [comment]
@FredKruse

**Comment by marcoagpinto** [comment]
I am using the nightly with LibreOffice 7.1.2.2 in Windows 10, and so far, no exceptions.

**Comment by xosecalvo** [comment]
Ubuntu Hirsute Hippo (development branch) aka 21.04
with packaged LibreOffice 7.1.2.2,
no issues, but other people have spotted problems with 7.1: https://extensions.libreoffice.org/en/extensions/show/languagetool

**Comment by FredKruse** [comment]
The null pointer exception is already solved in the current 5.4-snapshot. I removed an inconsistency just now: The function "next error" should run only by switched on LT.

**Comment by sbourlon** [comment]
Thank you everyone for the replied.

@FredKruse, I will wait for the release of 5.4 to test.

**Comment by kacnje** [comment]
When can we expect 5.4?
I can see that 5.4 (beta?) is available, but how to install it (Windows)?

**Comment by FredKruse** [comment]
The issue is solved. I close it.
