### ISSUE TITLE
LanguageTool nightly gives errors on TESTRULES PT

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#5406]
Hello!

I downloaded the nightlies for Wikipedia + Stand-alone to replace the older ones in my desktop.

However, the stand-alone no longer works with TESTRULES PT.

It throws many errors:

```
C:\Users\marco\Desktop\LanguageTool-20210725-snapshot\LanguageTool-5.5-SNAPSHOT>testrules pt
Running XML pattern tests...
LanguageTool version 5.5-SNAPSHOT (2021-07-25 18:39:59 +0000, f8abdb0)
Known languages: [Arabic, English, English (US), English (GB), English (Australian), English (Canadian), English (New Zealand), English (South African), Persian, French, German, German (Germany), German (Austria), German (Swiss), Simple German, Polish, Catalan, Catalan (Valencian), Italian, Breton, Dutch, Dutch (Belgium), Portuguese, Portuguese (Portugal), Portuguese (Brazil), Portuguese (Angola preAO), Portuguese (Moçambique preAO), Russian, Asturian, Belarusian, Chinese, Danish, Esperanto, Irish, Galician, Greek, Japanese, Khmer, Romanian, Slovak, Slovenian, Spanish, Spanish (voseo), Swedish, Tamil, Tagalog, Ukrainian, Testlanguage]
Running XML validation for pt/grammar.xml...
Running pattern rule tests for Portuguese...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.languagetool.language.AmericanEnglish.getRelevantLanguageModelCapableRules(AmericanEnglish.java:65)
        at org.languagetool.rules.spelling.hunspell.HunspellRule.getEnglishSpellingRules(HunspellRule.java:121)
        at org.languagetool.rules.spelling.hunspell.HunspellRule.<init>(HunspellRule.java:106)
        at org.languagetool.rules.spelling.hunspell.HunspellRule.<init>(HunspellRule.java:98)
        at org.languagetool.language.Portuguese.getRelevantRules(Portuguese.java:116)
        at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:465)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:319)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:288)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:348)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:86)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:67)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:51)
        at org.languagetool.rules.patterns.PatternRuleTest.createToolForTesting(PatternRuleTest.java:175)
        at org.languagetool.rules.patterns.PatternRuleTest.runTestForLanguage(PatternRuleTest.java:160)
        at org.languagetool.rules.patterns.PatternRuleTest.runGrammarRulesFromXmlTestIgnoringLanguages(PatternRuleTest.java:153)
        at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:728)
Caused by: java.lang.RuntimeException: Could not initialize English NER model
        at org.languagetool.ner.EnglishNamedEntityDetector.<init>(EnglishNamedEntityDetector.java:62)
        at org.languagetool.rules.en.AbstractEnglishSpellerRule.<clinit>(AbstractEnglishSpellerRule.java:49)
        ... 16 more
Caused by: java.io.IOException: Could not load file from classpath: '/eu/crydee/uima/opennlp/resources/en-ner-person.bin'
        at org.languagetool.tools.Tools.getStream(Tools.java:264)
        at org.languagetool.ner.EnglishNamedEntityDetector.<init>(EnglishNamedEntityDetector.java:58)
        ... 17 more
Running disambiguator rule tests...
Running disambiguation tests for Portuguese...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.languagetool.language.AmericanEnglish.getRelevantLanguageModelCapableRules(AmericanEnglish.java:65)
        at org.languagetool.rules.spelling.hunspell.HunspellRule.getEnglishSpellingRules(HunspellRule.java:121)
        at org.languagetool.rules.spelling.hunspell.HunspellRule.<init>(HunspellRule.java:106)
        at org.languagetool.rules.spelling.hunspell.HunspellRule.<init>(HunspellRule.java:98)
        at org.languagetool.language.Portuguese.getRelevantRules(Portuguese.java:116)
        at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:465)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:319)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:288)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:348)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:255)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.testDisambiguationRulesFromXML(DisambiguationRuleTest.java:70)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.main(DisambiguationRuleTest.java:238)
Caused by: java.lang.RuntimeException: Could not initialize English NER model
        at org.languagetool.ner.EnglishNamedEntityDetector.<init>(EnglishNamedEntityDetector.java:62)
        at org.languagetool.rules.en.AbstractEnglishSpellerRule.<clinit>(AbstractEnglishSpellerRule.java:49)
        ... 12 more
Caused by: java.io.IOException: Could not load file from classpath: '/eu/crydee/uima/opennlp/resources/en-ner-person.bin'
        at org.languagetool.tools.Tools.getStream(Tools.java:264)
        at org.languagetool.ner.EnglishNamedEntityDetector.<init>(EnglishNamedEntityDetector.java:58)
        ... 13 more
Running XML bitext pattern tests...
Bitext pattern tests successful.
Validating false-friends.xml...
Validation successfully finished.

```

**Comment by danielnaber** [comment]
Should work again now
