### ISSUE TITLE
[en] Missing POS for 'long'

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#5518]
The POS (RB, RBS, RBR) for the adverbs long/longer/longest are missing.

https://www.lexico.com/definition/long
https://www.merriam-webster.com/dictionary/long

(Adding the POS causes test failures in Premium, and I don't have time to deal with them.)

**Comment by atif-github-venture** [comment]
I wanted to explore a little here.. do you think you can point me to a unit test case which does POS tagging from code base? or any class or a document which can explain the usage of that class?
I want to understand first how the current logic of POS tagging works in this application. @MikeUnwalla

**Comment by atif-github-venture** [comment]
@MikeUnwalla @jaumeortola can anyone of you please point me in a direction here? Knowing a class and the rule xml will be a good place to start working on this issue.

**Comment by atif-github-venture** [comment]
Any tip here?

We added below in following file languagetool-language-modules/src/main/resources/org/languagetool/resource/en/added.txt:

longer	longer	RBS
longest	longest	RBR
long	long	RB

it passed the unit tests for this issue.. but its breaking at 2 places..

1. [ERROR] Tests run: 6, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 25.861 s <<< FAILURE! - in org.languagetool.rules.en.EnglishPatternRuleTest
[ERROR] testRules(org.languagetool.rules.en.EnglishPatternRuleTest)  Time elapsed: 21.13 s  <<< ERROR!
org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule FROM_FORM[5] in file /org/languagetool/rules/en/grammar.xml: Example sentence marked with 'triggers_error' didn't actually trigger an error: 'Over one million Taiwanese participate in the 228 Hand-in-Hand rally form a long human chain to commemorate the February 28 Incident in 1947.'
        at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:322)

2.
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.351 s <<< FAILURE! - in org.languagetool.rules.en.EnglishTest
[ERROR] testLanguage(org.languagetool.rules.en.EnglishTest)  Time elapsed: 9.307 s  <<< FAILURE!
java.lang.AssertionError: Disambiguated sentence is equal to the input sentence for rule: DT_JJ_NN_NN. The sentence was: <S> The[the/DT,B-NP-singular] elephant[elephant/NN,E-NP-singular] swings[swing/NNS,swing/VBZ,B-VP] its[it/PRP$_A3SN,it/PRP$_P3SN,its/PRP$,B-NP-singular] long[long/RB,long/JJ,long/NN:UN,long/VB,long/VBP,I-NP-singular] nose[nose/NN,nose/VB,nose/VBP,E-NP-singular].[./.,</S>./PCT,O]
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.testDisambiguationRulesFromXML(DisambiguationRuleTest.java:161)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.testDisambiguationRulesFromXML(DisambiguationRuleTest.java:79)

**Comment by atif-github-venture** [comment]
Also tried adding below to disambiguation.xml but it does have any effect.. also tried adding the same to grammar.xml

Any tips?

    <rule id="LONGER_RBS" name="Longer => RBS">
        <pattern case_sensitive="no">
            <marker><token>longer</token></marker>
        </pattern>
        <disambig action="add" postag="UP"/>
        
    </rule>

**Comment by MikeUnwalla** [comment]
>  Example sentence marked with 'triggers_error' didn't actually trigger an error:

'triggers_error' means that a sentence is correct, but LT gives a warning.

If a sentence is marked with 'triggers_error' and if after a change the error does not occur, you will see the message.

Because the sentence is correct, you can remove 'triggers_error' from the example.

**Comment by MikeUnwalla** [comment]
>  also tried adding the same to grammar.xml

Put the rule in disambiguation.xml.

**Comment by MikeUnwalla** [comment]
> Also tried adding below to disambiguation.xml but it does have any effect.. 

Use `<wd pos="UP"/>`, thus:

```
<rule id="LONGER_RBS" name="Longer => RBS">
    <pattern>
        <token>longer</token>
    </pattern>
    <disambig action="add"><wd pos="UP"/></disambig>
</rule>
```

![image](https://user-images.githubusercontent.com/5816160/140605319-e784220f-e2de-4ac9-ae60-ccabaa4c02eb.png)

Notes:
`marker `is not necessary if the disambiguation actions apply to all the pattern.
`case_sensitive `is not necessary because the default is 'no'.

**Comment by MikeUnwalla** [comment]
> We added below in following file languagetool-language-modules/src/main/resources/org/languagetool/resource/en/added.txt:

Make sure that you used tab characters as separators, not the space character.

With tabs, I get this result:

![image](https://user-images.githubusercontent.com/5816160/140605518-e797b17a-396d-4232-a6e6-f519cabbfc4a.png)

**Comment by kjckang** [comment]
Thank you @MikeUnwalla I am working with @atif-github-venture on this issue.
Can you also clarify if these POS tags are correct?
long: RB
longer: RBS
longest: RBR

**Comment by MikeUnwalla** [comment]
@kjckang, yes, the POS tags for long are correct. Refer to the first message in this issue.

**Comment by atif-github-venture** [comment]
@MikeUnwalla  here is the PR for the solve 
https://github.com/languagetool-org/languagetool/pull/6141

contributor - @atif-github-venture, @kjckang
