### ISSUE TITLE
ConcurrentModificationException in GenericUnpairedBracketsRule with MultiThreadedJLanguageTool

### ISSUE THREAD

**Issue by amake** [languagetool-org/languagetool#555]
I have a batch issue checker that uses LanguageTool in a parallel stream. When I used a single `MultiThreadedJLanguageTool` instance, I found that I could reliably get the exception included below.  In this scenario, `check(String)` is being called ~10,000 times over ~10 seconds with all default rules for en-US enabled.

I have an alternate implementation in which I use regular `JLanguageTool` wrapped in a `ThreadLocal`; it seems to be working well enough, so this is not an urgent issue for me.

```
18796: Error: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException 
18796: Error: 	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:176) 
18796: Error: 	at org.languagetool.JLanguageTool.check(JLanguageTool.java:511) 
18796: Error: 	at org.languagetool.JLanguageTool.check(JLanguageTool.java:461) 
18796: Error: 	at org.languagetool.JLanguageTool.check(JLanguageTool.java:457) 
18796: Error: 	at org.omegat.languagetools.LanguageToolNativeBridge2.getRuleMatches(LanguageToolNativeBridge2.java:106) 
18796: Error: 	at org.omegat.languagetools.LanguageToolNativeBridge2.getCheckResults(LanguageToolNativeBridge2.java:87) 
18796: Error: 	at org.omegat.languagetools.LanguageToolIssueProvider.getIssues(LanguageToolIssueProvider.java:69) 
18796: Error: 	at org.omegat.gui.issues.IssuesPanelController$IssueLoader.lambda$5(IssuesPanelController.java:512) 
18796: Error: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) 
18796: Error: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) 
18796: Error: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) 
18796: Error: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) 
18796: Error: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) 
18796: Error: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) 
18796: Error: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
18796: Error: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) 
18796: Error: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) 
18796: Error: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) 
18796: Error: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) 
18796: Error: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) 
18796: Error: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) 
18796: Error: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) 
18796: Error: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) 
18796: Error: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) 
18796: Error: 	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) 
18796: Error: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) 
18796: Error: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) 
18796: Error: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) 
18796: Error: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) 
18796: Error: 	at java.util.stream.AbstractTask.compute(AbstractTask.java:316) 
18796: Error: 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) 
18796: Error: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) 
18796: Error: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) 
18796: Error: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) 
18796: Error: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) 
18796: Error: Caused by: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException 
18796: Error: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 
18796: Error: 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 
18796: Error: 	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:173) 
18796: Error: 	... 34 more 
18796: Error: Caused by: java.util.ConcurrentModificationException 
18796: Error: 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) 
18796: Error: 	at java.util.ArrayList$Itr.next(ArrayList.java:851) 
18796: Error: 	at org.languagetool.rules.GenericUnpairedBracketsRule.match(GenericUnpairedBracketsRule.java:146) 
18796: Error: 	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:930) 
18796: Error: 	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:897) 
18796: Error: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
18796: Error: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
18796: Error: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
18796: Error: 	at java.lang.Thread.run(Thread.java:745) 
```

**Comment by danielnaber** [comment]
Thanks for the report. It would be great if you could write a small test case to reproduce this issue.

**Comment by amake** [comment]
[Here](https://github.com/amake/languagetool-issue-555/blob/master/src/test/java/LibraryTest.java) are three test cases: one for this specific issue, and two more for issues I found while writing the test case.

**Comment by danielnaber** [comment]
`MultiThreadedJLanguageTool` isn't thread safe (just like `JLanguageTool`). It's named like this because it uses several threads internally. Usually this isn't an issue as creating new instances is fast, but I'm not sure how it can be used with `parallel()` like in your tests.

**Comment by amake** [comment]
You are absolutely correct; my naive reading of the `JLanguageTool` Javadoc made me think that `MultiThreadedJLanguageTool` was offered as a thread-safe alternative, but that is not the case. The Javadoc isn't even misleading; I was just careless.

If thread-safety is not a goal for either class (and it sounds like it isn't) then there is no problem and we can close this issue.

**Comment by danielnaber** [comment]
I've made the javadoc a bit more explicit.
