### ISSUE TITLE
trove4j: "Equal objects must have equal hashcodes"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#5645]
We sometimes get this during tests or when the LT server has just started:

```
Caused by: java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals() or TObjectHashingStrategy.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =st. john's (class java.lang.String), hashCode=-294887158; object #2 =st. john's (class java.lang.String), hashCode=-294887158
        at gnu.trove.TObjectHash.throwObjectContractViolation(TObjectHash.java:331)
        at gnu.trove.THashMap.rehash(THashMap.java:347)
        at gnu.trove.THash.postInsertHook(THash.java:285)
        at gnu.trove.THashMap.put(THashMap.java:174)
        at org.languagetool.rules.AbstractSpecificCaseRule.initializeLcToProperSpellingMap(AbstractSpecificCaseRule.java:110)
        at org.languagetool.rules.AbstractSpecificCaseRule.loadPhrases(AbstractSpecificCaseRule.java:102)
        at org.languagetool.rules.AbstractSpecificCaseRule.<init>(AbstractSpecificCaseRule.java:58)
        at org.languagetool.rules.en.EnglishSpecificCaseRule.<init>(EnglishSpecificCaseRule.java:52)
        at org.languagetool.language.English.getRelevantRules(English.java:180)
        at org.languagetool.language.AmericanEnglish.getRelevantRules(AmericanEnglish.java:55)
[...]
```

The message doesn't seem to make sense, as it cites two identical hash codes actually. Not sure how to reproduce. the bug was reported at https://bitbucket.org/trove4j/trove/issues/36/tobjectinthashmap-has-problem-with-equals without a solution.

@donnerpeter Any idea, or maybe there's a new release planned for that dependency (I think `org.jetbrains.intellij.deps:trove4j` version `1.0.20200330`)?

**Comment by donnerpeter** [comment]
The message is indeed unclear for those not used to it :) It actually means that the map is written to concurrently by several threads. I believe some synchronization should be added somewhere in the stack trace.
