### ISSUE TITLE
[fr] NullPointerException with "livre-que-je"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#5753]
> livre-que-je

```
Caused by: java.lang.RuntimeException: Error analyzing sentence: '<S> livre[livre/N e s,livrer/V imp pres 2 s,livrer/V ind pres 1 s,livrer/V ind pres 3 s,livrer/V sub pres 1 s,livrer/V sub pres 3 s]-[-/null]que[que/C sub]-je[je/R pers suj 1 s,</S><P/>]' with rule VERB_PRONOUN[1]
	at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:219)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:1295)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1846)
	... 14 more
Caused by: java.lang.NullPointerException
	at org.languagetool.synthesis.BaseSynthesizer.synthesize(BaseSynthesizer.java:199)
	at org.languagetool.rules.fr.InterrogativeVerbFilter.acceptRuleMatch(InterrogativeVerbFilter.java:107)
	at org.languagetool.rules.patterns.RuleFilterEvaluator.runFilter(RuleFilterEvaluator.java:43)
	at org.languagetool.rules.patterns.PatternRuleMatcher.createRuleMatch(PatternRuleMatcher.java:179)
	at org.languagetool.rules.patterns.PatternRuleMatcher.lambda$match$1(PatternRuleMatcher.java:83)
	at org.languagetool.rules.patterns.AbstractPatternRulePerformer.matchFrom(AbstractPatternRulePerformer.java:157)
	at org.languagetool.rules.patterns.AbstractPatternRulePerformer.doMatch(AbstractPatternRulePerformer.java:77)
	at org.languagetool.rules.patterns.PatternRuleMatcher.match(PatternRuleMatcher.java:82)
	at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:215)
	... 16 more
```

**Comment by jaumeortola** [comment]
Yes. I have detected the same problem in the nightly diff (https://internal1.languagetool.org/regression-tests/via-http/2021-09-29/fr/result_java_FAKE_RULE.html). I will fix it.

**Comment by jaumeortola** [comment]
Done: https://github.com/languagetool-org/languagetool/commit/320d0987823c0d2a41fe09997a64dd5002607789
