### ISSUE TITLE
[de] build failure: GermanCompoundRuleTest

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#5775]
I cannot make a complete build with tests because of errors in GermanCompoundRuleTest(). There are errors in these two lines: 
```
check(1, "Nur im Stand by Betrieb", "Stand-by-Betrieb");
check(1, "Blu ray Brenner", "Blu-ray-Brenner");
```

I get a spelling error in "Stand-by-Betrieb", but not in "Blu-ray-Brenner". It is very strange. 
```
3603 rules activated for language German (Germany)
1.) Line 1, column 1, Rule ID: GERMAN_SPELLER_RULE prio=-3
Message: Möglicher Tippfehler gefunden.
Suggestion: Stand-Öl-Betrieb
Stand-by-Betrieb 
^^^^^^^^^^^^^^^^ 
```

**Comment by danielnaber** [comment]
Could you post the exact failure message? The tests work for me.

**Comment by jaumeortola** [comment]
It happens only in my desktop computer (java 8 and java 11), not in my laptop. 

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.827 s <<< FAILURE! - in org.languagetool.rules.de.GermanCompoundRuleTest
[ERROR] testRule(org.languagetool.rules.de.GermanCompoundRuleTest)  Time elapsed: 4.795 s  <<< FAILURE!
java.lang.AssertionError: Expected 1 error(s), but got: [] expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.languagetool.rules.AbstractCompoundRuleTest.check(AbstractCompoundRuleTest.java:59)
	at org.languagetool.rules.de.GermanCompoundRuleTest.runTests(GermanCompoundRuleTest.java:65)
	at org.languagetool.rules.de.GermanCompoundRuleTest.testRule(GermanCompoundRuleTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by danielnaber** [comment]
Is that under Windows or Linux? Any other idea what the difference between both computers might be?

**Comment by jaumeortola** [comment]
Both computers under Linux. 

The problem is probably in the speller rule. The GermanCompoundRule tests the suggestion with GermanSpellerRule, and if the suggestions is misspelled, the rule doesn't match.

**Comment by jaumeortola** [comment]
After updating Ubuntu 18.04 to 20.04 the problem goes away. The Hunspell library that we use is somewhat instable. 
Anyway, I don't know if the current results for German compounds are the desired results (in the speller rule and in the compound rule). The words on my previous message have to be revised.

**Comment by tiff** [comment]
@jaumeortola I'm currently checking this list and making sure that these terms are in our dictionary. However, something is wrong with the logic for deciding if a word is in the dict or not:
E.g. `REFA-Fachleute*` is in the list of German compounds and not marked as a spelling mistake when you type it, but when you type `REFA Fachleute` (without a hyphen) no suggestion is made. I guess the logic is only checking if the entire word is in the dict, and not whether both words individually exist in there. At least in German and English, you can connect two words (that are in the dictionary) with a hyphen and no spelling mistake is shown.

**Comment by jaumeortola** [comment]
> At least in German and English, you can connect two words (that are in the dictionary) with a hyphen and no spelling mistake is shown.

I see. The speller we use in the rule doesn't expect multi-token words. I can change it if you want. But having the words in the spelling dictionary (specially if they are common words) is better.

**Comment by tiff** [comment]
I'd prefer having it changed. At the same time I also prefer having them in the dictionary. Especially in English we do not have many multi-word tokens in the dictionary. I will take care of adding the missing ones over the next weeks
