### ISSUE TITLE
Standalone version | UnsatisfiedLinkError | can't check german and other languages

### ISSUE THREAD

**Issue by 9Lukas5** [languagetool-org/languagetool#6144]
Hey, I'm running a Ubuntu 20.04 Machine with openjdk-11 installed. I'm pretty sure it's something with my machine, because in an Ubuntu 20.04 VM installing openjdk-11 and running language tool works just fine. 
But on my prod machine it doesn't.
I've hoped you maybe could point me to things I'd have to check, which could cause this possibly.

So, I'm trying to check German. Using  German(Germany), German(Swiss) or German(Austrian) will always result in a crash. German(Easy German) however does work.  
I checked a few other languages from the list and some crash some don't. Any idea what's going on here?

```log
java.lang.RuntimeException: Failed to initialize BridJ (java.lang.UnsatisfiedLinkError: /tmp/BridJExtractedLibraries16676556865056251587/libbridj.so: /tmp/BridJExtractedLibraries16676556865056251587/libbridj.so: Fehler beim Mappen des Shared Objects)
	at org.bridj.Platform.initLibrary(Platform.java:444)
	at org.bridj.Platform.<clinit>(Platform.java:228)
	at org.bridj.Pointer.<clinit>(Pointer.java:208)
	at org.languagetool.rules.spelling.hunspell.DumontsHunspellDictionary.<init>(DumontsHunspellDictionary.java:37)
	at org.languagetool.rules.spelling.hunspell.Hunspell.getDictionary(Hunspell.java:50)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.init(HunspellRule.java:488)
	at org.languagetool.rules.de.GermanSpellerRule.init(GermanSpellerRule.java:1244)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.ensureInitialized(HunspellRule.java:462)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.match(HunspellRule.java:155)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:1295)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1846)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1765)
	at org.languagetool.MultiThreadedJLanguageTool.lambda$null$1(MultiThreadedJLanguageTool.java:200)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/BridJExtractedLibraries16676556865056251587/libbridj.so: /tmp/BridJExtractedLibraries16676556865056251587/libbridj.so: Fehler beim Mappen des Shared Objects
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at org.bridj.Platform.initLibrary(Platform.java:420)
	... 18 more
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: German (Germany)): <sentcontent>Dies ist ein Beispiel-Text, um zu zu zeigen, wie LanguageTool funktioniert. </sentcontent>
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:217)
	at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:970)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:900)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:882)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:869)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:859)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:841)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:798)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:782)
	at org.languagetool.gui.LanguageToolSupport.checkText(LanguageToolSupport.java:753)
	at org.languagetool.gui.LanguageToolSupport.access$1700(LanguageToolSupport.java:57)
	at org.languagetool.gui.LanguageToolSupport$RunnableImpl.run(LanguageToolSupport.java:921)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: German (Germany)): <sentcontent>Dies ist ein Beispiel-Text, um zu zu zeigen, wie LanguageTool funktioniert. </sentcontent>
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:214)
	... 17 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: German (Germany)): <sentcontent>Dies ist ein Beispiel-Text, um zu zu zeigen, wie LanguageTool funktioniert. </sentcontent>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	... 19 more
Caused by: java.lang.RuntimeException: Could not check sentence (language: German (Germany)): <sentcontent>Dies ist ein Beispiel-Text, um zu zu zeigen, wie LanguageTool funktioniert. </sentcontent>
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1883)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1765)
	at org.languagetool.MultiThreadedJLanguageTool.lambda$null$1(MultiThreadedJLanguageTool.java:200)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: Could not create hunspell instance. Please note that LanguageTool supports only 64-bit platforms (Linux, Windows, Mac) and that it requires a 64-bit JVM (Java).
	at org.languagetool.rules.spelling.hunspell.DumontsHunspellDictionary.<init>(DumontsHunspellDictionary.java:45)
	at org.languagetool.rules.spelling.hunspell.Hunspell.getDictionary(Hunspell.java:50)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.init(HunspellRule.java:488)
	at org.languagetool.rules.de.GermanSpellerRule.init(GermanSpellerRule.java:1244)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.ensureInitialized(HunspellRule.java:462)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.match(HunspellRule.java:155)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:1295)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1846)
	... 8 more
Caused by: java.lang.UnsatisfiedLinkError: 'int org.bridj.Platform.sizeOf_ptrdiff_t()'
	at org.bridj.Platform.sizeOf_ptrdiff_t(Native Method)
	at org.bridj.Platform.<clinit>(Platform.java:232)
	at org.bridj.Pointer.<clinit>(Pointer.java:208)
	at org.languagetool.rules.spelling.hunspell.DumontsHunspellDictionary.<init>(DumontsHunspellDictionary.java:37)
	... 15 more
```

**Comment by danielnaber** [comment]
What kind of hardware is that? What's the command you call?

**Comment by 9Lukas5** [comment]
I either open it by double clicking the jar file or, to capture the log and see maybe other things going on I used the terminal with `java -jar languagetool.jar`

Ryzen 4700U , Lenovo laptop (so amd64 platform)

**Comment by baarsrj** [comment]
I had something like this some time ago, and switched to a lower version of Java.

This works for me on (K)ubuntu:
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by 9Lukas5** [comment]
Didn't help sadly^^ Tried 1.8, 11 and 17 now. Same behavior on all of them. But as said, just on this machine :thinking:

**Comment by 9Lukas5** [comment]
Oh my god.....I fixed it. I'm so sorry. :facepalm: 

I enabled a tmpfs ramdisk for my /tmp folder lately. Turns out I disallowed executing files from that mount, which is done for certain languages. Removed the `noexec` argument from the mount definition and it works just fine again. :tipping_hand_person:
