### ISSUE TITLE
[de-DE] OutOfMemoryError in GermanSpellerRule#getAdditionalTopSuggestions

### ISSUE THREAD

**Issue by MadRiv** [languagetool-org/languagetool#668]
languagetool: `v3.6`
jvm options: `-Xmx1024m -Xms1024m`
```
String text = "free-and-open-source-and-cross-platform";
JLanguageTool languageTool = new JLanguageTool(new GermanyGerman());
languageTool.check(text);
```
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.languagetool.rules.de.GermanSpellerRule.getAdditionalTopSuggestions(GermanSpellerRule.java:309)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.match(HunspellRule.java:105)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:644)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:991)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:943)
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:606)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:558)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:508)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:504)
```

**Comment by danielnaber** [comment]
Thanks for the report, I've committed a workaround. @f-knorr, maybe you know a better solution? You made changes to `GermanSpellerRule` recently... (well, not *that* recently).

**Comment by f-knorr** [comment]
@danielnaber You are right! The `OutOfMemoryError` results from changes that I committed a few months ago (for better support of hyphenated compounds).  The only fix is, indeed, to stop searching for suggestions when a certain limited is reached (exponential growth!).
I will have a look at it, but i think the only change will be to move the check that stops the search.
