### ISSUE TITLE
[fr] runtime exception

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#6859]
Input text: 

`Après huit minutes d’un vol trop court, je repère le ter­rain d’atterrissage, et le del­ta­plane déjà posé. On approche, rota­tion rapide en finale et coup de vent tra­ver­sier au tou­cher, je me retrouve lamen­ta­ble­ment vau­tré, mort de rire, tan­dis que la voile se rabat sur ma gauche. Quand je me relève de mon ridi­cule, Auré­lie est à peine moins hilare, mer­ci pour la com­pas­sion ! (Bon, j’avoue, j’aurais sans doute été bien plus vache à sa place — meuh non, je suis pas moqueur.)\nAprès huit mois de co-construction impliquant les services déconcentrés de l’État, les collectivités territoriales, les entreprises, les associations, les partenaires et les citoyens, le Gouvernement dévoile ses engagements pour que le quotidien des habitants des quartiers change réellement, et pour que la France soit une chance pour chacun.\nAprès Huma, RS nous propose un modèle du petit hélicoptère Flettner qui devait être produit à 1000 exemplaires mais s’arrêta à 25-26. Le kit apparaît plus fin que celui du concurrent allemand et surtout offre l’option entre la version « torpedo » et la version à nez plein (et à empennages modifiés). Il ne manque donc plus que la version à nez transparent pour que la série soit complète. L’ensemble est bien détaillé et on appréciera les rotors d’une pièce.\nAprès Hydro-Québec en 2016, c'est maintenant au tour de la Sépaq d'appuyer QuébecOiseaux à l'occasion du prochain concert-bénéfice, qui aura lieu le 22 février 2017 au Conservatoire de musique de...\nAprès, il a regardé mes pneus et m'a dit que je devrais remercier ma bonne étoile de ne pas m'être déjà foutue en l'air. J'ai baissé la tête et demandé si je pouvais avoir rendez-vous la semaine prochaine. Oui.\naprès il augmente que lorsqu'on coupe l'alim électrique, ou un simple redémarrage de la box, coupure de courant.\nAprès, il est classique de trouver des associations avec des figs ou avec des joueurs avec plus de figs que nécessaires (oui, je ne suis pas seul !!) qui peuvent dépanner (voir "http://teamfrancebb.positifforum.com/t839-annuaire-des-ligues")\nAprès, il est sorti avec une autre de mes fausses copines. Je sais pas si elle a couché avec lui. Et encore ensuite il est sorti avec la dernière de mes fausses copines mais je crois pas que ça se soit bien passé parce qu’elle était gitane et qu’elle avait pas trop le droit de regarder un gars en 206 dans les yeux. J’ai entendu dire qu’on l’avait vu courir un jour, coursé par toute la famille de la fille. Pauvre Matthieu Flamme. Aujourd’hui, vous en faites pas, il a des gosses.\nAprès, il faudra vaincre les centaines d’années de conditionnement des populations (habiter à un endroit X et bosser à un endroit Y, la distance entre X et Y étant plus ou moins grande, et couvrable de telle ou telle manière), mais avec de l’éducation de la volonté et des moyens, on devrait pouvoir y arriver !\napres il faut avoir avec le doc si il dit qu'il n'y a besoin que le ventre mais je pense aussi les poignées d'amour et les cuisses `

Error: 

> Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException
> 	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:217)
> 	at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:1016)
> 	at org.languagetool.JLanguageTool.check(JLanguageTool.java:935)
> 	at org.languagetool.JLanguageTool.check(JLanguageTool.java:920)
> 	at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:108)
> 	at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:84)
> 	at org.languagetool.commandline.Main.runOnFile(Main.java:192)
> 	at org.languagetool.commandline.Main.main(Main.java:464)
> Caused by: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException
> 	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
> 	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:214)
> 	... 7 more
> Caused by: java.lang.StringIndexOutOfBoundsException
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
> 	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
> 	... 8 more
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 444
> 	at java.lang.String.substring(String.java:1963)
> 	at org.languagetool.JLanguageTool$TextCheckCallable.findLineColumn(JLanguageTool.java:2047)
> 	at org.languagetool.JLanguageTool$TextCheckCallable.getTextLevelRuleMatches(JLanguageTool.java:1938)
> 	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1905)
> 	at org.languagetool.MultiThreadedJLanguageTool.lambda$2(MultiThreadedJLanguageTool.java:200)
> 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

It is related to this change in sentence tokenization: https://github.com/languagetool-org/languagetool/commit/56bc8a876a5678257576a99d3454f45fe1a6e717

**Comment by jaumeortola** [comment]
In the first sentences, there are several <0xad> characters. Removing them, the problem disappears. 

![imatge](https://user-images.githubusercontent.com/4289501/177213977-ef18092b-1799-4abc-869f-cf5df793b3cc.png)

**Comment by jaumeortola** [comment]
Fixed after the improvement in annotated text: https://github.com/languagetool-org/languagetool/commit/f7299aba63c2aa0ace281fd3fe1f6f1718ae5dfe
