### ISSUE TITLE
[Wikipedia Tool] Throws numerous errors

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7075]
Hello!

I was testing the rules with the Wikipedia tool:
`java -Dfile.encoding=UTF-8 -Xmx4500M -jar languagetool-wikipedia.jar check-data -l pt-PT -r GENERAL_NUMBER_AGREEMENT_ERRORS -f pt-PT.txt -f tatoeba-pt.txt --max-sentences 600000 --context-size 100 >0.txt`

It throws tons of errors:
```
C:\Users\marco\Desktop\LanguageTool-wikipedia-20220907-snapshot\LanguageTool-wikipedia-5.9-SNAPSHOT>java -Dfile.encoding=UTF-8 -Xmx4500M -jar languagetool-wikipedia.jar check-data -l pt-PT -r GENERAL_NUMBER_AGREEMENT_ERRORS -f pt-PT.txt -f tatoeba-pt.txt --max-sentences 600000 --context-size 100 >0.txt
Unexpected line format: expected three tab-separated columns: '?<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.8/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.8/ http://www.mediawiki.org/xml/export-0.8.xsd" version="0.8" xml:lang="pt">', skipping
5,000 sentences checked...
10,000 sentences checked...
Exception in thread "main" java.lang.RuntimeException: Check failed on sentence: Este estiloso hotel proporciona aos seus hóspedes andar executivo, piscina exterior e check-in/check-out expresso.
        at org.languagetool.dev.dumpcheck.SentenceSourceChecker.run(SentenceSourceChecker.java:266)
        at org.languagetool.dev.dumpcheck.SentenceSourceChecker.main(SentenceSourceChecker.java:76)
        at org.languagetool.dev.wikipedia.Main.main(Main.java:45)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): <sentcontent>Este estiloso hotel proporciona aos seus hóspedes andar executivo, piscina exterior e check-in/check-out expresso.</sentcontent>
        at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:217)
        at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:1016)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:935)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:920)
        at org.languagetool.dev.dumpcheck.SentenceSourceChecker.run(SentenceSourceChecker.java:255)
        ... 2 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): <sentcontent>Este estiloso hotel proporciona aos seus hóspedes andar executivo, piscina exterior e check-in/check-out expresso.</sentcontent>
        at java.util.concurrent.ForkJoinTask.get(Unknown Source)
        at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:214)
        ... 6 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): <sentcontent>Este estiloso hotel proporciona aos seus hóspedes andar executivo, piscina exterior e check-in/check-out expresso.</sentcontent>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
        ... 8 more
Caused by: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): <sentcontent>Este estiloso hotel proporciona aos seus hóspedes andar executivo, piscina exterior e check-in/check-out expresso.</sentcontent>
        at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:2037)
        at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1906)
        at org.languagetool.MultiThreadedJLanguageTool.lambda$null$1(MultiThreadedJLanguageTool.java:200)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error analyzing sentence: '<S> Este[este/DD0MS0] estiloso[estiloso/AQ0MS0] hotel[hotel/NCMS000] proporciona[proporcionar/VMIP3S0,proporcionar/VMM02S0] aos[a:o/SPS00:DA0MP0,a:o/SPS00:DA0MP0] seus[seu/DP3MPS] hóspedes[hóspede/AQ0CP0,hóspede/NCCP000] andar[andar/NCMS000,andar/VMN0000,andar/VMN01S0,andar/VMN03S0,andar/VMSF1S0,andar/VMSF3S0] executivo[executivo/AQ0MS0,executivo/NCMS000],[,/_PUNCT_COMMA,,/_PUNCT] piscina[piscina/NCFS000] exterior[exterior/AQ0CS0,exterior/NCMS000] e[e/CC] check-in[check-in/NCMS000]/[//_PUNCT]check[check/null]-[-/_PUNCT]out[out/NCMS000,out/RG] expresso[expressar/VMIP1S0,expressar/VMP00SM].[</S>./_PUNCT_PERIOD,./_PUNCT,<P/>]' with rule GENERAL_NUMBER_AGREEMENT_ERRORS[2]
        at org.languagetool.rules.patterns.PatternRuleMatcher.match(PatternRuleMatcher.java:98)
        at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:218)
        at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:1414)
        at org.languagetool.JLanguageTool.access$1500(JLanguageTool.java:75)
        at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1994)
        ... 7 more
Caused by: java.lang.IndexOutOfBoundsException: No group 1
        at java.util.regex.Matcher.start(Unknown Source)
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceAll(Unknown Source)

```

I was trying to fix NUMBER_AGREEMENT_ERRORS

Maybe a recent change caused it?

`TESTRULES PT` works fine.

**Comment by jaumeortola** [comment]
Fixed here: https://github.com/languagetool-org/languagetool/commit/a7b47d36c786da6f0081a81fa115e1718216d1a8

But there is still an FP in the sentence, I guess: 
```
1.) Line 1, column 37, Rule ID: GENERAL_NUMBER_AGREEMENT_ERRORS[2] premium: false
Message: Possível erro de concordância de número.
Suggestion: suas hóspedes andar; seus hóspedes andares; seu hóspede andar; seus, hóspedes andar; seus hóspedes andar-
Este estiloso hotel proporciona aos seus hóspedes andar executivo, piscina exterior e check-in/check...
                                    ^^^^^^^^^^^^^^^^^^^ 
```
