### ISSUE TITLE
Exception java.lang.NoClassDefFoundError: org/apache/commons/io/input/BOMInputStream

### ISSUE THREAD

**Issue by SinBirb** [languagetool-org/languagetool#716]
I might do something wrong, but I can not even start the program, it gives an error:

> Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/input/BOMInputStream
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.input.BOMInputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

I tried with OpenJDK 8 and Oracle JRE 8, Arch Linux

**Comment by arysin** [comment]
Can you please provide more details on how you are trying to start it?

**Comment by SinBirb** [comment]
java -jar /usr/share/java/languagetool/languagetool.jar

I'm trying to find the right configuration for Texstudio which asks for Java and LT path

**Comment by danielnaber** [comment]
Does it make a difference if you `cd` to `/usr/share/java/languagetool/` and then call `java -jar languagetool.jar`? How did `languagetool.jar` get into `/usr/share/java/`, did you copy it there? Did you copy all files or only some?

**Comment by SinBirb** [comment]
Well, sorry for bothering you. The Arch Linux package apparently completely changes the structure and there has already been a [bug](https://bugs.archlinux.org/task/44072) which I will reopen because the workaround is not working for me.
