### ISSUE TITLE
why guava:31.0.1-android?

### ISSUE THREAD

**Issue by GGintama** [languagetool-org/languagetool#7254]
Exception in thread "main" java.lang.IncompatibleClassChangeError: Class com.google.common.base.Suppliers$SupplierOfInstance does not implement the requested interface java.util.function.Supplier
	at org.languagetool.rules.RuleMatch.getSuggestedReplacementObjects(RuleMatch.java:405)
	at org.languagetool.JLanguageTool$TextCheckCallable.getTextLevelRuleMatches(JLanguageTool.java:1953)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1905)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1877)
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1338)
	at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:1016)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:935)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:920)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:910)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:892)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:849)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:833)
	at TestMainClass.check(TestMainClass.java:27)
	at TestMainClass.main(TestMainClass.java:17)

**Comment by GGintama** [comment]
implementation("org.languagetool:language-en:5.9") 

uesd in my gradle project (java8 )  ,it run errors.

**Comment by nikialeksey** [comment]
The same issue for me on version 6.0

**Comment by nikialeksey** [comment]
I've fixed it using this:
```groovy
    implementation('org.languagetool:language-all:6.0')
    implementation('com.google.guava:guava') {
        version {
            strictly '30.1-jre'
        }
    }
```

**Comment by mateuy-dev** [comment]
I've studied the issue.
Rule.java line 254 uses com.google.common.base.Suppliers.memoize function. This returns a com.google.common.base.Supplier. In older versions of guava this Google supplier implemented Java Supplier

`public interface Supplier<T> extends java.util.function.Supplier<T>`

However, in new versions it does not implement the java Supplier interface and LanguageTool fails to work.

I suppose that using the google supplier instead of the java Supplier inside this project should fix the problem.
