### ISSUE TITLE
Maven error message

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#733]
I synced my copy of the LT code. When I ran the Maven tests, I got this error message:
```

<snip>
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.languagetool.tools.RuleMatchesAsJsonSerializerTest
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.16 s <<< FAILURE! - in org.languagetool.tools.
RuleMatchesAsJsonSerializerTest
[ERROR] testJson(org.languagetool.tools.RuleMatchesAsJsonSerializerTest)  Time elapsed: 0.1 s  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.languagetool.tools.RuleMatchesAsJsonSerializerTest.testJson(RuleMatchesAsJsonSerializerTest.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)

[INFO] Running org.languagetool.tools.RuleMatchAsXmlSerializerTest
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.languagetool.tools.Rul
eMatchAsXmlSerializerTest
[ERROR] testRuleMatchesToXML(org.languagetool.tools.RuleMatchAsXmlSerializerTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError:
Did not find expected '<matches>' element, got: <?xml version="1.0" encoding="UTF-8"?>
<!-- THIS OUTPUT IS DEPRECATED, PLEASE SEE http://wiki.languagetool.org/http-server FOR A BETTER APPROACH -->
<matches software="LanguageTool" version="3.9-SNAPSHOT" buildDate="null">
<language shortname="xx-XX" name="Testlanguage"/>
<error fromy="44" fromx="98" toy="45" tox="99" ruleId="FAKE_ID" msg="myMessage" replacements="" context="...s is an test
..." contextoffset="8" offset="8" errorlength="2" category="Misc" categoryid="MISC" locqualityissuetype="misspelling"/>
</matches>

        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.languagetool.tools.RuleMatchAsXmlSerializerTest.testRuleMatchesToXML(RuleMatchAsXmlSerializerTest.java:97
)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)

[INFO] Running org.languagetool.rules.RuleWithMaxFilterTest
<snip>
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   RuleMatchAsXmlSerializerTest.testRuleMatchesToXML:97 Did not find expected '<matches>' element, got: <?xml ver
sion="1.0" encoding="UTF-8"?>
<!-- THIS OUTPUT IS DEPRECATED, PLEASE SEE http://wiki.languagetool.org/http-server FOR A BETTER APPROACH -->
<matches software="LanguageTool" version="3.9-SNAPSHOT" buildDate="null">
<language shortname="xx-XX" name="Testlanguage"/>
<error fromy="44" fromx="98" toy="45" tox="99" ruleId="FAKE_ID" msg="myMessage" replacements="" context="...s is an test
..." contextoffset="8" offset="8" errorlength="2" category="Misc" categoryid="MISC" locqualityissuetype="misspelling"/>
</matches>

[ERROR]   RuleMatchesAsJsonSerializerTest.testJson:49
[INFO]
[ERROR] Tests run: 212, Failures: 2, Errors: 0, Skipped: 3
[INFO]
<snip>

```

**Comment by danielnaber** [comment]
What command exactly are you running? `mvn test`? If so, please try `mvn clean test`.

**Comment by MikeUnwalla** [comment]
Fixed.

@danielnaber , sorry, this is not the first time that I forgot about mvn clean test. I changed my batch file so that I can't forget again.
