### ISSUE TITLE
Packaging language tool and running the HTTPServer

### ISSUE THREAD

**Issue by chrisbartoloburlo** [languagetool-org/languagetool#7417]
To package the server I am using: `mvn -DskipTests=true clean package` and get a build success. However, whenever I attempt to run it using: `java -jar ./benchmarks/languagetool/languagetool-server/target/languagetool-server-6.0-SNAPSHOT.jar` I get the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.languagetool.server.Server.<clinit>(Server.java:40)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 1 more
```

**Comment by danielnaber** [comment]
That file is not meant to be run directly. Please try using the ZIP at `languagetool-standalone/target/LanguageTool-6.0-SNAPSHOT.zip` instead.

**Comment by chrisbartoloburlo** [comment]
The issue is that I would like to gather coverage using jacoco. Is there a way to do so?
