### ISSUE TITLE
How I Build in Linux Command Line Jar Files???

### ISSUE THREAD

**Issue by crashangelbr** [languagetool-org/languagetool#792]
Hi, 
How I Build in Linux Command Line Jar Files???

**Comment by danielnaber** [comment]
Not sure if that's your question, but see http://wiki.languagetool.org/development-overview#toc2

**Comment by crashangelbr** [comment]
Hi, i Receive this error..

`[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/crash). Please verify you invoked Maven from the correct directory. -> [Help 1]
org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory (/home/crash). Please verify you invoked Maven from the correct directory.
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:84)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException`

**Comment by danielnaber** [comment]
> Please verify you invoked Maven from the correct directory.

You need to call `mvn package` in the directory to which you checked out the code from github.

**Comment by crashangelbr** [comment]
Ok, I Build.. All SUCCESS

When I Execute Command Line i receive this error..

`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/languagetool/rules/Rule
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.languagetool.rules.Rule
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more`

**Comment by danielnaber** [comment]
What command exactly are you calling? Did you exactly follow the instructions from http://wiki.languagetool.org/development-overview#toc2?

**Comment by crashangelbr** [comment]
I Try execute cmd 
`java -jar languagetool-commandline-3.9-SNAPSHOT.jar --help`

**Comment by danielnaber** [comment]
Please check closely the link I've posted: "you cannot run the *.jar directly in the target directory"

**Comment by crashangelbr** [comment]
Hummm...

Files in Zip files....

Thanks!!!!!

**Comment by holtzermann17** [comment]
[README.md](https://github.com/languagetool-org/languagetool/blob/master/README.md) mentions `mvn clean test` but not `mvn package` (per @danielnaber).  Maybe it should give more details for people who aren't familiar with maven.

By the way, to get it to run properly with Java 9 I've had to adjust a couple lines in the `.pom`, bumping up version numbers to these:

```
      <maven.jar.plugin>3.0.2</maven.jar.plugin>  <!-- NOTE: don't update without testing OpenOffice, 3.0.2 caused "Got no data stream!" after add-on installation -->
      <maven.assemby.plugin>3.0</maven.assemby.plugin>
```
