### ISSUE TITLE
[pt] Disambiguator issue with word “mesmo” - 2023-03-05

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7923]
Hello!

@susanaboatto @jaumeortola @maphjo @ricardojosehlima

I was trying to create a pt-PT rule, and the disambiguator doesn't work with the example sentences:
![Screenshot 2023-03-05 at 20-25-37 Análise de Texto - LanguageTool](https://user-images.githubusercontent.com/5192600/222984099-427ebe28-b900-4265-a2b3-47d2ad8f5785.png)

![Screenshot 2023-03-05 at 20-26-28 Análise de Texto - LanguageTool](https://user-images.githubusercontent.com/5192600/222984107-a00fe5d5-1386-408a-bd4a-25e9affbe010.png)

The rule I am creating even complains with "mesma":
```
    <!-- QUE REFERIREMOS A SEGUIR referidas a seguir -->
    <rule id='PERANTE_O_MESMO_IDENTICO' name="[pt-PT][Formal] Perante 'o mesmo' → idêntico">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2023-03-05 (2-MAR-2023+) -->
      <!-- 
	  A ciência responde diferentemente perante o mesmo conjunto de dados. → A ciência responde diferentemente perante idêntico conjunto de dados.
	  Estamos perante a mesma categoria de dados. → Estamos perante idêntica categoria de dados.
      -->
      <pattern>
	    <token regexp='no'>perante</token>
        <marker>          
          <token regexp='yes'>[ao]s?</token>
          <token regexp='yes'>mesm[ao]s?</token>
        </marker>
		<token postag='NC.+|AQ.+' postag_regexp='yes'/>
      </pattern>
      <message>Num contexto formal, é preferível escrever:</message>
      <suggestion><match no='3' postag='DD0(..)0' postag_replace='AQ0$10'>idêntico</match></suggestion>
      <example correction="idêntico">A ciência responde diferentemente perante <marker>o mesmo</marker> conjunto de dados.</example>
      <example correction="idêntica">Estamos perante <marker>a mesma</marker> categoria de dados.</example>
    </rule>
```

TESTRULES PT-PT:
```
Exception in thread "main" org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule PERANTE_O_MESMO_IDENTICO[1] in file /org/languagetool/rules/pt/pt-PT/grammar.xml (line 6174): Incorrect suggestions: Expected 'idêntico', got: '(idêntico)' on input: 'A ciência responde diferentemente perante o mesmo conjunto de dados.'
        at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:487)
        at org.languagetool.rules.patterns.PatternRuleTest.assertSuggestions(PatternRuleTest.java:754)
        at org.languagetool.rules.patterns.PatternRuleTest.testBadSentences(PatternRuleTest.java:646)
        at org.languagetool.rules.patterns.PatternRuleTest.lambda$testGrammarRulesFromXML$2(PatternRuleTest.java:522)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule PERANTE_O_MESMO_IDENTICO[1] in file /org/languagetool/rules/pt/pt-PT/grammar.xml (line 6174): Incorrect suggestions: Expected 'idêntica', got: '(idêntico)' on input: 'Estamos perante a mesma categoria de dados.'
        at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:487)
        at org.languagetool.rules.patterns.PatternRuleTest.assertSuggestions(PatternRuleTest.java:754)
        at org.languagetool.rules.patterns.PatternRuleTest.testBadSentences(PatternRuleTest.java:646)
        at org.languagetool.rules.patterns.PatternRuleTest.lambda$testGrammarRulesFromXML$2(PatternRuleTest.java:522)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Is it possible for the disambiguator to be improved?

Thanks!

**Comment by jaumeortola** [comment]
@marcoagpinto The disambiguation of "mesmo" has been improved. Try again your rule.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Thanks, I will have to wait for tomorrow's nightly since they are now released at 5pm or so.

**Comment by marcoagpinto** [comment]
Ahhhhh… Jaume, all I had to do was to copy the disambiguator.xml into my folder and I can now use the latest postags.
