### ISSUE TITLE
crash in BaseSynthesizer.synthesize (Replace UNKNOWN tag in suggestions)

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#793]
The string `de Bangladesh` makes LT crash for Portuguese with this stack trace. Looks like there's an error in the synth dict?

```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): 'de Bangladesh'
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:195)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:552)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:527)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:484)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:467)
	at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:105)
	at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:81)
	at org.languagetool.commandline.Main.runOnFile(Main.java:195)
	at org.languagetool.commandline.Main.main(Main.java:461)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): 'de Bangladesh'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.languagetool.MultiThreadedJLanguageTool.performCheck(MultiThreadedJLanguageTool.java:192)
	... 8 more
Caused by: java.lang.RuntimeException: Could not check sentence (language: Portuguese (Portugal)): 'de Bangladesh'
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1056)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:970)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:937)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error analyzing sentence: '<S> de[de/SPS00] Bangladesh[</S><P/>]'
	at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:166)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:639)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1022)
	... 6 more
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 6
DA0(..
      ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.accept(Pattern.java:1813)
	at java.util.regex.Pattern.group0(Pattern.java:2908)
	at java.util.regex.Pattern.sequence(Pattern.java:2051)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at org.languagetool.synthesis.BaseSynthesizer.synthesize(BaseSynthesizer.java:123)
	at org.languagetool.rules.patterns.MatchState.toFinalString(MatchState.java:251)
	at org.languagetool.rules.patterns.PatternRuleMatcher.concatMatches(PatternRuleMatcher.java:403)
	at org.languagetool.rules.patterns.PatternRuleMatcher.formatMatches(PatternRuleMatcher.java:304)
	at org.languagetool.rules.patterns.PatternRuleMatcher.createRuleMatch(PatternRuleMatcher.java:159)
	at org.languagetool.rules.patterns.PatternRuleMatcher.match(PatternRuleMatcher.java:137)
	at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:162)
	... 8 more

```

**Comment by TiagoSantos81** [comment]
Line 1079 (suggestion) on this rule.
```
    <rule>
      <pattern>
          <token postag="SPS00"/>
        <marker>
          <token regexp="yes" case_sensitive="yes">&paises_com_artigo;|&outros_toponimos_com_artigo;</token>
        </marker>
      </pattern>
      <message>Este nome geográfico é precedido de um artigo.</message>
        <suggestion><match no="2" postag="N.(..).+" postag_regexp="yes" postag_replace="DA0$1." case_conversion="alllower">o</match> \2</suggestion>
      <example correction="o Perú">Vão a <marker>Perú</marker>.</example><!-- XXX a o handled by CONTRACOES_OBRIGATORIAS -->
      <example correction="os EUA">Vão a <marker>EUA</marker>.</example><!-- XXX a os handled by CONTRACOES_OBRIGATORIAS -->
      <example>Perú</example>
      <example>Vão aos EUA</example>
      <example>Cerca de 500 km a oeste de Dakar, Senegal</example>
      <example>A ilha de Honshū, Japão.</example>
      <example>A ilha de Honshū (Japão).</example>
    </rule>
```
It is indeed a limitation of the base synthesizer. I had corrected before other related errors, but to make it work for everyone, the synthesizer will have to return the same type of error that it does for mismatched tags (e.g. (lemma)).
I will remove this word later today.

**Comment by TiagoSantos81** [comment]
The Portuguese part is solved, at least, until another word is found.
I will remove the portuguese part on this issue and reassign to you, since you are more acquainted with the BaseSynthesizer.java
