### ISSUE TITLE
Maven Error: LanguageTool embedded HTTP server

### ISSUE THREAD

**Issue by lreaderl** [languagetool-org/languagetool#814]
[ERROR] Failed to execute goal on project languagetool-server: Could not resolve dependencies for                 project org.languagetool:languagetool-server:jar:4.0-SNAPSHOT: The following artifacts could not b                e resolved: org.languagetool:languagetool-core:jar:4.0-SNAPSHOT, org.languagetool:languagetool-gui                -commons:jar:4.0-SNAPSHOT, org.languagetool:language-all:jar:4.0-SNAPSHOT, org.languagetool:langua                getool-core:jar:tests:4.0-SNAPSHOT: Failure to find org.languagetool:languagetool-core:jar:4.0-SNA                PSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repositor                y, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has el                apsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project language                tool-server: Could not resolve dependencies for project org.languagetool:languagetool-server:jar:4                .0-SNAPSHOT: The following artifacts could not be resolved: org.languagetool:languagetool-core:jar                :4.0-SNAPSHOT, org.languagetool:languagetool-gui-commons:jar:4.0-SNAPSHOT, org.languagetool:langua                ge-all:jar:4.0-SNAPSHOT, org.languagetool:languagetool-core:jar:tests:4.0-SNAPSHOT: Failure to fin                d org.languagetool:languagetool-core:jar:4.0-SNAPSHOT in https://oss.sonatype.org/content/reposito                ries/snapshots was cached in the local repository, resolution will not be reattempted until the up                date interval of sonatype-nexus-snapshots has elapsed or updates are forced
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(Lifecyc                leDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependenc                ies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExec                utor.java:246)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModule                Builder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModule                Builder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(                SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies                 for project org.languagetool:languagetool-server:jar:4.0-SNAPSHOT: The following artifacts could n                ot be resolved: org.languagetool:languagetool-core:jar:4.0-SNAPSHOT, org.languagetool:languagetool                -gui-commons:jar:4.0-SNAPSHOT, org.languagetool:language-all:jar:4.0-SNAPSHOT, org.languagetool:la                nguagetool-core:jar:tests:4.0-SNAPSHOT: Failure to find org.languagetool:languagetool-core:jar:4.0                -SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repos                itory, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots ha                s elapsed or updates are forced
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDepen                denciesResolver.java:208)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(Lifecyc                leDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts co                uld not be resolved: org.languagetool:languagetool-core:jar:4.0-SNAPSHOT, org.languagetool:languag                etool-gui-commons:jar:4.0-SNAPSHOT, org.languagetool:language-all:jar:4.0-SNAPSHOT, org.languageto                ol:languagetool-core:jar:tests:4.0-SNAPSHOT: Failure to find org.languagetool:languagetool-core:ja                r:4.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local                 repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapsho                ts has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRep                ositorySystem.java:393)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDepen                denciesResolver.java:202)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts coul                d not be resolved: org.languagetool:languagetool-core:jar:4.0-SNAPSHOT, org.languagetool:languaget                ool-gui-commons:jar:4.0-SNAPSHOT, org.languagetool:language-all:jar:4.0-SNAPSHOT, org.languagetool                :languagetool-core:jar:tests:4.0-SNAPSHOT: Failure to find org.languagetool:languagetool-core:jar:                4.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local re                pository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots                 has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolve                r.java:453)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifa                ctResolver.java:255)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRep                ositorySystem.java:376)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.languagetool                :languagetool-core:jar:4.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was                 cached in the local repository, resolution will not be reattempted until the update interval of s                onatype-nexus-snapshots has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCh                eckManager.java:240)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateC                heckManager.java:215)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifac                tResolver.java:594)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifa                ctResolver.java:512)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolve                r.java:430)
        ... 27 more

**Comment by danielnaber** [comment]
You cannot compile the HTTP server on its own. Either you build the top project (one level above HTTP server), which will also build the HTTP server, or you run `mvn install -DskipTests` in the top project and then compile the HTTP server.

**Comment by lreaderl** [comment]
Okay, I've done that. But can use this tool as a jar in Intellij? I wanna use it to handle a lot of texts.

**Comment by danielnaber** [comment]
I'm not sure I understand your question - IntelliJ should import it when you specify the dependency as documented at http://wiki.languagetool.org/java-api

**Comment by lreaderl** [comment]
Thanks a lot. But it's real hard for Intellij to apply the maven Setting. Finally, I use Eclipse instead. -_-
