### ISSUE TITLE
Error: Internal Error: Unsupported action: 'check/check', code 500

### ISSUE THREAD

**Issue by evandrocoan** [languagetool-org/languagetool#885]
I am running locally the server version 4.0 I just downloaded:
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

D:\User\Testes\languagetool>java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081
WARNING: running in HTTP mode, consider using org.languagetool.server.HTTPSServer for encrypted connections
Setting up thread pool with 10 threads
Starting LanguageTool 4.0 (build date: 2017-12-29 09:54) server on http://localhost:8081...
Server started
```

When I call it with your example URL `http://localhost:8081/v2/check?language=en-US&text=my+text` from http://wiki.languagetool.org/http-server it does work:
`
{"software":{"name":"LanguageTool","version":"4.0","buildDate":"2017-12-29 09:54","apiVersion":1,"status":""},"warnings":{"incompleteResults":false},"language":{"name":"English (US)","code":"en-US"},"matches":[{"message":"This sentence does not start with an uppercase letter","shortMessage":"","replacements":[{"value":"My"}],"offset":0,"length":2,"context":{"text":"my text","offset":0,"length":2},"sentence":"my text","rule":{"id":"UPPERCASE_SENTENCE_START","description":"Checks that a sentence starts with an uppercase letter","issueType":"typographical","category":{"id":"CASING","name":"Capitalization"}}}]}
`
![image](https://user-images.githubusercontent.com/5332158/35763479-4de8c816-0894-11e8-82c9-cc23ca2a75ee.png)

But when I put it on Google Chrome extension version `1.0.35`:

![image](https://user-images.githubusercontent.com/5332158/35769331-955f61d0-08f0-11e8-8d38-55b917083b9d.png)

It throw this error on the Server Console and on Google Chrome:
``` 
2018-02-03 03:36:20 Check done: 7 chars, en-US, #1, null, 1 matches, 19560ms, agent:-, sent, q:0
2018-02-03 03:36:24 An error has occurred: 'Seems like you're using an old version of our API that's not supported anymore. Please see https://languagetool.org/http-api/migration.php', sending HTTP code 400. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36, User agent param: null, Referrer: http://localhost:8081/v2/check?language=en-US&text=my+text, language: null, Stacktrace follows:
java.lang.IllegalArgumentException: Seems like you're using an old version of our API that's not supported anymore. Please see https://languagetool.org/http-api/migration.php
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:124)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
2018-02-03 03:37:08 An error has occurred: 'Unsupported action: 'check/check'', sending HTTP code 500. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36, User agent param: webextension-chrome, Referrer: null, language: auto, text length: 100676, Stacktrace follows:
java.lang.RuntimeException: Unsupported action: 'check/check'
        at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:62)
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:116)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

`
Could not check text: No valid response from http://localhost:8081/v2/check: Error: Internal Error: Unsupported action: 'check/check', code 500
`

**Comment by evandrocoan** [comment]
Thanks!
