### ISSUE TITLE
The wiki page needs an update for this example?

### ISSUE THREAD

**Issue by evandrocoan** [languagetool-org/languagetool#887]
When doing:
```
curl --data "language=en-US&text=a simple test" http://localhost:8081/v2/check
{"software":{"name":"LanguageTool","version":"4.0","buildDate":"2017-12-29 09:54","apiVersion":1,"status":""},"warnings":{"incompleteResults":false},"language":{"name":"English (US)","code":"en-US"},"matches":[{"message":"This sentence does not start with an uppercase letter","shortMessage":"","replacements":[{"value":"A"}],"offset":0,"length":1,"context":{"text":"a simple test","offset":0,"length":1},"sentence":"a simple test","rule":{"id":"UPPERCASE_SENTENCE_START","description":"Checks that a sentence starts with an uppercase letter","issueType":"typographical","category":{"id":"CASING","name":"Capitalization"}}}]}
```
I got not error on the server console:
```
2018-02-03 16:03:04 Check done: 13 chars, en-US, #4, null, 1 matches, 500ms, agent:-, sent, q:0
2018-02-03 16:03:14 Check done: 13 chars, en-US, #5, null, 1 matches, 172ms, agent:-, sent, q:0
2018-02-03 16:03:21 Check done: 13 chars, en-US, #6, null, 1 matches, 113ms, agent:-, sent, q:0
```

But the other example `http://localhost:8081/v2/check?language=en-US&text=my+text` on http://wiki.languagetool.org/http-server throws this on the server console:
```
2018-02-03 16:01:03 An error has occurred: 'Seems like you're using an old version of our API that's not supported anymore. Please see https://languagetool.org/http-api/migration.php', sending HTTP code 400. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36, User agent param: null, Referrer: http://localhost:8081/v2/check?language=en-US&text=my+text, language: null, Stacktrace follows:
java.lang.IllegalArgumentException: Seems like you're using an old version of our API that's not supported anymore. Please see https://languagetool.org/http-api/migration.php
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:124)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

The wiki page needs an update for this example?
`
http://localhost:8081/v2/check?language=en-US&text=my+text
`

**Comment by danielnaber** [comment]
You can ignore that error. It's caused by your browser trying to request a `favico.ico` file from the LT API.
