### ISSUE TITLE
[LO-Add-on] Issues with the nightly and LO 7.6.0.1 - 2023-07-20

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#9006]
@FredKruse 

Heya, Fred,

I haven't been posting LibreOffice issues because I have been using the Word add-on, but tonight I decided to try the LibreOffice one.

I opened my 600+ page thesis with the latest nightly, and after 20 minutes waiting for the add-on to process the document, the CPU load was still high and LO was unresponsive, I was trying to scroll down, and it lagged as hell, I couldn't do anything in it.

![lt_20230720](https://github.com/languagetool-org/languagetool/assets/5192600/cbb48743-20c1-4f8b-aa10-4d1a831a0c9d)

Then, here is the log file when I closed the .ODT:

```
LT office integration log from Thu Jul 20 19:23:48 BST 2023

LanguageTool 6.3-SNAPSHOT (2023-07-20 16:45:17 +0000, a3e185c)
OS: Windows 11 10.0 on amd64
LibreOffice 7.6.0.1 (The Document Foundation), en-GB
Java-Version: 1.8.0_381, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: CacheCleanUp: Remove Path from CacheMap: /C:/Users/marco/Desktop/LANGUAGETOOL TESTS/PhD_thesis_marcoagpinto_IST_1Main_V0088unsent.odt
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(4): 1126391
SingleCheck: addParaErrorsToCache: return: isDisposed = true, useQueue = true, isDialogRequest = false, TextLevelCheckQueue(isInterrupted) = null
```

And here is the log when after closing it, I opened a 1-page document:
```
CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: removeDoc: Interrupt text level queue for document 1
MultiDocumentsHandler: removeDoc: Interrupt done
Disposed document 1 removed
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 2
Time to generate cache(4): 48
```

(the second log lost all system information, the lines above is all it produced).

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse @danielnaber 

I am trying the latest nightly.

I reached the conclusion that in the last weeks I have added dozens of pages with figures and tables to my thesis, and now it must be some 620+ pages long.

After I deleted two chapters of it, the scrolling got back to normal.

I guess the thesis is “too heavy” for LanguageTool.

Fred:
Is there any way of optimising the code?

If there is no solution, feel free to close this ticket.

Thanks!

**Comment by FredKruse** [comment]
@marcoagpinto Yes, there is a new feature for LO 7.6 (I did a little LO-hack, that makes life easier for the LT extension, especially for big complicated documents including tables, figures etc.). I deactivated this for LT, because it runs automatically for LO 7.6 or later, and it isn't well tested till now.
Now, I had activated it. It would be great if you could test the next nightly with your thesis.

**Comment by marcoagpinto** [comment]
@FredKruse 

Thanks, I will test it tonight.

**Comment by marcoagpinto** [comment]
@FredKruse 

It is still slow as hell.

Even opening the .docx, then changing the whole language to Portuguese, and then going to the SAVE AS .dot menu item, then scrolling down the 631 pages.

Here is the log as I edit the document on this moment:

```
LT office integration log from Mon Jul 31 23:25:11 BST 2023

LanguageTool 6.3-SNAPSHOT (2023-07-31 16:45:38 +0000, cfef66f)
OS: Windows 11 10.0 on amd64
LibreOffice 7.6.0.1 (The Document Foundation), en-GB
Java-Version: 1.8.0_381, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(5): 63
Time to generate cache(6): 22
CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: removeDoc: Interrupt text level queue for document 1
MultiDocumentsHandler: removeDoc: Interrupt done
Disposed document 1 removed
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 2
SingleDocument: writeCaches: Copy DocumentCache
SingleDocument: writeCaches: Copy ResultCache 0
SingleDocument: writeCaches: Copy ResultCache 1
SingleDocument: writeCaches: Copy ResultCache 2
SingleDocument: writeCaches: Copy ResultCache 3
SingleDocument: writeCaches: Save Caches ...
```

And here is the log after I closed LibreOffice (it throws tons of errors):

```
LT office integration log from Mon Jul 31 23:25:11 BST 2023

LanguageTool 6.3-SNAPSHOT (2023-07-31 16:45:38 +0000, cfef66f)
OS: Windows 11 10.0 on amd64
LibreOffice 7.6.0.1 (The Document Foundation), en-GB
Java-Version: 1.8.0_381, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(5): 63
Time to generate cache(6): 22
CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: removeDoc: Interrupt text level queue for document 1
MultiDocumentsHandler: removeDoc: Interrupt done
Disposed document 1 removed
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 2
SingleDocument: writeCaches: Copy DocumentCache
SingleDocument: writeCaches: Copy ResultCache 0
SingleDocument: writeCaches: Copy ResultCache 1
SingleDocument: writeCaches: Copy ResultCache 2
SingleDocument: writeCaches: Copy ResultCache 3
SingleDocument: writeCaches: Save Caches ...
java.lang.NullPointerException
	at org.languagetool.openoffice.FlatParagraphTools.getAllFlatParagraphs(FlatParagraphTools.java:309)
	at org.languagetool.openoffice.DocumentCache.refreshWriterCache(DocumentCache.java:251)
	at org.languagetool.openoffice.DocumentCache.refresh(DocumentCache.java:169)
	at org.languagetool.openoffice.DocumentCache.refreshAndCompare(DocumentCache.java:2041)
	at org.languagetool.openoffice.CheckRequestAnalysis.handleCacheChanges(CheckRequestAnalysis.java:649)
	at org.languagetool.openoffice.CheckRequestAnalysis.getNumberOfParagraphFromSortedTextId(CheckRequestAnalysis.java:115)
	at org.languagetool.openoffice.SingleDocument.getCheckResults(SingleDocument.java:305)
	at org.languagetool.openoffice.SingleDocument.getCheckResults(SingleDocument.java:175)
	at org.languagetool.openoffice.MultiDocumentsHandler.getCheckResults(MultiDocumentsHandler.java:242)
	at org.languagetool.openoffice.MultiDocumentsHandler.doProofreading(MultiDocumentsHandler.java:180)
	at org.languagetool.openoffice.Main.doProofreading(Main.java:80)

WARNING: DocumentCache: refresh: paragraphContainer == null - ParagraphCache not initialised
XDrawPageSupplier == null
WARNING: DocumentCache: refresh: paragraphContainer == null - ParagraphCache not initialised
```

**Comment by FredKruse** [comment]
I will close this issue as solved. Open a new issue with current versions if necessary.
