### ISSUE TITLE
[pt?] TESTRULES PT doesn't work with nightly build - 2023-07-20

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#9007]
Heya,

I am not sure if anyone else has noticed it, but the new entities' implementation makes the nightly snapshot where we test the rules “`TESTRULES PT`” unusable.

```
C:\Users\BLAH BLAH\LanguageTool-20230720-snapshot\LanguageTool-6.3-SNAPSHOT>testrules pt
Running XML pattern tests...
LanguageTool version 6.3-SNAPSHOT (2023-07-20 16:45:17 +0000, a3e185c)
Known languages: [Arabic, Asturian, Belarusian, Breton, Catalan, Catalan (Valencian), Catalan (Balearic), Danish, German, German (Germany), German (Austria), German (Swiss), Simple German, Greek, English, English (US), English (GB), English (Australian), English (Canadian), English (New Zealand), English (South African), Esperanto, Spanish, Spanish (voseo), Persian, French, Irish, Galician, Italian, Japanese, Khmer, Dutch, Dutch (Belgium), Polish, Portuguese, Portuguese (Portugal), Portuguese (Brazil), Portuguese (Angola preAO), Portuguese (Moçambique preAO), Romanian, Russian, Slovak, Slovenian, Swedish, Tamil, Tagalog, Ukrainian, Chinese, Testlanguage]
Running XML validation for pt/grammar.xml...
Exception in thread "main" java.io.IOException: Cannot load or parse '/org/languagetool/rules/pt/grammar.xml'
        at org.languagetool.XMLValidator.validateWithXmlSchema(XMLValidator.java:117)
        at org.languagetool.rules.patterns.PatternRuleTest.validatePatternFile(PatternRuleTest.java:242)
        at org.languagetool.rules.patterns.PatternRuleTest.validatePatternFile(PatternRuleTest.java:218)
        at org.languagetool.rules.patterns.PatternRuleTest.runTestForLanguage(PatternRuleTest.java:189)
        at org.languagetool.rules.patterns.PatternRuleTest.runGrammarRulesFromXmlTestIgnoringLanguages(PatternRuleTest.java:184)
        at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:927)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/marco/Desktop/LanguageTool-20230720-snapshot/LanguageTool-6.3-SNAPSHOT/org/languagetool/resource/pt/entities/messages.ent
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at org.languagetool.XMLValidator$EntityAsInput.setInputStream(XMLValidator.java:301)
        at org.languagetool.XMLValidator$EntityAsInput.<init>(XMLValidator.java:387)
        at org.languagetool.XMLValidator$LSRuleEntityResolver.resolveResource(XMLValidator.java:242)
        at com.sun.org.apache.xerces.internal.util.DOMEntityResolverWrapper.resolveEntity(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntityAsPerStax(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.startPE(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.skipSeparator(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDecls(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDTDInternalSubset(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(Unknown Source)
        at javax.xml.validation.Validator.validate(Unknown Source)
        at org.languagetool.XMLValidator.validateInternal(XMLValidator.java:218)
        at org.languagetool.XMLValidator.validateWithXmlSchema(XMLValidator.java:115)
        ... 5 more
Running disambiguator rule tests...
Running disambiguation tests for Portuguese...
Exception in thread "main" java.io.IOException: Cannot load or parse '/org/languagetool/resource/pt/disambiguation.xml'
        at org.languagetool.XMLValidator.validateWithXmlSchema(XMLValidator.java:117)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.validateRuleFile(DisambiguationRuleTest.java:98)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.testDisambiguationRulesFromXML(DisambiguationRuleTest.java:78)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.main(DisambiguationRuleTest.java:246)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/marco/Desktop/LanguageTool-20230720-snapshot/LanguageTool-6.3-SNAPSHOT/org/languagetool/resource/pt/entities/messages.ent
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at org.languagetool.XMLValidator$EntityAsInput.setInputStream(XMLValidator.java:301)
        at org.languagetool.XMLValidator$EntityAsInput.<init>(XMLValidator.java:387)
        at org.languagetool.XMLValidator$LSRuleEntityResolver.resolveResource(XMLValidator.java:242)
        at com.sun.org.apache.xerces.internal.util.DOMEntityResolverWrapper.resolveEntity(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntityAsPerStax(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.startPE(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.skipSeparator(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDecls(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDTDInternalSubset(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(Unknown Source)
        at javax.xml.validation.Validator.validate(Unknown Source)
        at org.languagetool.XMLValidator.validateInternal(XMLValidator.java:218)
        at org.languagetool.XMLValidator.validateWithXmlSchema(XMLValidator.java:115)
        ... 3 more
Running XML bitext pattern tests...
Bitext pattern tests successful.
Validating false-friends.xml...
Validation successfully finished.
```

**Comment by danielnaber** [comment]
@p-goulart Can you reproduce that?

**Comment by p-goulart** [comment]
No, I can't, the path resolution works here. But crucially, I'm not on Windows.

There might be a simple solution, but I can't test it very easily.

@jaumeortola, I know you're on Windows, can you try to repro this issue? If yes, would you have 10 minutes today to test a simple solution that I may have found? Thanks!

**Comment by p-goulart** [comment]
@marcoagpinto if you're interested in testing the solution locally, just reach out to me and I'll explain how to do it.

**Comment by marcoagpinto** [comment]
@p-goulart 

Ahhhh... sure, I have to go buy Coca-Cola, I will return in 30 minutes.

**Comment by marcoagpinto** [comment]
@p-goulart 

Heya, I am back, what should I do?

**Comment by p-goulart** [comment]
> @p-goulart
> 
> Heya, I am back, what should I do?

Instructions already given in [this comment](https://github.com/languagetool-org/languagetool/issues/9007#issuecomment-1645047977).

**Comment by p-goulart** [comment]
@susanaboatto this is the same error you were getting in #8999 , can you also check my solution?

**Comment by marcoagpinto** [comment]
Ahhhh… I can't build apps, I have never tried doing it.

😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 

@susanaboatto 
Can you try Pedro's solution?

Thanks!

**Comment by p-goulart** [comment]
No worries, we need to test it internally anyway! Sorry about the inconvenience, that's always a risk when we try to optimise things. Please bear with us at we sort this out.

**Comment by jaumeortola** [comment]
I confirm that the problem is solved on Windows with these changes: https://github.com/languagetool-org/languagetool/pull/9023
