### ISSUE TITLE
Could not connect OpenNMT server at http://127.0.0.1:7784/translator/translate

### ISSUE THREAD

**Issue by evandrocoan** [languagetool-org/languagetool#903]
Command line:
```
java -cp languagetool.jar org.languagetool.gui.Main -t
```

![image](https://user-images.githubusercontent.com/5332158/36212191-78e7eb2e-118a-11e8-8d14-29c56611c06d.png)

```
2018-02-14 13:19:38 An error has occurred: 'java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: English (US)): 'Test test.'', sending HTTP code 500. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36, User agent param: webextension-chrome, Referrer: null, language: en-US, text length: 10, Stacktrace follows:
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: English (US)): 'Test test.'
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at org.languagetool.server.TextChecker.checkText(TextChecker.java:148)
    at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:84)
    at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:58)
    at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:116)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
    at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
    at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: English (US)): 'Test test.'
    at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:641)
    at org.languagetool.JLanguageTool.check(JLanguageTool.java:580)
    at org.languagetool.JLanguageTool.check(JLanguageTool.java:538)
    at org.languagetool.server.TextChecker.getRuleMatches(TextChecker.java:246)
    at org.languagetool.server.TextChecker.access$000(TextChecker.java:45)
    at org.languagetool.server.TextChecker$1.call(TextChecker.java:142)
    at org.languagetool.server.TextChecker$1.call(TextChecker.java:135)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    ... 3 more
Caused by: java.lang.RuntimeException: Could not check sentence (language: English (US)): 'Test test.'
    at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1119)
    at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1022)
    at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:989)
    at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:637)
    ... 10 more
Caused by: java.lang.RuntimeException: Could not connect OpenNMT server at http://127.0.0.1:7784/translator/translate
    at org.languagetool.rules.OpenNMTRule.postToServer(OpenNMTRule.java:194)
    at org.languagetool.rules.OpenNMTRule.match(OpenNMTRule.java:83)
    at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:667)
    at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1077)
    ... 13 more
```

The port 7784 is free, no one else is using it. What is it?

Perhaps related to: https://github.com/languagetool-org/languagetool/issues/698 Better message for 'Get corrections from an OpenNMT server (beta)

This only happens for `English (US)`:

![image](https://user-images.githubusercontent.com/5332158/36212462-2bbf2dc0-118b-11e8-8c0b-26950536ac24.png)

If I select English (British) or (Australian) it works:

![image](https://user-images.githubusercontent.com/5332158/36212527-4defe57e-118b-11e8-8f40-20294a7a8ead.png)

```
2018-02-14 13:31:33 Using options configured in the GUI
2018-02-14 13:31:34 Check done: 10 chars, en-AU (mother tongue: pt), #1, null, 1 matches, 2080ms, agent:webextension-chrome, sent, q:0
2018-02-14 13:32:32 Using options configured in the GUI
2018-02-14 13:32:32 Check done: 10 chars, en-GB (mother tongue: pt), #3, null, 1 matches, 131ms, agent:webextension-chrome, sent, q:0
```

___

Running directly the server, I have no problems:
```
java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081
```

**Comment by danielnaber** [comment]
You need to turn off the rule named `Get corrections from an OpenNMT server (beta)`

**Comment by evandrocoan** [comment]
Where is this option?

**Comment by evandrocoan** [comment]
I just found it on `Miscellaneous`:

![image](https://user-images.githubusercontent.com/5332158/36212838-2bf9def6-118c-11e8-8a59-f8797f1a9de7.png)

**Comment by evandrocoan** [comment]
Perhaps would be better put it on here:

![image](https://user-images.githubusercontent.com/5332158/36212923-62ff872a-118c-11e8-8db0-183ff7ff2c40.png)

**Comment by danielnaber** [comment]
I have removed the option for now, as it caused confusion when activated by accident.
