### ISSUE TITLE
UnsupportedOperationException on addIgnoreWords (unmodifiable list)

### ISSUE THREAD

**Issue by rasael** [languagetool-org/languagetool#910]
Hi, I'm experiencing this exception with languagetool 4.0 using the following languages: Portuguese, SwissGerman.

Following is the exception for the SwissGerman error:

Caused by: java.lang.RuntimeException: Could not check sentence (language: German (Swiss)): 'dies is deuscht'
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1119)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1022)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:989)
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:637)
	... 9 more
Caused by: java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.add(Collections.java:1055)
	at org.languagetool.rules.spelling.SpellingCheckRule.addIgnoreWords(SpellingCheckRule.java:288)
	at org.languagetool.rules.de.GermanSpellerRule.addIgnoreWords(GermanSpellerRule.java:274)
	at org.languagetool.rules.spelling.SpellingCheckRule.init(SpellingCheckRule.java:217)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.init(HunspellRule.java:222)
	at org.languagetool.rules.de.GermanSpellerRule.init(GermanSpellerRule.java:226)
	at org.languagetool.rules.de.SwissGermanSpellerRule.init(SwissGermanSpellerRule.java:45)
	at org.languagetool.rules.spelling.hunspell.HunspellRule.match(HunspellRule.java:96)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:667)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1077)
	... 12 more

**Comment by danielnaber** [comment]
Thanks for the report. How are you calling LT, from your own Java code? Or are you using the command line version?

**Comment by rasael** [comment]
Yes I'm calling LT from Java code. 

I have a static map for each Language and then create a new LT instance (singlethread) for each spellchecking job.

**Comment by danielnaber** [comment]
Please post a self-contained example (e.g. a Junit test), so I can reproduce this.

**Comment by danielnaber** [comment]
Closing, as there was no further feedback.

**Comment by danielnaber** [comment]
Thanks, should be fixed now.
