### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException on LibreOffice extension

### ISSUE THREAD

**Issue by yakovru** [languagetool-org/languagetool#951]
I got java.lang.ArrayIndexOutOfBoundsException on current daily builds LanguageTool LibreOffice extension after open text document in writer:

java.lang.ArrayIndexOutOfBoundsException: -346
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at org.languagetool.openoffice.Main.resetAllParas(Main.java:1057)
	at org.languagetool.openoffice.Main.getParaPos(Main.java:1163)
	at org.languagetool.openoffice.Main.checkParaRules(Main.java:533)
	at org.languagetool.openoffice.Main.doGrammarCheckingInternal(Main.java:359)
	at org.languagetool.openoffice.Main.doProofreading(Main.java:294)

OpenOffice 4.1, LibreOffice 4.2.3.3

**Comment by danielnaber** [comment]
@FredKruse Any idea? Yakov, can you attach that document?

**Comment by dpelle** [comment]
What was the language for grammar checking when this crash occurred? (assuming that language is even relevant)

**Comment by FredKruse** [comment]
I think that will fix the bug.
@yakovru: If you have a document to reproduce the bug, it would be interesting, because I don't understand why a special function failed.

**Comment by yakovru** [comment]
I tested this on several computers,
he bug is reproduced on systems with Java 8.51 and 8.66, and
on Java 8.151 the window with an error does not appear.
I tested it with the document in Russian.

**Comment by yakovru** [comment]
Thanks. Bug fixed.

[test-rus.docx](https://github.com/languagetool-org/languagetool/files/1822619/test-rus.docx)

**Comment by yakovru** [comment]
Fixed in LanguageTool-20180318-snapshot.oxt
