### ISSUE TITLE
[en] testrules is broken (LT 6.4 snapshot 2023-10-22)

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#9518]
```
<snip>LanguageTool-6.4-SNAPSHOT>testrules en
Running XML pattern tests...
LanguageTool version 6.4-SNAPSHOT (2023-10-22 16:50:26 +0000, a7e3199)
Known languages: [Arabic, Asturian, Belarusian, Breton, Catalan, Catalan (Valencian), Catalan (Balearic), Danish, German, German (Germany), German (Austria), German (Swiss), Simple German, Greek, English, English (US), English (GB), English (Australian), English (Canadian), English (New Zealand), English (South African), Esperanto, Spanish, Spanish (voseo), Persian, French, French (Canada), French (Switzerland), French (Belgium), Irish, Galician, Italian, Japanese, Khmer, Dutch, Dutch (Belgium), Polish, Portuguese, Portuguese (Portugal), Portuguese (Brazil), Portuguese (Angola preAO), Portuguese (Moçambique preAO), Romanian, Russian, Slovak, Slovenian, Swedish, Tamil, Tagalog, Ukrainian, Chinese, Testlanguage]
Running XML validation for en/grammar.xml...
Running XML validation for en/style.xml...
Running XML validation for /org/languagetool/rules/en/remote-rule-filters.xml...
Running pattern rule tests for English (org.languagetool.language.English)...
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2ObjectOpenHashMap
        at org.languagetool.rules.AbstractSpecificCaseRule.<clinit>(AbstractSpecificCaseRule.java:43)
        at org.languagetool.language.English.getRelevantRules(English.java:180)
        at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:507)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:339)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:308)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:94)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:84)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:67)
        at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:51)
        at org.languagetool.rules.patterns.PatternRuleTest.createToolForTesting(PatternRuleTest.java:210)
        at org.languagetool.rules.patterns.PatternRuleTest.runTestForLanguage(PatternRuleTest.java:192)
        at org.languagetool.rules.patterns.PatternRuleTest.runGrammarRulesFromXmlTestIgnoringLanguages(PatternRuleTest.java:184)
        at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:927)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 13 more
Running disambiguator rule tests...
Running disambiguation tests for English...
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2ObjectOpenHashMap
        at org.languagetool.rules.AbstractSpecificCaseRule.<clinit>(AbstractSpecificCaseRule.java:43)
        at org.languagetool.language.English.getRelevantRules(English.java:180)
        at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:507)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:339)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:308)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:368)
        at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:274)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.testDisambiguationRulesFromXML(DisambiguationRuleTest.java:71)
        at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest.main(DisambiguationRuleTest.java:246)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 9 more
Running XML bitext pattern tests...
Bitext pattern tests successful.
Validating false-friends.xml...
Validation successfully finished.

```

**Comment by jaumeortola** [comment]
This is probably related to this change: https://github.com/languagetool-org/languagetool/commit/b62f0b783d3adf61a41354c47228ced05b0bcfac 
@SteVio89

**Comment by SteVio89** [comment]
How to reproduce this error?

**Comment by MikeUnwalla** [comment]
@SteVio89, run testrules (https://dev.languagetool.org/development-overview#testing-rules).

**Comment by SteVio89** [comment]
Next snapshot should work again

**Comment by MikeUnwalla** [comment]
@SteVio89, thanks. Fixed.
