### ISSUE TITLE
ConcurrentModificationException in uk.MissingHyphenRule

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#954]
Happens rarely, and maybe only when server starts or is overloaded.

```
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.languagetool.server.TextChecker.checkText(TextChecker.java:154)
	at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:84)
	at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:58)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:123)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at org.languagetool.rules.uk.MissingHyphenRule.<init>(MissingHyphenRule.java:57)
	at org.languagetool.language.Ukrainian.getRelevantRules(Ukrainian.java:164)
	at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:279)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:186)
	at org.languagetool.server.TextChecker.getLanguageToolInstance(TextChecker.java:308)
	at org.languagetool.server.TextChecker.getRuleMatches(TextChecker.java:251)
	at org.languagetool.server.TextChecker.access$000(TextChecker.java:46)
	at org.languagetool.server.TextChecker$1.call(TextChecker.java:145)
	at org.languagetool.server.TextChecker$1.call(TextChecker.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by arysin** [comment]
I've looked at the code and dashPrefixes is private and static, as the concurrency happens in constructor the only way I can see it happening is if MissingHypenRule is constructed multiple times.
As a fix I can either make dashPrefixes non-static (or wrap part of constructor code in synchronize).

**Comment by arysin** [comment]
Those two files would need to be kept in sync, I just realized I can move the set adjustment code into static block, that should take care of it.
