### ISSUE TITLE
NoSuchMethodError: ...rules.AbstractCompoundRule.useSubRuleSpecificIds()

### ISSUE THREAD

**Issue by tonurics** [languagetool-org/languagetool#9681]
languagetool 6.3 dies with the following error:

ERROR o.l.server.LanguageToolHttpHandler An error has occurred: 'java.lang.NoSuchMethodError: 'void org.languagetool.rules.AbstractCompoundRule.useSubRuleSpecificIds()', detected: en-GB', sending HTTP code 500. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, User agent param: webextension-chrome-ng, v: 8.2.1, Referrer: null, language: auto, h: 2, r: 78, time: 6m: TEXTLEVEL_ONLY, l: PICKY, iID: [Removed], Stacktrace follows:java.lang.RuntimeException: java.lang.NoSuchMethodError: 'void org.languagetool.rules.AbstractCompoundRule.useSubRuleSpecificIds()', detected: en-GB

**Comment by noraj** [comment]
```
➜ languagetool --version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp
LanguageTool version 6.3 (2023-10-06 20:34:38 +0000, fb238b2)

➜ java --version                                                
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)
```

```
nov. 29 10:30:53 norarch systemd[1]: Started Languagetool HTTP server.
░░ Subject: A start job for unit languagetool.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit languagetool.service has finished successfully.
░░ 
░░ The job identifier is 94.
nov. 29 10:30:54 norarch languagetool[895]: 2023-11-29 09:30:54 +0000 Setting up thread pool with 10 threads
nov. 29 10:30:54 norarch languagetool[895]: WARN: no common words file defined for Japanese - this language might not be correctly auto-detected
nov. 29 10:30:54 norarch languagetool[895]: WARN: no common words file defined for Khmer - this language might not be correctly auto-detected
nov. 29 10:30:55 norarch languagetool[895]: 2023-11-29 09:30:55 +0000 Starting LanguageTool 6.3 (build date: 2023-10-06 20:34:38 +0000, fb238b2) server on http://localhost:8081...
nov. 29 10:30:55 norarch languagetool[895]: 2023-11-29 09:30:55 +0000 Server started
nov. 29 10:31:52 norarch languagetool[895]: ERROR o.l.server.LanguageToolHttpHandler An error has occurred: 'Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null', sending HTTP code 500. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0, User agent param: webextension-firefox-ng, v: 8.3.0, Referrer: null, language: auto, h: 2, r: 2, time: 113m: ALL_BUT_TEXTLEVEL_ONLY, l: PICKY, iID: 30809:1701250306691, Stacktrace follows:java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.TextChecker.checkText(TextChecker.java:376)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:176)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.ApiV2.lambda$handleRequest$4(ApiV2.java:86)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:86)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.LanguageToolHttpHandler.lambda$handle$0(LanguageToolHttpHandler.java:202)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:202)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
nov. 29 10:31:52 norarch languagetool[895]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
nov. 29 10:31:52 norarch languagetool[895]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
nov. 29 10:31:52 norarch languagetool[895]:         at java.base/java.lang.Thread.run(Thread.java:1583)
nov. 29 10:31:52 norarch languagetool[895]: ERROR o.l.server.LanguageToolHttpHandler An error has occurred: 'Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null', sending HTTP code 500. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0, User agent param: webextension-firefox-ng, v: 8.3.0, Referrer: null, language: auto, h: 2, r: 2, time: 113m: TEXTLEVEL_ONLY, l: PICKY, iID: 30809:1701250306691, Stacktrace follows:java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.TextChecker.checkText(TextChecker.java:376)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:176)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.ApiV2.lambda$handleRequest$4(ApiV2.java:86)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:86)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.LanguageToolHttpHandler.lambda$handle$0(LanguageToolHttpHandler.java:202)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
nov. 29 10:31:52 norarch languagetool[895]:         at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:202)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
nov. 29 10:31:52 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
nov. 29 10:31:52 norarch languagetool[895]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
nov. 29 10:31:52 norarch languagetool[895]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
nov. 29 10:31:52 norarch languagetool[895]:         at java.base/java.lang.Thread.run(Thread.java:1583)
nov. 29 10:31:56 norarch languagetool[895]: ERROR o.l.server.LanguageToolHttpHandler An error has occurred: 'Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null', sending HTTP code 500. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0, User agent param: webextension-firefox-ng, v: 8.3.0, Referrer: null, language: auto, h: 1, r: 4, time: 0m: TEXTLEVEL_ONLY, l: PICKY, iID: 30809:1701250306691, Stacktrace follows:java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.TextChecker.checkText(TextChecker.java:376)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:176)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.ApiV2.lambda$handleRequest$4(ApiV2.java:86)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:86)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.LanguageToolHttpHandler.lambda$handle$0(LanguageToolHttpHandler.java:202)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:202)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
nov. 29 10:31:56 norarch languagetool[895]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
nov. 29 10:31:56 norarch languagetool[895]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
nov. 29 10:31:56 norarch languagetool[895]:         at java.base/java.lang.Thread.run(Thread.java:1583)
nov. 29 10:31:56 norarch languagetool[895]: ERROR o.l.server.LanguageToolHttpHandler An error has occurred: 'Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null', sending HTTP code 500. Access from 127.0.0.1, HTTP user agent: Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0, User agent param: webextension-firefox-ng, v: 8.3.0, Referrer: null, language: auto, h: 1, r: 4, time: 1m: ALL_BUT_TEXTLEVEL_ONLY, l: PICKY, iID: 30809:1701250306691, Stacktrace follows:java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.TextChecker.checkText(TextChecker.java:376)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:176)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.ApiV2.lambda$handleRequest$4(ApiV2.java:86)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:86)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.LanguageToolHttpHandler.lambda$handle$0(LanguageToolHttpHandler.java:202)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
nov. 29 10:31:56 norarch languagetool[895]:         at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:202)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
nov. 29 10:31:56 norarch languagetool[895]:         at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
nov. 29 10:31:56 norarch languagetool[895]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
nov. 29 10:31:56 norarch languagetool[895]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
nov. 29 10:31:56 norarch languagetool[895]:         at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by noraj** [comment]
My issue seems similar but may no be related.

**Comment by danielnaber** [comment]
@noraj  Please start LT with the `--config` option and an empty config file to see if that helps.
