### ISSUE TITLE
Crash with Russian in AbstractCompoundRule

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#969]
Problem is in `RuleMatch ruleMatch = new RuleMatch(this, sentence, firstMatchToken.getStartPos(), atr.getEndPos(), msg, shortDesc);` - start position is 14, end position is 0 - can be reproduced with "Ведь сейчас в Лос Анджелесе"

```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Russian): 'Ведь сейчас в Лос Анджелесе'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.languagetool.server.TextChecker.checkText(TextChecker.java:154)
	at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:84)
	at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:58)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:121)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: Russian): 'Ведь сейчас в Лос Анджелесе'
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:641)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:580)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:538)
	at org.languagetool.server.TextChecker.getRuleMatches(TextChecker.java:252)
	at org.languagetool.server.TextChecker.access$000(TextChecker.java:46)
	at org.languagetool.server.TextChecker$1.call(TextChecker.java:145)
	at org.languagetool.server.TextChecker$1.call(TextChecker.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.lang.RuntimeException: Could not check sentence (language: Russian): 'Ведь сейчас в Лос Анджелесе'
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1119)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1022)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:989)
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:637)
	... 10 more
Caused by: java.lang.RuntimeException: fromPos (14) must be less than toPos (0)
	at org.languagetool.rules.RuleMatch.<init>(RuleMatch.java:127)
	at org.languagetool.rules.RuleMatch.<init>(RuleMatch.java:99)
	at org.languagetool.rules.AbstractCompoundRule.match(AbstractCompoundRule.java:141)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:667)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1077)
	... 13 more

```

**Comment by danielnaber** [comment]
@f-knorr seems to be caused by the fix for #934 on 2018-03-11, after that change, the wrong item is fetched from `stringToToken`.

**Comment by yakovru** [comment]
I think it can depend on https://github.com/languagetool-org/languagetool/issues/793

**Comment by danielnaber** [comment]
If I comment out `stringToCheck = StringUtils.uncapitalize(stringToCheck);`, the crash is gone. Indeed @yakovru added `super.sentenceStartsWithUpperCase = true;` on 2018-03-19.

**Comment by yakovru** [comment]
I added a unit tests for compounds like "Ведь сейчас в Лос-Анджелесе", "Лос-Анджелес", etc.
