### ISSUE TITLE
languagetool 6.3 always reaturns status 500 - Cannot invoke contains because getAbTest() is null

### ISSUE THREAD

**Issue by Orgoth** [languagetool-org/languagetool#9757]
System: Ryzen 7700, 64GB Ram, 1tb nvme, 1gbit/s
OS: Debian 12
Languagetool: 6.3
cmd: screen -d -m  /usr/bin/java -Xmx1500M -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --public --allow-origin "*"

Even the text of this ticket is resulting in a 500 error, which you can see below.
Is there a way to enable debug or logging, to see what the underlying problem is?

2023-11-27 08:22:44.976 GMT+01:00 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-11-27 08:22:45.049 GMT+01:00 ERROR org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null', sending HTTP code 500. Access from 192.168.6.1, HTTP user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, User agent param: webextension-chrome-ng, v: 8.3.0, Referrer: null, language: auto, h: 2, r: 2, time: 87m: TEXTLEVEL_ONLY, l: PICKY, iID: 12410:1701069470883, Stacktrace follows:java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because the return value of "org.languagetool.server.HTTPServerConfig.getAbTest()" is null
        at org.languagetool.server.TextChecker.checkText(TextChecker.java:376)
        at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:176)
        at org.languagetool.server.ApiV2.lambda$handleRequest$4(ApiV2.java:86)
        at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
        at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:86)
        at org.languagetool.server.LanguageToolHttpHandler.lambda$handle$0(LanguageToolHttpHandler.java:202)
        at org.languagetool.tools.TelemetryProvider.createSpan(TelemetryProvider.java:96)
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:202)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:851)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:818)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by danielnaber** [comment]
Should be fixed with tomorrow's build, please see https://forum.languagetool.org/t/self-hosted-languagetool-server-and-chrome-add-on/9519/2

**Comment by noraj** [comment]
I have the same issue (cf. https://github.com/languagetool-org/languagetool/issues/9681#issuecomment-1831544570).

Ok I read the workaround about adding `--config=` mentionned in https://forum.languagetool.org/t/self-hosted-languagetool-server-and-chrome-add-on/9519/3. But does a server or browser extension fix is planned?

**Comment by danielnaber** [comment]
> But does a long term server or browser extension fix is planned?

This will be fixed with the next release in March 2024. As the workaround is so simple, we don't plan an extra fix release just for this.

**Comment by Orgoth** [comment]
The workaround does not work for me.
```
/usr/bin/java -Xmx1500M -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --public --allow-origin "*" --config
```

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
        at org.languagetool.server.HTTPServerConfig.<init>(HTTPServerConfig.java:243)
        at org.languagetool.server.HTTPServer.main(HTTPServer.java:170)
```

**Comment by danielnaber** [comment]
Please specify an empty config file, not `/dev/null`

**Comment by Orgoth** [comment]
What is a empty config file for you?
Do you mean /home/lang/empty.cfg?

**Comment by Orgoth** [comment]
Since it is too much for @danielnaber to simply provide a sniped.  
Here is a simple bash variant and how the server call must or should look.  
This makes it much easier to understand, as --config is not really well documented.
https://github.com/search?q=repo%3Alanguagetool-org%2Flanguagetool%20--config&type=code

```bash
touch /home/lang/empty.cfg
/usr/bin/java -Xmx1500M -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --public --allow-origin "*" --config /home/language/empty.cfg
```

**Comment by noraj** [comment]
> Please specify an empty config file, not `/dev/null` or nothing

`--config` with no file doesn't work but `--config /dev/null` works.

For those having a systemd unit / service file:

`sudo systemctl edit languagetool.service` (will produce an override file, e.g. `/etc/systemd/system/languagetool.service.d/override.conf`)

```ini
[Service]
# reset list to avoid append
ExecStart=
# Workaround https://github.com/languagetool-org/languagetool/issues/9757
ExecStart=/usr/bin/languagetool --http --allow-origin "*" --config /dev/null
```
