### ISSUE TITLE
Usage of "checkCancelCallback" throws IndexOutOfBounds error

### ISSUE THREAD

**Issue by nandorszabo** [languagetool-org/languagetool#9852]
When we set a `CheckCancelCallback` implementation on a JLanguageTool instance, and the `checkCancelled` method returns `true` at some point during a `check` run, the result is not handled and returns a random error.
So we can not really decide whether the error was caused by us because we cancelled it, or it's a random error during normal run. Here is an example, when being cancelled during first sentence of passed in content, but it varies based on when the cancellation happens:

`{"name":"java.lang.IndexOutOfBoundsException","message":"Index 0 out of bounds for length 0","extendedStackTrace":"java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
at org.languagetool.JLanguageTool.computeSentenceData(JLanguageTool.java:1376) ~[languagetool-core-6.3.jar!/:?
at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1358) ~[languagetool-core-6.3.jar!/:?]
at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:1010) ~[languagetool-core-6.3.jar!/:?]
at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:972) ~[languagetool-core-6.3.jar!/:?]
at org.languagetool.JLanguageTool.check(JLanguageTool.java:916) ~[languagetool-core-6.3.jar!/:?]
at org.languagetool.JLanguageTool.check(JLanguageTool.java:901) ~[languagetool-core-6.3.jar!/:?]
at org.languagetool.JLanguageTool.check(JLanguageTool.java:891) ~[languagetool-core-6.3.jar!/:?]
at org.languagetool.JLanguageTool.check(JLanguageTool.java:873) ~[languagetool-core-6.3.jar!/:?]
at org.languagetool.JLanguageTool.check(JLanguageTool.java:830) ~[languagetool-core-6.3.jar!/:?]
at org.languagetool.JLanguageTool.check(JLanguageTool.java:814) ~[languagetool-core-6.3.jar!/:?]}`

**Comment by abimael-turing** [comment]
Hello @Luisa-LT, would you like me to assist you with this issue?

**Comment by abimael-turing** [comment]
Can you provide more information about the situation in which the error occurred? I would like to know how to reproduce the error to better understand the issue.

**Comment by abimael-turing** [comment]
@nandorszabo How can I help?

**Comment by nandorszabo** [comment]
@abimael-turing The issue can be reproduced by creating a single instance of `JLanguageTool`, and set a `checkCancelCallback` logic on it, which terminates based on some logic you set. Then trigger two requests simultaneously, so that the first request would end up triggering the `checkCancelCallback` with a `true` result.
Normally you'd expect a `null` result for a cancellation, or a cancellation specific exception, but currently a random exception is being thrown (e.g. `IndexOutOfBoundsException`), which is not ideal, as we can't decide whether a runtime error was caused during the check or it was triggered by the cancellation and should be treated differently.
