### ISSUE TITLE
[nl] dump wjhile executing locally

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9869]
Expected text language: Dutch
Working on /media/ruud/ssd1/LT/nl.txt...
Exception in thread "main" java.lang.NoClassDefFoundError: org/languagetool/tools/TelemetryProvider
        at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:1023)
        at org.languagetool.JLanguageTool.checkInternal(JLanguageTool.java:980)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:923)
        at org.languagetool.JLanguageTool.check(JLanguageTool.java:908)
        at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:112)
        at org.languagetool.commandline.CommandLineTools.checkText(CommandLineTools.java:88)
        at org.languagetool.commandline.Main.runOnFile(Main.java:186)
        at org.languagetool.commandline.Main.main(Main.java:454)
Caused by: java.lang.ClassNotFoundException: org.languagetool.tools.TelemetryProvider
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 8 more

Any idea what could cause this?

**Comment by danielnaber** [comment]
What command exactly do you call and which version of LT is this?

**Comment by baarsrj** [comment]
It was the build of the current version. It might be a temporary hickup. I will try again tomorrow.Op 8 dec. 2023 19:57 schreef Daniel Naber ***@***.***>:
What command exactly do you call and which version of LT is this?

**Comment by baarsrj** [comment]
Could not reproduce today.
